# import dan konfig awal

In [17]:
import os
import subprocess
import time
import shutil
import csv
from datetime import datetime
import stat

import ast
import json
import shutil
import builtins
import re
import pandas as pd

import cProfile
import pstats
import tempfile

from IPython.display import display

import timeit
import contextlib
import io
import threading

from tqdm.notebook import tqdm
import sys

In [18]:
# KONFIGURASI

input_file = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\asli\nim_github(12).txt"
projects_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset12\kode_github(12)"
os.makedirs(projects_folder, exist_ok=True)

In [19]:
# output folder

log_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(12)"
os.makedirs(log_folder, exist_ok=True)

# Pengumpulan Data

## konfigurasi log proses clone

In [4]:
# konfigurasi output untuk proses clone
clone_excel = os.path.join(log_folder, "hasil_clone.xlsx")
clone_json = os.path.join(log_folder, "hasil_clone.json")
clone_csv = os.path.join(log_folder, "hasil_clone.csv")

In [5]:
# LOG CLONE
log_file = os.path.join(log_folder, "log_clone.csv")

# SETUP LOG

if not os.path.exists(log_file):
    with open(log_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["timestamp", "nim", "url", "status", "message"])


def write_log(nim, url, status, message):
    with open(log_file, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            nim,
            url,
            status,
            message
        ])

## Clone/Pengumpulan Data

In [6]:
# github token
GITHUB_TOKEN = "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"


def add_token(url):

    if url.startswith("https://github.com"):

        url = url.replace(
            "https://",
            f"https://{GITHUB_TOKEN}@"
        )

    return url

In [7]:
# BACA DATASET
# dataset berupa nim | url
def load_dataset(file_path):
    dataset = []

    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split("|")

            if len(parts) != 2:
                continue

            nim = parts[0].strip()
            url = parts[1].strip()

            dataset.append((nim, url))

    return dataset

In [8]:
# HANYA SIMPAN .py & .ipynb

def keep_only_code_files(repo_path):

    for root, dirs, files in os.walk(repo_path):

        # Jangan masuk folder .git
        if ".git" in dirs:
            dirs.remove(".git")

        for file in files:
            if not (file.endswith(".py") or file.endswith(".ipynb")):
                try:
                    os.remove(os.path.join(root, file))
                except:
                    pass

    # Hapus folder kosong
    for root, dirs, files in os.walk(repo_path, topdown=False):
        if not os.listdir(root):
            try:
                os.rmdir(root)
            except:
                pass

In [9]:
# HITUNG FILE KODE

def count_code_files(repo_path):

    py_count = 0
    ipynb_count = 0

    for root, dirs, files in os.walk(repo_path):

        if ".git" in dirs:
            dirs.remove(".git")

        for file in files:
            if file.endswith(".py"):
                py_count += 1
            elif file.endswith(".ipynb"):
                ipynb_count += 1

    return py_count, ipynb_count

In [10]:
# Remove folder gagal

def remove_readonly(func, path, exc_info):
    """
    Menghapus atribut read-only lalu retry delete.
    """
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except Exception as e:
        print(f"Gagal paksa hapus: {path}")
        print(f"->   Alasan: {str(e)}")

In [11]:
# menghitung modul atau folder di dalam repo

def count_modules(repo_path):

    modules = []

    for item in os.listdir(repo_path):
        full_path = os.path.join(repo_path, item)

        if os.path.isdir(full_path) and item != ".git":
            modules.append(item)

    return len(modules)

In [12]:
results = []

def clone_repo(repo_list):
    global success_count, fail_count, skip_count
    global total_py_files, total_ipynb_files

    success_count = fail_count = skip_count = 0
    total_py_files = total_ipynb_files = 0

    with tqdm(total=len(repo_list), desc="Cloning Repos", unit="repo") as pbar:
        for nim, url in repo_list:
            target_path = os.path.join(projects_folder, nim)

            def save(status, message, module=0, py=0, ipynb=0):
                results.append({
                    "nim": nim, 
                    "url": url, 
                    "status": status,
                    "message": message, 
                    "module": module,
                    "py_files": py, 
                    "ipynb_files": ipynb,
                    "total_files": py + ipynb
                })

            if not nim:
                pbar.write(f"[SKIP] URL tanpa NIM → {url}")
                write_log("", url, "SKIPPED", "NIM kosong")
                skip_count += 1
                save("SKIPPED", "NIM Kosong")
                pbar.update(1)
                continue

            if "/tree/" in url:
                url = url.split("/tree/")[0]

            if os.path.exists(target_path):
                pbar.write(f"[SKIP] {url} sudah diclone.")
                write_log(nim, url, "SKIPPED", "Folder sudah ada")
                skip_count += 1

                py, ipynb = count_code_files(target_path)
                module = count_modules(target_path)
                total_py_files += py
                total_ipynb_files += ipynb

                save("SKIPPED", "Folder sudah ada", module, py, ipynb)
                pbar.update(1)
                continue

            try:
                auth_url = add_token(url)
                subprocess.run(
                    ["git", "clone", "--depth", "1", auth_url, target_path],
                    check=True,
                    timeout=900,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.PIPE
                )

                keep_only_code_files(target_path)
                py, ipynb = count_code_files(target_path)
                module = count_modules(target_path)

                total_py_files += py
                total_ipynb_files += ipynb
                success_count += 1

                write_log(nim, url, "SUCCESS", f"Clone berhasil | module:{module} | py:{py} ipynb:{ipynb}")

                save("SUCCESS", "Clone berhasil", module, py, ipynb)

            except subprocess.CalledProcessError as e:
                error_msg = e.stderr.decode(errors="ignore")

                pbar.write(f"❌ Gagal clone {url} \n {error_msg}")
                write_log(nim, url, "FAILED", error_msg)

                if os.path.exists(target_path):
                    try:
                        shutil.rmtree(target_path, onerror=remove_readonly)
                        pbar.write("🧹 Folder clone dihapus\n------------------------")
                    except Exception as err:
                        pbar.write(f"⚠ Gagal hapus folder: {err}")

                fail_count += 1
                save("FAILED", error_msg)
                
            except subprocess.TimeoutExpired:
                pbar.write(f"❌ Gagal clone {url} \n Timeout Clone")
                write_log(nim, url, "FAILED", "Timeout")

                if os.path.exists(target_path):
                    try:
                        shutil.rmtree(target_path, onerror=remove_readonly)
                        pbar.write("🧹 Folder clone dihapus\n----------")
                    except Exception as err:
                        pbar.write(f"⚠ Gagal hapus folder: {err}")

                fail_count += 1
                save("FAILED", "Timeout Clone")

            finally:
                pbar.update(1)

In [13]:
dataset = load_dataset(input_file)
total_url = len(dataset)

success_count = 0
fail_count = 0
skip_count = 0

total_py_files = 0
total_ipynb_files = 0

print(f"\nTotal input URL: {total_url}\n")

# jalankan cloning
clone_repo(dataset)

repo_count = len([
    d for d in os.listdir(projects_folder)
    if os.path.isdir(os.path.join(projects_folder, d))
])

print("="*40)
print("HASIL CLONING")
print("="*40)
print(f"Total repo dalam dataset   : {repo_count}")
print(f"Berhasil clone    : {success_count}")
print(f"Gagal clone       : {fail_count}")
print(f"Skipped           : {skip_count}")
print(f"Total file .py    : {total_py_files}")
print(f"Total file .ipynb : {total_ipynb_files}")
print(f"Total file kode   : {total_py_files + total_ipynb_files}")

print("="*40)
print(f"Log tersimpan di: {log_file}")
print(f"Dataset tersimpan di: {projects_folder}")

Total input URL: 12

Cloning Repos:   0%|          | 0/12 [00:00<?, ?repo/s]

[SKIP] https://github.com/Katakon17/2241720092_ML_2025 sudah diclone.
❌ Gagal clone https://github.com/fajrulsantoso/244107023010_ML_2025
 Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset12\kode_github(12)\244107023010'...
error: invalid path 'JS08 /JS08'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


🧹 Folder clone dihapus
------------------------
[SKIP] https://github.com/emkafie/Machine-Learning sudah diclone.
[SKIP] https://github.com/AstorBoy11/2341720095_ML_2025.git sudah diclone.
[SKIP] https://github.com/NathanaelGracedo/2341720217_ML_2025 sudah diclone.
[SKIP] https://github.com/Oktavian19/2341720117_ML_2025 sudah diclone.
❌ Gagal clone https://github.com/alfbrynn/2341720025_ML_2025
 Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset12\kode_github(12)\2341720025'...
remote: Repository not found.
fatal: repository 'https://github.com/alfbrynn/2341720025_ML_2025/' not found

[SKIP] https://github.com/SatrioHubs/2341720163_ML_2025 sudah diclone.
[SKIP] https://github.com/soulqan/2341720191_ML_2025 sudah diclone.
========================================
HASIL CLONING
========================================
Total repo dalam dataset   : 10
Berhasil clone    : 3
Gagal clone       : 2
Skipped           : 7
Total file .py    : 505
Total file .ipynb : 450
Total file kode   : 955
========================================
Log tersimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(12)\log_clone.csv
Dataset tersimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset12\kode_github(12)

In [31]:
# hasil clone
df = pd.DataFrame(results)

# simpan file hasil
df.to_excel(clone_excel, index=False)
df.to_csv(clone_csv, index=False)

with open(clone_json, "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)

print("\nFile hasil disimpan di:")
print(clone_excel)
print(clone_csv)
print(clone_json)

# TAMPILKAN TABEL
print("\n===== DATA HASIL CLONING =====\n")
display(df.head(10))

File hasil disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(12)\hasil_clone.xlsx
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(12)\hasil_clone.csv
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(12)\hasil_clone.json

===== DATA HASIL CLONING =====

,nim,url,status,message,module,py_files,ipynb_files,total_files
0,2241720092,https://github.com/Katakon17/2241720092_ML_2025,SKIPPED,Folder sudah ada,5,0,22,22
1,244107023010,https://github.com/fajrulsantoso/244107023010_...,FAILED,Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skri...,0,0,0,0
2,2341720176,https://github.com/emkafie/Machine-Learning,SKIPPED,Folder sudah ada,1,0,51,51
3,2341720095,https://github.com/AstorBoy11/2341720095_ML_20...,SKIPPED,Folder sudah ada,10,0,43,43
4,2341720217,https://github.com/NathanaelGracedo/2341720217...,SKIPPED,Folder sudah ada,15,0,52,52
5,2341720117,https://github.com/Oktavian19/2341720117_ML_2025,SKIPPED,Folder sudah ada,15,9,50,59
6,2341720025,https://github.com/alfbrynn/2341720025_ML_2025,FAILED,Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skri...,0,0,0,0
7,2341720163,https://github.com/SatrioHubs/2341720163_ML_2025,SKIPPED,Folder sudah ada,0,0,4,4
8,2341720191,https://github.com/soulqan/2341720191_ML_2025,SKIPPED,Folder sudah ada,16,491,62,553
9,2341720174,https://github.com/Atadewa/2341720174_ML_2025,SUCCESS,Clone berhasil,16,2,52,54

# normalisasi (baru)

In [24]:
# ===============================
# LOG NORMALISASI
# ===============================

normStruktur_excel = os.path.join(log_folder, "log_normalisasi.xlsx")

log_records = []

def write_log(nim, action, detail, status="SUCCESS", message=""):

    log_records.append({
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "nim": nim,
        "action": action,
        "detail": detail,
        "status": status,
        "message": message
    })

In [30]:
normalized_folder = projects_folder + "_normalized"
os.makedirs(normalized_folder, exist_ok=True)


# =====================================================
# IDENTIFIKASI MODULE
# =====================================================

def identify_module(text):

    text = text.upper()
    
    # PBL
    if "PBL" in text:
        return "pbl"

    # UTS
    if re.search(r"\bUTS\b|UJIAN\s*TENGAH\s*SEMESTER", text):
        return "uts"

    # UAS
    if re.search(r"\bUAS\b|UJIAN\s*AKHIR\s*SEMESTER", text):
        return "uas"
    
    # KUIS
    if re.search(r"KUIS|QUIZ", text):
        return "kuis"
    
    # KELOMPOK
    match = re.search(r"KELOMPOK|GROUP", text)
    if match:
        return "kelompok"
    
    # JS / JOBSHEET / PERTEMUAN
    match = re.search(r"(JS|JOBSHEET|PERTEMUAN|SESI|MODUL|MODULE|PRAKTIKUM)\s*0?(\d+)", text)
    if match:
        return f"js{int(match.group(2)):02d}"

    return None


# =====================================================
# IDENTIFIKASI FILE TYPE
# =====================================================

def normalize_filename(file):

    name = file.upper()
    ext = os.path.splitext(file)[1].lower()
    
    # PBL
    if "PBL" in name:
        return f"pbl{ext}"
    
    # KELOMPOK
    if re.search(r"KELOMPOK|GROUP", name):
        return f"kelompok{ext}"

    # UTS
    if re.search(r"\bUTS\b|UJIAN\s*TENGAH\s*SEMESTER", name):
        return f"uts{ext}"

    # UAS
    if re.search(r"\bUAS\b|UJIAN\s*AKHIR\s*SEMESTER", name):
        return f"uas{ext}"
    
    # KUIS
    if re.search(r"KUIS|QUIZ", name):
        return f"kuis{ext}"

    # PRAKTIKUM
    match = re.search(r"\bP\s*0?(\d+)", name)
    if match:
        return f"p{int(match.group(1)):02d}{ext}"

    # TUGAS PRAKTIKUM
    if re.search(r"(TP|TG|TUGAS)", name):
        return f"tp{ext}"

    return None


# =====================================================
# HAPUS FOLDER YANG TIDAK PERLU
# =====================================================
def remove_readonly(func, path, _):
    os.chmod(path, stat.S_IWRITE)
    func(path)
    
def remove_unnecessary(repo, remove_list, nim):

    for root, dirs, files in os.walk(repo):

        for d in dirs[:]:
            if d in remove_list:
                path = os.path.join(root, d)

                try:
                    shutil.rmtree(path, onerror=remove_readonly)
                    dirs.remove(d)
                    write_log(nim, "REMOVE_FOLDER", path)
                except Exception as e:
                    write_log(nim, "REMOVE_FOLDER", path, "FAILED", str(e))
                    tqdm.write(f"[ERROR] {nim} | REMOVE_FOLDER | {path} | {str(e)}")


# =====================================================
# CARI MODULE DARI PATH
# =====================================================

def detect_module_from_path(root, file):

    module = None

    # cek semua folder dalam path
    for part in root.split(os.sep):

        module = identify_module(part)

        if module:
            return module

    # jika tidak ditemukan → cek dari file
    module = identify_module(file)

    return module


# =====================================================
# NORMALISASI REPOSITORY
# =====================================================

def normalize_repository(repo_path):

    nim = os.path.basename(repo_path)
    normalized_repo = os.path.join(normalized_folder, nim)

    if os.path.exists(normalized_repo):
        shutil.rmtree(normalized_repo)
    
    os.makedirs(normalized_repo, exist_ok=True)

    remove_list = [".env", ".venv", "env", "venv", "__pycache__", ".git"]
    remove_unnecessary(normalized_repo, remove_list, nim)

    unclassified = os.path.join(normalized_repo, "unclassified")
    os.makedirs(unclassified, exist_ok=True)

    moved_files = []

    # scan semua file dulu
    for root, dirs, files in os.walk(repo_path):
        # jangan masuk ke folder .git dan venv
        dirs[:] = [d for d in dirs if d not in [".git", ".venv", "__pycache__", "env", "colab lama"]]
        for file in files:

            if not (file.endswith(".py") or file.endswith(".ipynb")):
                continue

            file_path = os.path.join(root, file)

            moved_files.append((root, file, file_path))


    # proses pemindahan
    for root, file, file_path in tqdm(
        moved_files,
        desc=f"{nim}",
        unit="file",
        leave=False,
        dynamic_ncols=True
    ):

        module = detect_module_from_path(root, file)

        if module:
            target_folder = os.path.join(normalized_repo, module)
        else:
            target_folder = unclassified

        os.makedirs(target_folder, exist_ok=True)

        new_name = normalize_filename(file)
        if new_name and new_name != file:
            write_log(nim, "RENAME_FILE", f"{file} -> {new_name}")

        if not new_name:
            new_name = file

        target_path = os.path.join(target_folder, new_name)

        # hindari overwrite
        counter = 1
        base, ext = os.path.splitext(new_name)

        while os.path.exists(target_path):
            counter += 1
            target_path = os.path.join(
                target_folder,
                f"{base}{counter}{ext}"
            )
            write_log(nim, "DUPLICATE_RENAME", f"{new_name} -> {base}{counter}{ext}")

        try:
            shutil.copy2(file_path, target_path)
            write_log(nim, "MOVE_FILE", f"{file_path} -> {target_path}")
        except Exception as e:
            write_log(nim, "MOVE_FILE", file_path, "FAILED", str(e))
            tqdm.write(f"[ERROR] {nim} | MOVE_FILE | {file_path} | {str(e)}")


# =====================================================
# NORMALISASI DATASET
# =====================================================

print("\nMulai normalisasi dataset...\n")

total_repo = 0
repos = [
    r for r in os.listdir(projects_folder)
    if os.path.isdir(os.path.join(projects_folder, r))
]

for repo in tqdm(repos, desc="Normalizing Repositories", unit="repo"):
    repo_path = os.path.join(projects_folder, repo)
    try:
        normalize_repository(repo_path)
    except Exception as e:
        tqdm.write(f"[ERROR] Repository {repo} gagal diproses: {str(e)}")
        write_log(repo, "NORMALIZE_REPO", repo_path, "FAILED", str(e))
    total_repo += 1


print("\n===== NORMALISASI SELESAI =====")
print(f"Total repository : {total_repo}")



# ===============================
# SIMPAN LOG
# ===============================

df_log = pd.DataFrame(log_records)

df_log.to_excel(normStruktur_excel, index=False)

print("\nLog normalisasi disimpan di:")
print(normStruktur_excel)

print("="*35)
print("DATA LOG NORMALISASI")
print("-"*35)
display(df_log.head(10))

Mulai normalisasi dataset...

Normalizing Repositories:   0%|          | 0/10 [00:00<?, ?repo/s]

2241720092:   0%|          | 0/22 [00:00<?, ?file/s]

2341720047:   0%|          | 0/54 [00:00<?, ?file/s]

2341720095:   0%|          | 0/43 [00:00<?, ?file/s]

2341720117:   0%|          | 0/59 [00:00<?, ?file/s]

2341720163:   0%|          | 0/4 [00:00<?, ?file/s]

2341720174:   0%|          | 0/54 [00:00<?, ?file/s]

2341720176:   0%|          | 0/51 [00:00<?, ?file/s]

2341720191:   0%|          | 0/50 [00:00<?, ?file/s]

2341720217:   0%|          | 0/52 [00:00<?, ?file/s]

2341720248:   0%|          | 0/63 [00:00<?, ?file/s]

===== NORMALISASI SELESAI =====
Total repository : 10

Log normalisasi disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(12)\log_normalisasi.xlsx
===================================
DATA LOG NORMALISASI
-----------------------------------

,timestamp,nim,action,detail,status,message
0,2026-03-20 13:33:17,2241720092,RENAME_FILE,Uts.ipynb -> uts.ipynb,SUCCESS,
1,2026-03-20 13:33:17,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
2,2026-03-20 13:33:17,2241720092,RENAME_FILE,P1_JS13.ipynb -> p01.ipynb,SUCCESS,
3,2026-03-20 13:33:17,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
4,2026-03-20 13:33:17,2241720092,RENAME_FILE,P2_JS13.ipynb -> p02.ipynb,SUCCESS,
5,2026-03-20 13:33:17,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
6,2026-03-20 13:33:17,2241720092,RENAME_FILE,P3_JS13.ipynb -> p03.ipynb,SUCCESS,
7,2026-03-20 13:33:17,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
8,2026-03-20 13:33:17,2241720092,RENAME_FILE,TP_JS13.ipynb -> tp13.ipynb,SUCCESS,
9,2026-03-20 13:33:17,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,

# normalisasi struktur direktori

In [ ]:
normalized_folder = projects_folder + "_normalized"
os.makedirs(normalized_folder, exist_ok=True)

In [ ]:
def remove_empty_folders(base_path):
    """
    Menghapus semua folder kosong kecuali folder utama mahasiswa.
    """
    for root, dirs, files in os.walk(base_path, topdown=False):

        # Jangan hapus root utama mahasiswa
        if root == base_path:
            continue

        if not os.listdir(root):
            try:
                os.rmdir(root)
            except:
                pass

In [ ]:
# log untuk normalisasi struktur

log_file = os.path.join(log_folder, "log_normalisasiStruktur.csv")

# SETUP LOG

if not os.path.exists(log_file):
    with open(log_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["timestamp", "nim", "action", "detail"])


def write_log(nim, action, detail):
    with open(log_file, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            nim,
            action,
            detail
        ])

In [ ]:
def identify_module_from_name(name):

    name_upper = name.upper()

    # PRIORITAS KHUSUS DULU
    if "KUIS" in name_upper:
        return "kuis"

    if "UTS" in name_upper:
        return "uts"

    if "PBL" in name_upper:
        return "pbl"

    match_kel = re.search(r"KELOMPOK\s*0?(\d+)?", name_upper)
    if match_kel:
        number = match_kel.group(1)
        number = int(number) if number else 1
        return f"kelompok{number:02d}"

    # BARU JSxx
    match_js = re.search(r"JS\s?0?(\d+)", name_upper)
    if match_js:
        return f"m{int(match_js.group(1)):02d}"

    return None

In [ ]:
# NORMALISASI FILE

def normalize_file_name(file_name, module_folder, counter_dict):

    name_upper = file_name.upper()
    ext = os.path.splitext(file_name)[1].lower()

    # PRAKTIKUM Pxx
    match_p = re.search(r"\bP\s?0?(\d+)", name_upper)
    if match_p:
        number = int(match_p.group(1))
        return f"p{number:02d}{ext}"

    # TPxx
    match_tp = re.search(r"TP\s*0?(\d+)?", name_upper)
    if match_tp:
        number = match_tp.group(1)
        number = int(number) if number else 1
        return f"tp{number:02d}{ext}"

    # kelompok
    match_kel = re.search(r"KELOMPOK\s*0?(\d+)?", name_upper)
    if match_kel:
        number = match_kel.group(1)
        number = int(number) if number else 1
        return f"kelompok{number:02d}{ext}"

    # KUIS / UTS
    if module_folder in ["kuis", "uts", "pbl"]:
        return f"{module_folder}{ext}"

    return file_name

In [ ]:
# NORMALISASI REPO
def normalize_repository(nim_path):

    global total_py_dataset
    global total_ipynb_dataset
    global total_repo

    nim = os.path.basename(nim_path)
    print(f"\n🔎 Normalisasi {nim}")

    # Copy repo ke folder normalized
    normalized_nim_path = os.path.join(normalized_folder, nim)

    if os.path.exists(normalized_nim_path):
        shutil.rmtree(normalized_nim_path)

    shutil.copytree(nim_path, normalized_nim_path)

    # Setelah dicopy → semua proses normalisasi dilakukan di folder ini
    working_path = normalized_nim_path

    # Hapus folder .env jika ada
    env_path = os.path.join(working_path, ".env")
    if os.path.exists(env_path):
        shutil.rmtree(env_path, ignore_errors=True)
        write_log(nim, "DELETE_FOLDER", ".env removed")

    counter_dict = {}
    py_count = 0
    ipynb_count = 0
    total_files = 0

    unclassified_path = os.path.join(working_path, "unclassified")
    os.makedirs(unclassified_path, exist_ok=True)

    # =========================
    # STEP 1 - Rename folder level atas
    # =========================
    for folder in os.listdir(working_path):

        old_folder_path = os.path.join(working_path, folder)

        if not os.path.isdir(old_folder_path):
            continue

        new_module = identify_module_from_name(folder)

        if new_module:
            new_folder_path = os.path.join(working_path, new_module)

            if old_folder_path != new_folder_path:

                if not os.path.exists(new_folder_path):
                    os.rename(old_folder_path, new_folder_path)
                    write_log(nim, "RENAME_FOLDER", f"{folder} → {new_module}")

                else:
                    for item in os.listdir(old_folder_path):
                        src_item = os.path.join(old_folder_path, item)
                        dst_item = os.path.join(new_folder_path, item)

                        if not os.path.exists(dst_item):
                            shutil.move(src_item, dst_item)
                        else:
                            base, ext = os.path.splitext(item)
                            counter = 1
                            while True:
                                new_name = f"{base}_{counter}{ext}"
                                new_dst = os.path.join(
                                    new_folder_path, new_name)

                                if not os.path.exists(new_dst):
                                    shutil.move(src_item, new_dst)
                                    break

                                counter += 1

                    if os.path.exists(old_folder_path):
                        shutil.rmtree(old_folder_path, ignore_errors=True)

                    write_log(nim, "MERGE_FOLDER", f"{folder} → {new_module}")

    # =========================
    # STEP 2 - Pindahkan & rename file
    # =========================
    for root, dirs, files in os.walk(working_path):

        for file in files:

            if not (file.endswith(".py") or file.endswith(".ipynb")):
                continue

            total_files += 1

            if file.endswith(".py"):
                py_count += 1
                total_py_dataset += 1

            if file.endswith(".ipynb"):
                ipynb_count += 1
                total_ipynb_dataset += 1

            file_path = os.path.join(root, file)

            module = identify_module_from_name(root)

            if not module:
                module = identify_module_from_name(file)

            if not module:
                target_folder = unclassified_path
            else:
                target_folder = os.path.join(working_path, module)
                os.makedirs(target_folder, exist_ok=True)

            if module not in counter_dict:
                counter_dict[module] = 0

            new_name = normalize_file_name(file, module, counter_dict)
            target_path = os.path.join(target_folder, new_name)

            if file_path != target_path:
                shutil.move(file_path, target_path)
                write_log(nim, "MOVE_RENAME_FILE",
                          f"{file} → {module}/{new_name}")

    # =========================
    # STEP 3 - Hapus folder kosong
    # =========================
    remove_empty_folders(working_path)

    print(
        f"   ✅ Selesai {nim}             ||  .py : {py_count}        |   .ipynb : {ipynb_count}")
    print(f"       Total files  : {total_files}")

In [ ]:
print("Mulai normalisasi struktur & nama file")
total_py_dataset = 0
total_ipynb_dataset = 0
total_repo = 0

for student in os.listdir(projects_folder):

    student_path = os.path.join(projects_folder, student)

    if os.path.isdir(student_path):
        normalize_repository(student_path)
        total_repo += 1

print("\n===== NORMALISASI SELESAI =====")
print(f"Log tersimpan di: {log_file}")

print("\n===== STATISTIK DATASET =====")
print(f"Total repository : {total_repo}")
print(f"Total file .py   : {total_py_dataset}")
print(f"Total file .ipynb: {total_ipynb_dataset}")
print(f"Total kode file  : {total_py_dataset + total_ipynb_dataset}")

🚀 Mulai normalisasi struktur & nama file...

🔎 Normalisasi 2241720092
   ✅ Selesai 2241720092             ||  .py : 0        |   .ipynb : 22
       Total files  : 22

🔎 Normalisasi 2341720081
   ✅ Selesai 2341720081             ||  .py : 0        |   .ipynb : 48
       Total files  : 48

🔎 Normalisasi 2341720095
   ✅ Selesai 2341720095             ||  .py : 0        |   .ipynb : 43
       Total files  : 43

🔎 Normalisasi 2341720096
   ✅ Selesai 2341720096             ||  .py : 2        |   .ipynb : 55
       Total files  : 57

🔎 Normalisasi 2341720117
   ✅ Selesai 2341720117             ||  .py : 9        |   .ipynb : 49
       Total files  : 58

🔎 Normalisasi 2341720163
   ✅ Selesai 2341720163             ||  .py : 0        |   .ipynb : 5
       Total files  : 5

🔎 Normalisasi 2341720176
   ✅ Selesai 2341720176             ||  .py : 0        |   .ipynb : 51
       Total files  : 51

🔎 Normalisasi 2341720187
   ✅ Selesai 2341720187             ||  .py : 1        |   .ipynb : 55
       Total files  : 56

===== NORMALISASI SELESAI =====
Log tersimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(10)\log_normalisasiStruktur.csv

===== STATISTIK DATASET =====
Total repository : 8
Total file .py   : 12
Total file .ipynb: 328
Total kode file  : 340

# convert ke py

In [ ]:
# konfigurasi folder hasil convert
converted_folder = normalized_folder + "_py"
os.makedirs(converted_folder, exist_ok=True)

In [ ]:
# menghapus magic command dari ipynb
def clean_magic_commands(code):

    code = re.sub(r"^\s*%.*$", "", code, flags=re.MULTILINE)
    code = re.sub(r"^\s*!.*$", "", code, flags=re.MULTILINE)
    return code

In [ ]:
# KONVERSI NOTEBOOK

def convert_ipynb_to_py(ipynb_path, py_path):

    try:

        with open(ipynb_path, "r", encoding="utf-8") as f:
            notebook = json.load(f)

        code_cells = []

        for cell in notebook.get("cells", []):

            if cell.get("cell_type") != "code":
                continue

            source = "".join(cell.get("source", []))
            source = clean_magic_commands(source)

            code_cells.append(source)

        if not code_cells:
            raise Exception("Notebook tidak memiliki code cell")

        code = "\n\n".join(code_cells)

        with open(py_path, "w", encoding="utf-8") as f:
            f.write(code)

        return True, None

    except Exception as e:
        return False, str(e)

In [ ]:
from tqdm import tqdm
import os
import shutil

total_py_original = 0
total_ipynb = 0
converted_success = 0
converted_failed = 0

error_logs = []  # 🔥 simpan error di sini

# kumpulkan file
all_files = []
for root, dirs, files in os.walk(projects_folder):
    for file in files:
        all_files.append((root, file))

# progress bar (TIDAK ADA PRINT DI DALAM LOOP)
pbar = tqdm(all_files, desc="📦 Processing Dataset", unit="file")

for root, file in pbar:

    relative_path = os.path.relpath(root, projects_folder)
    new_root = os.path.join(converted_folder, relative_path)
    os.makedirs(new_root, exist_ok=True)

    source_path = os.path.join(root, file)

    if file.endswith(".py"):
        target_path = os.path.join(new_root, file)
        shutil.copy2(source_path, target_path)
        total_py_original += 1

    elif file.endswith(".ipynb"):

        total_ipynb += 1

        new_name = file.replace(".ipynb", ".py")
        target_path = os.path.join(new_root, new_name)

        success, error = convert_ipynb_to_py(source_path, target_path)

        if success:
            converted_success += 1
        else:
            converted_failed += 1

            # 🔥 SIMPAN ERROR (tidak print di sini!)
            error_logs.append({
                "file": source_path,
                "error": error
            })

    # update info kecil di progress bar
    pbar.set_postfix({
        "ok": converted_success,
        "fail": converted_failed
    })

pbar.close()

# ===== TAMPILKAN ERROR SETELAH SELESAI =====
print("\n===== ERROR LOG =====")

if not error_logs:
    print("Tidak ada error 🎉")
else:
    for err in error_logs[:10]:  # tampilkan max 10 saja biar tidak spam
        print(f"❌ {err['file']}")
        print(f"   Alasan: {err['error']}")

    if len(error_logs) > 10:
        print(f"\n... dan {len(error_logs)-10} error lainnya")

# ===== STATISTIK =====
total_py_output = total_py_original + converted_success

print("\n===== STATISTIK KONVERSI DATASET =====")
print(f"Total file .py asli     : {total_py_original}")
print(f"Total file .ipynb asli  : {total_ipynb}")
print(f"Berhasil convert        : {converted_success}")
print(f"Gagal convert           : {converted_failed}")
print(f"Total file .py output   : {total_py_output}")

print("\nDataset hasil convert tersimpan di:")
print(converted_folder)

📦 Processing Dataset: 100%|██████████| 562/562 [00:05<00:00, 103.51file/s, ok=326, fail=1]

===== ERROR LOG =====
❌ D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\kode_github(10)\2341720081\JS15\P2_JS15.ipynb
   Alasan: Expecting value: line 1 column 1 (char 0)

===== STATISTIK KONVERSI DATASET =====
Total file .py asli     : 11
Total file .ipynb asli  : 327
Berhasil convert        : 326
Gagal convert           : 1
Total file .py output   : 337

Dataset hasil convert tersimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\kode_github(10)_normalized_py

# Waktu eksekusi

## seluruh project (CProfile)

In [ ]:
# KONFIGURASI

# dataset_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\kode_github_py"

dataset_folder = converted_folder

output_csv = os.path.join(log_folder, "runtime_cprofile.csv")
output_excel = os.path.join(log_folder, "runtime_cprofile.xlsx")
output_json = os.path.join(log_folder, "runtime_cprofile.json")

TIMEOUT = 30

In [ ]:
# FUNCTION PROFILING
def run_with_cprofile(file_path):

    try:

        # membuat file sementara untuk profil
        with tempfile.NamedTemporaryFile(delete=False) as temp_prof:
            profile_file = temp_prof.name

        subprocess.run(
            [
                "python",
                "-m",
                "cProfile",
                "-o",
                profile_file,
                file_path
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            timeout=TIMEOUT
        )

        stats = pstats.Stats(profile_file)

        runtime = stats.total_tt

        os.remove(profile_file)

        return "SUCCESS", runtime, ""

    except subprocess.TimeoutExpired:

        return "TIMEOUT", None, "Execution timeout"

    except Exception as e:

        return "FAILED", None, str(e)

In [ ]:
# EKSTRAK METADATA

def extract_metadata(file_path, dataset_folder):

    # ambil path relatif dari dataset
    rel_path = os.path.relpath(file_path, dataset_folder)

    parts = rel_path.split(os.sep)

    # file name
    file_name = parts[-1]

    # nim = folder pertama
    nim = parts[0] if len(parts) >= 2 else "unknown"

    # module = folder setelah nim (jika ada)
    module = parts[1] if len(parts) >= 3 else "root"

    return nim, module, file_name

In [ ]:
# LOOP DATASET

records = []
total_files = 0

print("\n========== MULAI PROFILING ==========\n")

for root, dirs, files in os.walk(dataset_folder):

    for file in files:

        if not file.endswith(".py"):
            continue

        file_path = os.path.join(root, file)

        nim, module, file_name = extract_metadata(file_path, dataset_folder)

        print(f"[RUN] {nim}/{module}/{file_name}")

        status, runtime, message = run_with_cprofile(file_path)

        total_files += 1

        records.append({
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "nim": nim,
            "module": module,
            "file_name": file_name,
            "file_path": file_path,
            "status": status,
            "execution_time_seconds": runtime,
            "message": message
        })

print("\n========== PROFILING SELESAI ==========\n")

========== MULAI PROFILING ==========

[RUN] 2241720092/root/Uts.py
[RUN] 2241720092/Artificial Neural Network (ANN) dan Evaluasi Classifier/P1_JS13.py
[RUN] 2241720092/Artificial Neural Network (ANN) dan Evaluasi Classifier/P2_JS13.py
[RUN] 2241720092/Artificial Neural Network (ANN) dan Evaluasi Classifier/P3_JS13.py
[RUN] 2241720092/Artificial Neural Network (ANN) dan Evaluasi Classifier/TP_JS13.py
[RUN] 2241720092/Convolutional Neural Network/P1_JS14.py
[RUN] 2241720092/Convolutional Neural Network/P2_JS14.py
[RUN] 2241720092/Convolutional Neural Network/TP_JS14.py
[RUN] 2241720092/Ekstraksi Fitur/P1_JS03.py
[RUN] 2241720092/Ekstraksi Fitur/P2_JS03.py
[RUN] 2241720092/Ekstraksi Fitur/P3_JS03.py
[RUN] 2241720092/Ekstraksi Fitur/P4_JS03.py
[RUN] 2241720092/Ekstraksi Fitur/TP_JS03.py
[RUN] 2241720092/Klasterisasi/P1_JS04.py
[RUN] 2241720092/Klasterisasi/P2_JS04.py
[RUN] 2241720092/Klasterisasi/P3_JS04.py
[RUN] 2241720092/Klasterisasi/TP_JS04.py
[RUN] 2241720092/Pemahaman data/P1_JS02.py
[RUN] 2241720092/Pemahaman data/P2_JS02.py
[RUN] 2241720092/Pemahaman data/P3_JS02.py
[RUN] 2241720092/Pemahaman data/P4_JS02.py
[RUN] 2241720092/Pemahaman data/TP_JS02.py
[RUN] 2341720081/JS02/P1_JS02.py
[RUN] 2341720081/JS02/P2_JS02.py
[RUN] 2341720081/JS02/P3_JS02.py
[RUN] 2341720081/JS02/P4_JS02.py
[RUN] 2341720081/JS02/TP_JS02.py
[RUN] 2341720081/JS03/P1_JS03.py
[RUN] 2341720081/JS03/P2_JS03.py
[RUN] 2341720081/JS03/P3_JS03.py
[RUN] 2341720081/JS03/P4_JS03.py
[RUN] 2341720081/JS03/TP_JS03.py
[RUN] 2341720081/JS04/P1_JS04.py
[RUN] 2341720081/JS04/P2_JS04.py
[RUN] 2341720081/JS04/P3_JS04.py
[RUN] 2341720081/JS04/TP_JS04.py
[RUN] 2341720081/JS05/P1_JS05.py
[RUN] 2341720081/JS05/P2_JS05.py
[RUN] 2341720081/JS05/TP_JS05.py
[RUN] 2341720081/JS06/P1_JS06.py
[RUN] 2341720081/JS06/P2_JS06.py
[RUN] 2341720081/JS06/TP_JS06.py
[RUN] 2341720081/JS07/P1_JS07.py
[RUN] 2341720081/JS07/P2_JS07.py
[RUN] 2341720081/JS07/P3_JS07.py
[RUN] 2341720081/JS07/P4_JS07.py
[RUN] 2341720081/JS07/P5_JS07.py
[RUN] 2341720081/JS07/P6_JS07.py
[RUN] 2341720081/JS07/TP_JS07.py
[RUN] 2341720081/JS08/TP_JS08.py
[RUN] 2341720081/JS09/P1_JS09.py
[RUN] 2341720081/JS09/P2_JS09.py
[RUN] 2341720081/JS09/P3_JS09.py
[RUN] 2341720081/JS09/TP_JS09_1.py
[RUN] 2341720081/JS09/TP_JS09_2.py
[RUN] 2341720081/JS11/P1_JS11.py
[RUN] 2341720081/JS11/P2_JS11.py
[RUN] 2341720081/JS11/P3_JS11.py
[RUN] 2341720081/JS11/P4_JS11.py
[RUN] 2341720081/JS11/P5_JS11.py
[RUN] 2341720081/JS11/TP_JS11.py
[RUN] 2341720081/JS13/P1_JS13.py
[RUN] 2341720081/JS13/P2_JS13.py
[RUN] 2341720081/JS13/P3_JS13.py
[RUN] 2341720081/JS13/TP_JS13.py
[RUN] 2341720081/JS14/P1_JS14.py
[RUN] 2341720081/JS14/P2_JS14.py
[RUN] 2341720081/JS14/TP_JS14.py
[RUN] 2341720081/JS15/P1_JS15.py
[RUN] 2341720081/PBL/Digital_Text_OCR.py
[RUN] 2341720081/PBL/OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py
[RUN] 2341720081/UTS/idn-notebook.py
[RUN] 2341720081/UTS/notebook.py
[RUN] 2341720095/JS02/P1_JS02.py
[RUN] 2341720095/JS02/P2_JS02.py
[RUN] 2341720095/JS02/P3_JS02.py
[RUN] 2341720095/JS02/P4_JS02.py
[RUN] 2341720095/JS02/TP_JS02.py
[RUN] 2341720095/JS03/P1_JS03.py
[RUN] 2341720095/JS03/P2_JS03.py
[RUN] 2341720095/JS03/P3_JS03.py
[RUN] 2341720095/JS03/P4_JS03.py
[RUN] 2341720095/JS03/TP_JS03.py
[RUN] 2341720095/JS04/P1_JS04.py
[RUN] 2341720095/JS04/P2_JS04.py
[RUN] 2341720095/JS04/P3_JS04.py
[RUN] 2341720095/JS04/TP_JS04.py
[RUN] 2341720095/JS05/P1_JS05.py
[RUN] 2341720095/JS05/P2_JS05.py
[RUN] 2341720095/JS05/TP_JS05.py
[RUN] 2341720095/JS06/P1_JS06.py
[RUN] 2341720095/JS06/P2_JS06.py
[RUN] 2341720095/JS06/TP_JS06.py
[RUN] 2341720095/JS07/P1_JS07.py
[RUN] 2341720095/JS07/P2_JS07.py
[RUN] 2341720095/JS07/P3_JS07.py
[RUN] 2341720095/JS07/P4_JS07.py
[RUN] 2341720095/JS07/P5_JS07.py
[RUN] 2341720095/JS07/P6_JS07.py
[RUN] 2341720095/JS07/TP_JS066.py
[RUN] 2341720095/JS08/TP_JS08.py
[RUN] 2341720095/JS09/P1_JS09.py
[RUN] 2341720095/JS09/P2_JS09.py
[RUN] 2341720095/JS09/P3_JS09.py
[RUN] 2341720095/JS09/TP_JS09_1.py
[RUN] 2341720095/JS09/TP_JS09_2.py
[RUN] 2341720095/JS11/P1_JS11.py
[RUN] 2341720095/JS11/P2_JS11.py
[RUN] 2341720095/JS11/P3_JS11.py
[RUN] 2341720095/JS11/P4_JS11.py
[RUN] 2341720095/JS11/P5_JS11.py
[RUN] 2341720095/JS11/TP_JS11.py
[RUN] 2341720095/JS13/P1_JS13.py
[RUN] 2341720095/JS13/P2_JS13.py
[RUN] 2341720095/JS13/P3_JS13.py
[RUN] 2341720095/JS13/TP_JS13.py
[RUN] 2341720096/root/Giovano_Alkandri_ML_QUIZ1.py
[RUN] 2341720096/JS01/P1_JS01.py
[RUN] 2341720096/JS02/P1_JS02.py
[RUN] 2341720096/JS02/P2_JS02.py
[RUN] 2341720096/JS02/P3_JS02.py
[RUN] 2341720096/JS02/P4_JS02.py
[RUN] 2341720096/JS02/TP_JS02.py
[RUN] 2341720096/JS03/P1_JS03.py
[RUN] 2341720096/JS03/P2_JS03.py
[RUN] 2341720096/JS03/P3_JS03.py
[RUN] 2341720096/JS03/P4_JS03.py
[RUN] 2341720096/JS03/TP_JS03.py
[RUN] 2341720096/JS04/P1_JS04.py
[RUN] 2341720096/JS04/P2_JS04.py
[RUN] 2341720096/JS04/P3_JS04.py
[RUN] 2341720096/JS04/TP_JS04.py
[RUN] 2341720096/JS05/P1_JS05.py
[RUN] 2341720096/JS05/P2_JS05.py
[RUN] 2341720096/JS05/TP_JS05.py
[RUN] 2341720096/JS06/P1_JS06.py
[RUN] 2341720096/JS06/P2_JS06.py
[RUN] 2341720096/JS06/T1_JS06.py
[RUN] 2341720096/JS06/teoridasar.py
[RUN] 2341720096/JS07/P1_JS07.py
[RUN] 2341720096/JS07/P2_JS07.py
[RUN] 2341720096/JS07/P3_JS07.py
[RUN] 2341720096/JS07/P4_JS07.py
[RUN] 2341720096/JS07/P5_JS07.py
[RUN] 2341720096/JS07/P6_JS07.py
[RUN] 2341720096/JS07/TP_JS07.py
[RUN] 2341720096/JS08/TP_JS08.py
[RUN] 2341720096/JS08/uts copy.py
[RUN] 2341720096/JS08/uts.py
[RUN] 2341720096/JS09/P1_JS09.py
[RUN] 2341720096/JS09/P2_JS09.py
[RUN] 2341720096/JS09/P3_JS09.py
[RUN] 2341720096/JS09/TP_JS09_1.py
[RUN] 2341720096/JS09/TP_JS09_2.py
[RUN] 2341720096/JS11/P1_JS11.py
[RUN] 2341720096/JS11/P2_JS11.py
[RUN] 2341720096/JS11/P3_JS11.py
[RUN] 2341720096/JS11/P4_JS11.py
[RUN] 2341720096/JS11/P5_JS11.py
[RUN] 2341720096/JS11/TP_JS11.py
[RUN] 2341720096/JS13/P1_JS13.py
[RUN] 2341720096/JS13/P2_JS13.py
[RUN] 2341720096/JS13/P3_JS13.py
[RUN] 2341720096/JS13/TP_JS13.py
[RUN] 2341720096/JS14/P1_JS14.py
[RUN] 2341720096/JS14/P2_JS14.py
[RUN] 2341720096/JS14/TP_JS14.py
[RUN] 2341720096/JS15/app.py
[RUN] 2341720096/JS15/P1_JS15.py
[RUN] 2341720096/JS15/P2_JS15.py
[RUN] 2341720096/PBL/train svm prepro.py
[RUN] 2341720117/JS01/TG1_2341720117_OKTAVIAN_EKA_RAMADHAN.py
[RUN] 2341720117/JS02/P1_JS02.py
[RUN] 2341720117/JS02/P2_JS02.py
[RUN] 2341720117/JS02/P3_JS02.py
[RUN] 2341720117/JS02/P4_JS02.py
[RUN] 2341720117/JS02/TP_JS02.py
[RUN] 2341720117/JS03/P1_JS03.py
[RUN] 2341720117/JS03/P2_JS03.py
[RUN] 2341720117/JS03/P3_JS03.py
[RUN] 2341720117/JS03/P4_JS03.py
[RUN] 2341720117/JS03/TP_JS03.py
[RUN] 2341720117/JS04/P1_JS04.py
[RUN] 2341720117/JS04/P2_JS04.py
[RUN] 2341720117/JS04/P3_JS04.py
[RUN] 2341720117/JS04/TP_JS04.py
[RUN] 2341720117/JS05/P1_JS05.py
[RUN] 2341720117/JS05/P2_JS05.py
[RUN] 2341720117/JS05/TP_JS05.py
[RUN] 2341720117/JS06/P1_JS06.py
[RUN] 2341720117/JS06/P2_JS06.py
[RUN] 2341720117/JS06/TP_JS06.py
[RUN] 2341720117/JS07/P1_JS07.py
[RUN] 2341720117/JS07/P2_JS07.py
[RUN] 2341720117/JS07/P3_JS07.py
[RUN] 2341720117/JS07/P4_JS07.py
[RUN] 2341720117/JS07/P5_JS07.py
[RUN] 2341720117/JS07/P6_JS07.py
[RUN] 2341720117/JS07/TP_JS07.py
[RUN] 2341720117/JS09/P1_JS09.py
[RUN] 2341720117/JS09/P2_JS09.py
[RUN] 2341720117/JS09/P3_JS09.py
[RUN] 2341720117/JS09/TP_JS09_1.py
[RUN] 2341720117/JS09/TP_JS09_2.py
[RUN] 2341720117/JS11/P1_JS11.py
[RUN] 2341720117/JS11/P2_JS11.py
[RUN] 2341720117/JS11/P3_JS11.py
[RUN] 2341720117/JS11/P4_JS11.py
[RUN] 2341720117/JS11/P5_JS11.py
[RUN] 2341720117/JS11/TP_JS11.py
[RUN] 2341720117/JS13/P1_JS13.py
[RUN] 2341720117/JS13/P2_JS13.py
[RUN] 2341720117/JS13/P3_JS13.py
[RUN] 2341720117/JS13/TP_JS13.py
[RUN] 2341720117/JS14/P1_JS14.py
[RUN] 2341720117/JS14/P2_JS14.py
[RUN] 2341720117/JS14/TP_JS14.py
[RUN] 2341720117/JS15/P1_JS15.py
[RUN] 2341720117/JS15/app.py
[RUN] 2341720117/JS15/app.py
[RUN] 2341720117/KUIS/TP_JS08.py
[RUN] 2341720117/PBL_FastAPI/Salinan PBL_ML Regression Risk_V1.py
[RUN] 2341720117/PBL_FastAPI/config.py
[RUN] 2341720117/PBL_FastAPI/main.py
[RUN] 2341720117/PBL_FastAPI/schemas.py
[RUN] 2341720117/PBL_FastAPI/feature_builder.py
[RUN] 2341720117/PBL_FastAPI/model_loader.py
[RUN] 2341720117/PBL_FastAPI/predictor.py
[RUN] 2341720117/PBL_FastAPI/risk_analyzer.py
[RUN] 2341720117/UTS/UTS.py
[RUN] 2341720163/root/JS2_2341720163_Satrio_Ahmad_Ramadhani.py
[RUN] 2341720163/root/JS3_2341720163_Satrio_Ahmad_Ramadhani.py
[RUN] 2341720163/root/Satrio_Ahmad_Ramadhani_2341720163_27_KUIS1_ML.py
[RUN] 2341720163/root/TG1_2341720163_Satrio_Ahmad_Ramadhani.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS01.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS01.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS02.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS02.py
[RUN] 2341720176/2341720176_ML_2025/P3_JS02.py
[RUN] 2341720176/2341720176_ML_2025/P4_JS02.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS02.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS03.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS03.py
[RUN] 2341720176/2341720176_ML_2025/P3_JS03.py
[RUN] 2341720176/2341720176_ML_2025/P4_JS03.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS03.py
[RUN] 2341720176/2341720176_ML_2025/KUIS_1.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS04.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS04.py
[RUN] 2341720176/2341720176_ML_2025/P3_JS04.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS04.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS05.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS05.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS05.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS06.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS06.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS06.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS07.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS07.py
[RUN] 2341720176/2341720176_ML_2025/P3_JS07.py
[RUN] 2341720176/2341720176_ML_2025/P4_JS07.py
[RUN] 2341720176/2341720176_ML_2025/P5_JS07.py
[RUN] 2341720176/2341720176_ML_2025/P6_JS07.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS07.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS08.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS09.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS09.py
[RUN] 2341720176/2341720176_ML_2025/P3_JS09.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS09_1.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS09_2.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS11.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS11.py
[RUN] 2341720176/2341720176_ML_2025/P3_JS11.py
[RUN] 2341720176/2341720176_ML_2025/P4_JS11.py
[RUN] 2341720176/2341720176_ML_2025/P5_JS11.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS11.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS13.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS13.py
[RUN] 2341720176/2341720176_ML_2025/P3_JS13.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS13.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS14.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS14.py
[RUN] 2341720176/2341720176_ML_2025/TP_JS14.py
[RUN] 2341720176/2341720176_ML_2025/P1_JS15.py
[RUN] 2341720176/2341720176_ML_2025/P2_JS15.py
[RUN] 2341720187/JS01/TP_JS01.py
[RUN] 2341720187/JS02/P1_JS02.py
[RUN] 2341720187/JS02/P2_JS02.py
[RUN] 2341720187/JS02/P3_JS02.py
[RUN] 2341720187/JS02/P4_JS02.py
[RUN] 2341720187/JS02/TP_JS02.py
[RUN] 2341720187/JS03/P1_JS03.py
[RUN] 2341720187/JS03/P2_JS03.py
[RUN] 2341720187/JS03/P3_JS03.py
[RUN] 2341720187/JS03/P4_JS03.py
[RUN] 2341720187/JS03/TP_JS03.py
[RUN] 2341720187/JS04/P1_JS04.py
[RUN] 2341720187/JS04/P2_JS04.py
[RUN] 2341720187/JS04/P3_JS04.py
[RUN] 2341720187/JS04/TP_JS04.py
[RUN] 2341720187/JS05/P1_JS05.py
[RUN] 2341720187/JS05/P2_JS05.py
[RUN] 2341720187/JS05/TP_JS05.py
[RUN] 2341720187/JS06/P1_JS07.py
[RUN] 2341720187/JS06/P2_JS07.py
[RUN] 2341720187/JS06/TP_JS06.py
[RUN] 2341720187/JS07/P1_JS07.py
[RUN] 2341720187/JS07/P2_JS07.py
[RUN] 2341720187/JS07/P3_JS07.py
[RUN] 2341720187/JS07/P4_JS07.py
[RUN] 2341720187/JS07/P5_JS07.py
[RUN] 2341720187/JS07/P6_JS07.py
[RUN] 2341720187/JS07/TP_JS07.py
[RUN] 2341720187/JS08/TP_JS08.py
[RUN] 2341720187/JS09/P1_JS09.py
[RUN] 2341720187/JS09/P2_JS09.py
[RUN] 2341720187/JS09/P3_JS09.py
[RUN] 2341720187/JS09/TP_JS09_1.py
[RUN] 2341720187/JS09/TP_JS09_2.py
[RUN] 2341720187/JS11/P1_JS11.py
[RUN] 2341720187/JS11/P2_JS11.py
[RUN] 2341720187/JS11/P3_JS11.py
[RUN] 2341720187/JS11/P4_JS11.py
[RUN] 2341720187/JS11/P5_JS11.py
[RUN] 2341720187/JS11/TP_JS11.py
[RUN] 2341720187/JS13/P1_JS13.py
[RUN] 2341720187/JS13/P2_JS13.py
[RUN] 2341720187/JS13/P3_JS13.py
[RUN] 2341720187/JS13/TP_JS13.py
[RUN] 2341720187/JS14/P1_JS14.py
[RUN] 2341720187/JS14/P2_JS14.py
[RUN] 2341720187/JS14/TP_JS14.py
[RUN] 2341720187/JS15/P1_JS15.py
[RUN] 2341720187/JS15/P2_JS15.py
[RUN] 2341720187/JS15/app.py
[RUN] 2341720187/UAS/UAS.py
[RUN] 2341720187/UTS/UTS_2341720187_CANDRA_AHMAD_DANI.py

========== PROFILING SELESAI ==========

In [ ]:
# DATAFRAME
df = pd.DataFrame(records)

df["execution_time_seconds"] = df["execution_time_seconds"].round(6)

# SIMPAN CSV
df.to_csv(output_csv, index=False)
df.to_excel(output_excel, index=False)

with open(output_json, "w", encoding="utf-8") as f:
    json.dump(records, f, indent=4)

# TAMPILKAN TABEL
print("========== TABEL HASIL RUNTIME ==========\n")

display_columns = [
    "nim",
    "module",
    "file_name",
    "status",
    "execution_time_seconds"
]

display(df[display_columns])

========== TABEL HASIL RUNTIME ==========

,nim,module,file_name,status,execution_time_seconds
0,2241720092,root,Uts.py,SUCCESS,0.745290
1,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P1_JS13.py,SUCCESS,6.107665
2,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P2_JS13.py,SUCCESS,3.387265
3,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P3_JS13.py,SUCCESS,0.243612
4,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,TP_JS13.py,SUCCESS,0.000795
...,...,...,...,...,...
332,2341720187,JS15,P1_JS15.py,SUCCESS,1.074874
333,2341720187,JS15,P2_JS15.py,SUCCESS,0.188612
334,2341720187,JS15,app.py,SUCCESS,0.621026
335,2341720187,UAS,UAS.py,SUCCESS,0.192998
336,2341720187,UTS,UTS_2341720187_CANDRA_AHMAD_DANI.py,SUCCESS,0.179863

In [ ]:
# STATISTIK RINGKAS

print("\n========== RINGKASAN ==========\n")

summary = {
    "Total file dijalankan": total_files,
    "SUCCESS": (df["status"] == "SUCCESS").sum(),
    "FAILED": (df["status"] == "FAILED").sum(),
    "TIMEOUT": (df["status"] == "TIMEOUT").sum(),
    "Rata-rata runtime": round(df["execution_time_seconds"].mean(), 6)
}

summary_df = pd.DataFrame(list(summary.items()), columns=["Metric", "Value"])

display(summary_df)

print("\nTop 5 runtime terlama:")

top_runtime = (
    df.sort_values("execution_time_seconds", ascending=False)
    [["nim", "module", "file_name", "execution_time_seconds"]]
    .head()
)

display(top_runtime)

print("\nHasil lengkap disimpan di:")
print(output_csv)
print(output_excel)
print(output_json)

========== RINGKASAN ==========

                  Metric       Value
0  Total file dijalankan  337.000000
1                SUCCESS  333.000000
2                 FAILED    3.000000
3                TIMEOUT    1.000000
4      Rata-rata runtime    0.700901

Top 5 runtime terlama:

,nim,module,file_name,execution_time_seconds
1,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P1_JS13.py,6.107665
25,2341720081,JS02,P4_JS02.py,3.966546
34,2341720081,JS04,P3_JS04.py,3.710639
156,2341720096,JS11,P3_JS11.py,3.634451
2,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P2_JS13.py,3.387265

Hasil lengkap disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(10)\runtime_cprofile.csv
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(10)\runtime_cprofile.xlsx
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing(10)\runtime_cprofile.json

## per function (timeit)

In [ ]:
# KONFIGURASI
# dataset_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\kode_github(10)_py"
dataset_folder = converted_folder

output_csv = os.path.join(log_folder, "runtime_per_function.csv")
output_excel = os.path.join(log_folder, "runtime_per_function.xlsx")
output_json = os.path.join(log_folder, "runtime_per_function.json")

RUN_REPEAT = 3
TIMEOUT = 30

In [ ]:
# BLOK INPUT
builtins.input = lambda *args: "0"

In [ ]:
# EKSTRAK METADATA

def extract_metadata(file_path, dataset_folder):

    # ambil path relatif dari dataset
    rel_path = os.path.relpath(file_path, dataset_folder)

    parts = rel_path.split(os.sep)

    # file name
    file_name = parts[-1]

    # nim = folder pertama
    nim = parts[0] if len(parts) >= 2 else "unknown"

    # module = folder setelah nim (jika ada)
    module = parts[1] if len(parts) >= 3 else "root"

    return nim, module, file_name

In [ ]:
# EXTRACT FUNCTION DARI AST
def extract_functions(file_path):

    with open(file_path, "r", encoding="utf8", errors="ignore") as f:
        code = f.read()

    try:
        tree = ast.parse(code)
    except:
        return []

    functions = []

    for node in tree.body:

        if isinstance(node, ast.FunctionDef):

            func_code = ast.get_source_segment(code, node)

            functions.append((node.name, func_code))

    return functions

In [ ]:
# GENERATE WRAPPER
def generate_wrapper(func_name, func_code):

    try:

        tree = ast.parse(func_code)
        func_node = tree.body[0]

        param_count = len(func_node.args.args)

        dummy_args = ",".join(["0"] * param_count)

    except:

        dummy_args = ""

    wrapper = f"""
{func_code}

def __wrapper():
    try:
        {func_name}({dummy_args})
    except:
        pass
"""

    return wrapper

In [ ]:
# RUN DENGAN TIMEOUT (THREAD)
def run_with_timeout(code):

    result = {"status": None, "runtime": None, "message": ""}

    def worker():
        original_stdout = sys.stdout
        try:

            local_env = {}

            dummy = io.StringIO()

            # override input agar tidak menunggu user
            local_env["input"] = lambda *args: "0"
            exec(code, local_env)

            with contextlib.redirect_stdout(dummy), contextlib.redirect_stderr(dummy):

                runtime = timeit.timeit(
                    "__wrapper()",
                    globals=local_env,
                    number=RUN_REPEAT
                )

            result["status"] = "SUCCESS"
            result["runtime"] = runtime / RUN_REPEAT

        except Exception as e:

            result["status"] = "FAILED"
            result["message"] = str(e)

    thread = threading.Thread(target=worker)

    thread.start()
    thread.join(TIMEOUT)

    if thread.is_alive():

        return "TIMEOUT", None, "Execution timeout"

    return result["status"], result["runtime"], result["message"]

In [ ]:
import os
from collections import defaultdict
from datetime import datetime
from tqdm import tqdm

records = []

print("\n" + "-"*50)
print(" ANALISIS RUNTIME per FUNCTION")

skip_funcs = ["main", "menu", "run", "start", "program", "main_menu"]

total_functions = 0
status_counter = defaultdict(int)

start_time = datetime.now()

# 🔹 Ambil semua file dulu (biar tqdm bisa hitung total)
all_py_files = []
for root, dirs, files in os.walk(dataset_folder):
    for file in files:
        if file.endswith(".py"):
            all_py_files.append(os.path.join(root, file))

# 🔹 Progress bar untuk FILE
for file_path in tqdm(all_py_files, desc=">> Processing Files", unit="file"):

    nim, module, file_name = extract_metadata(file_path, dataset_folder)
    functions = extract_functions(file_path)

    if not functions:
        status_counter["NO FUNCTION"] += 1

        records.append({
            "nim": nim,
            "module": module,
            "file_name": file_name,
            "function_name": "NO_FUNCTION",
            "status": "NO FUNCTION",
            "runtime_seconds": None,
            "message": "No function detected"
        })
        continue

    # 🔹 Progress bar untuk FUNCTION (nested, optional)
    for func_name, func_code in tqdm(
        functions,
        desc=f"⚙️ {file_name}",
        leave=False,
        unit="func"
    ):
        total_functions += 1
        if func_name.lower() in skip_funcs:
            status_counter["SKIPPED"] += 1

            records.append({
                "nim": nim,
                "module": module,
                "file_name": file_name,
                "function_name": func_name,
                "status": "SKIPPED",
                "runtime_seconds": None,
                "message": "Skipped Function"
            })
            continue

        wrapper_code = generate_wrapper(func_name, func_code)
        status, runtime, message = run_with_timeout(wrapper_code)

        status_counter[status] += 1

        records.append({
            "nim": nim,
            "module": module,
            "file_name": file_name,
            "function_name": func_name,
            "status": status,
            "runtime_seconds": runtime,
            "message": message
        })

# ===== SUMMARY =====
end_time = datetime.now()
duration = (end_time - start_time).total_seconds()

print("\n" + "="*50)
print("RINGKASAN")
print("-"*50)
print(f"Total file      : {len(all_py_files)}")
print(f"Total function  : {total_functions}")
print(f"Durasi          : {duration:.2f} detik")

print("\nStatus:")
for k, v in status_counter.items():
    print(f"- {k:<10}: {v}")

print("="*50 + "\n")

==================================================
🚀 ANALISIS RUNTIME per FUNCTION
==================================================

📂 Processing Files: 100%|██████████| 337/337 [00:03<00:00, 94.90file/s]

==================================================
📊 RINGKASAN
==================================================
Total file      : 337
Total function  : 323
Durasi          : 3.62 detik

Status:
- NO FUNCTION: 237
- SUCCESS   : 268
- FAILED    : 53
- SKIPPED   : 2
==================================================

In [ ]:
# SIMPAN DATA RUNTIME PER FUNCTION

df = pd.DataFrame(records)

df["runtime_seconds"] = pd.to_numeric(df["runtime_seconds"], errors="coerce")
# format runtime agar tidak scientific notation
df["runtime_seconds"] = df["runtime_seconds"].round(10)

df.to_csv(output_csv, index=False, float_format="%.10f")
with pd.ExcelWriter(output_excel, engine="xlsxwriter") as writer:

    df.to_excel(writer, index=False, sheet_name="runtime")

    workbook = writer.book
    worksheet = writer.sheets["runtime"]

    number_format = workbook.add_format({'num_format': '0.0000000000'})

    runtime_col = df.columns.get_loc("runtime_seconds")

    worksheet.set_column(runtime_col, runtime_col, 18, number_format)

with open(output_json, "w", encoding="utf-8") as f:
    json.dump(records, f, indent=4, default=str)

print("Hasil disimpan di:")
print(output_csv)
print(output_excel)
print(output_json)

# TAMPILKAN HASIL
print("\n===== HASIL RUNTIME PER FUNCTION =====")

display_columns = [
    "nim",
    "module",
    "file_name",
    "function_name",
    "status",
    "runtime_seconds"
]

display(df[display_columns])

Hasil disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing2\runtime_per_function.csv
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing2\runtime_per_function.xlsx
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing2\runtime_per_function.json

===== HASIL RUNTIME PER FUNCTION =====

,nim,module,file_name,function_name,status,runtime_seconds
0,2241720092,root,Uts.py,NO_FUNCTION,NO FUNCTION,NaN
1,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P1_JS13.py,sigmoid,SUCCESS,3.233300e-06
2,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P1_JS13.py,sigmoid_derivative,SUCCESS,8.000000e-07
3,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P1_JS13.py,sigmoid,SUCCESS,2.066700e-06
4,2241720092,Artificial Neural Network (ANN) dan Evaluasi C...,P1_JS13.py,sigmoid_derivative,SUCCESS,7.667000e-07
...,...,...,...,...,...,...
555,2341720187,UAS,UAS.py,extract_hog_features,SUCCESS,2.166700e-06
556,2341720187,UAS,UAS.py,extract_lbp_features,SUCCESS,3.833300e-06
557,2341720187,UAS,UAS.py,extract_features,SUCCESS,6.733300e-06
558,2341720187,UAS,UAS.py,predict_and_show,SUCCESS,3.366700e-06
559,2341720187,UTS,UTS_2341720187_CANDRA_AHMAD_DANI.py,NO_FUNCTION,NO FUNCTION,NaN

In [ ]:
# RINGKASAN
print("\n===== RINGKASAN =====\n")

summary = {
    "Total function dianalisis": len(df),
    "SUCCESS": (df["status"] == "SUCCESS").sum(),
    "FAILED": (df["status"] == "FAILED").sum(),
    "TIMEOUT": (df["status"] == "TIMEOUT").sum(),
    "NO FUNCTION": (df["status"] == "NO FUNCTION").sum(),
    "SKIPPED": (df["status"] == "SKIPPED").sum(),
    "Rata-rata runtime": round(df["runtime_seconds"].mean(), 6)
}

summary_df = pd.DataFrame(list(summary.items()), columns=["Metric", "Value"])

display(summary_df)

print("\nTop 5 runtime terlama:\n")

top_runtime = (
    df.sort_values("runtime_seconds", ascending=False)
    [["nim", "module", "file_name", "function_name", "runtime_seconds"]]
    .head(5)
)

display(top_runtime)

===== RINGKASAN =====

                      Metric       Value
0  Total function dianalisis  560.000000
1                    SUCCESS  268.000000
2                     FAILED   53.000000
3                    TIMEOUT    0.000000
4                NO FUNCTION  237.000000
5                    SKIPPED    2.000000
6          Rata-rata runtime    0.000004

Top 5 runtime terlama:

,nim,module,file_name,function_name,runtime_seconds
496,2341720187,JS07,P5_JS07.py,run_faiss,0.000207
266,2341720096,JS11,P5_JS11.py,evaluate,0.000048
267,2341720096,JS11,P5_JS11.py,extract_avg_bright_feature,0.000030
379,2341720117,PBL_FastAPI,Salinan PBL_ML Regression Risk_V1.py,tampilkan_hasil,0.000016
512,2341720187,JS11,P5_JS11.py,load_dataset,0.000013