# import dan konfig awal

In [1]:
import os
import subprocess
import time
import shutil
import csv
from datetime import datetime
import stat

import ast
import json
import shutil
import builtins
import re
import pandas as pd

import cProfile
import pstats
import tempfile

from IPython.display import display

import timeit
import contextlib
import io
import threading

from tqdm.notebook import tqdm
import sys

from collections import defaultdict

In [2]:
# KONFIGURASI

input_file = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\asli\nim_github.txt"
projects_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github"
os.makedirs(projects_folder, exist_ok=True)

In [3]:
# output folder

log_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing"
os.makedirs(log_folder, exist_ok=True)

# Pengumpulan Data

## konfigurasi log proses clone

In [4]:
# konfigurasi output untuk proses clone
clone_excel = os.path.join(log_folder, "hasil_clone.xlsx")
clone_json = os.path.join(log_folder, "hasil_clone.json")
clone_csv = os.path.join(log_folder, "hasil_clone.csv")

In [6]:
# LOG CLONE
log_file = os.path.join(log_folder, "log_clone.csv")

# SETUP LOG

if not os.path.exists(log_file):
    with open(log_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["timestamp", "nim", "url", "status", "message"])


def write_log(nim, url, status, message):
    with open(log_file, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            nim,
            url,
            status,
            message
        ])

## Clone/Pengumpulan Data

In [7]:
# github token
GITHUB_TOKEN = "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"


def add_token(url):

    if url.startswith("https://github.com"):

        url = url.replace(
            "https://",
            f"https://{GITHUB_TOKEN}@"
        )

    return url

In [8]:
# BACA DATASET
# dataset berupa nim | url
def load_dataset(file_path):
    dataset = []

    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split("|")

            if len(parts) != 2:
                continue

            nim = parts[0].strip()
            url = parts[1].strip()

            dataset.append((nim, url))

    return dataset

In [9]:
# HANYA SIMPAN .py & .ipynb

def keep_only_code_files(repo_path):

    for root, dirs, files in os.walk(repo_path):

        # Jangan masuk folder .git
        if ".git" in dirs:
            dirs.remove(".git")

        for file in files:
            if not (file.endswith(".py") or file.endswith(".ipynb")):
                try:
                    os.remove(os.path.join(root, file))
                except:
                    pass

    # Hapus folder kosong
    for root, dirs, files in os.walk(repo_path, topdown=False):
        if not os.listdir(root):
            try:
                os.rmdir(root)
            except:
                pass

In [10]:
# HITUNG FILE KODE

def count_code_files(repo_path):

    py_count = 0
    ipynb_count = 0

    for root, dirs, files in os.walk(repo_path):

        if ".git" in dirs:
            dirs.remove(".git")

        for file in files:
            if file.endswith(".py"):
                py_count += 1
            elif file.endswith(".ipynb"):
                ipynb_count += 1

    return py_count, ipynb_count

In [11]:
# Remove folder gagal

def remove_readonly(func, path, exc_info):
    """
    Menghapus atribut read-only lalu retry delete.
    """
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except Exception as e:
        print(f"Gagal paksa hapus: {path}")
        print(f"->   Alasan: {str(e)}")

In [12]:
# menghitung modul atau folder di dalam repo

def count_modules(repo_path):

    modules = []

    for item in os.listdir(repo_path):
        full_path = os.path.join(repo_path, item)

        if os.path.isdir(full_path) and item != ".git":
            modules.append(item)

    return len(modules)

In [13]:
results = []

def clone_repo(repo_list):
    global success_count, fail_count, skip_count
    global total_py_files, total_ipynb_files

    success_count = fail_count = skip_count = 0
    total_py_files = total_ipynb_files = 0

    with tqdm(total=len(repo_list), desc="Cloning Repos", unit="repo") as pbar:
        for nim, url in repo_list:
            target_path = os.path.join(projects_folder, nim)

            def save(status, message, module=0, py=0, ipynb=0):
                results.append({
                    "nim": nim, 
                    "url": url, 
                    "status": status,
                    "message": message, 
                    "module": module,
                    "py_files": py, 
                    "ipynb_files": ipynb,
                    "total_files": py + ipynb
                })

            if not nim:
                pbar.write(f"[SKIP] URL tanpa NIM → {url}")
                write_log("", url, "SKIPPED", "NIM kosong")
                skip_count += 1
                save("SKIPPED", "NIM Kosong")
                pbar.update(1)
                continue

            if "/tree/" in url:
                url = url.split("/tree/")[0]

            if os.path.exists(target_path):
                pbar.write(f"[SKIP] {url} sudah diclone.")
                write_log(nim, url, "SKIPPED", "Folder sudah ada")
                skip_count += 1

                py, ipynb = count_code_files(target_path)
                module = count_modules(target_path)
                total_py_files += py
                total_ipynb_files += ipynb

                save("SKIPPED", "Folder sudah ada", module, py, ipynb)
                pbar.update(1)
                continue

            try:
                auth_url = add_token(url)
                subprocess.run(
                    ["git", "clone", "--depth", "1", auth_url, target_path],
                    check=True,
                    timeout=900,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.PIPE
                )

                keep_only_code_files(target_path)
                py, ipynb = count_code_files(target_path)
                module = count_modules(target_path)

                total_py_files += py
                total_ipynb_files += ipynb
                success_count += 1

                write_log(nim, url, "SUCCESS", f"Clone berhasil | module:{module} | py:{py} ipynb:{ipynb}")

                save("SUCCESS", "Clone berhasil", module, py, ipynb)

            except subprocess.CalledProcessError as e:
                error_msg = e.stderr.decode(errors="ignore")

                pbar.write(f"❌ Gagal clone {url} \n {error_msg}")
                write_log(nim, url, "FAILED", error_msg)

                if os.path.exists(target_path):
                    try:
                        shutil.rmtree(target_path, onerror=remove_readonly)
                        pbar.write("🧹 Folder clone dihapus\n------------------------")
                    except Exception as err:
                        pbar.write(f"⚠ Gagal hapus folder: {err}")

                fail_count += 1
                save("FAILED", error_msg)
                
            except subprocess.TimeoutExpired:
                pbar.write(f"❌ Gagal clone {url} \n Timeout Clone")
                write_log(nim, url, "FAILED", "Timeout")

                if os.path.exists(target_path):
                    try:
                        shutil.rmtree(target_path, onerror=remove_readonly)
                        pbar.write("🧹 Folder clone dihapus\n----------")
                    except Exception as err:
                        pbar.write(f"⚠ Gagal hapus folder: {err}")

                fail_count += 1
                save("FAILED", "Timeout Clone")

            finally:
                pbar.update(1)

In [14]:
dataset = load_dataset(input_file)
total_url = len(dataset)

success_count = 0
fail_count = 0
skip_count = 0

total_py_files = 0
total_ipynb_files = 0

print(f"\nTotal input URL: {total_url}\n")

# jalankan cloning
clone_repo(dataset)

repo_count = len([
    d for d in os.listdir(projects_folder)
    if os.path.isdir(os.path.join(projects_folder, d))
])

print("="*40)
print("HASIL CLONING")
print("="*40)
print(f"Total repo dalam dataset   : {repo_count}")
print(f"Berhasil clone    : {success_count}")
print(f"Gagal clone       : {fail_count}")
print(f"Skipped           : {skip_count}")
print(f"Total file .py    : {total_py_files}")
print(f"Total file .ipynb : {total_ipynb_files}")
print(f"Total file kode   : {total_py_files + total_ipynb_files}")

print("="*40)
print(f"Log tersimpan di: {log_file}")
print(f"Dataset tersimpan di: {projects_folder}")

Total input URL: 57

Cloning Repos:   0%|          | 0/57 [00:00<?, ?repo/s]

❌ Gagal clone https://github.com/fajrulsantoso/244107023010_ML_2025
 Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github\244107023010'...
error: invalid path 'JS08 /JS08'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


🧹 Folder clone dihapus
------------------------
❌ Gagal clone https://github.com/alfbrynn/2341720025_ML_2025
 Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github\2341720025'...
remote: Repository not found.
fatal: repository 'https://github.com/alfbrynn/2341720025_ML_2025/' not found

========================================
HASIL CLONING
========================================
Total repo dalam dataset   : 55
Berhasil clone    : 55
Gagal clone       : 2
Skipped           : 0
Total file .py    : 572
Total file .ipynb : 2822
Total file kode   : 3394
========================================
Log tersimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\log_clone.csv
Dataset tersimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github

In [15]:
# hasil clone
df = pd.DataFrame(results)

# simpan file hasil
df.to_excel(clone_excel, index=False)
df.to_csv(clone_csv, index=False)

with open(clone_json, "w", encoding="utf-8") as f:
    json.dump(results, f, indent=4)

print("\nFile hasil disimpan di:")
print(clone_excel)
print(clone_csv)
print(clone_json)

# TAMPILKAN TABEL
print("\n===== DATA HASIL CLONING =====\n")
display(df.head(10))

File hasil disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\hasil_clone.xlsx
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\hasil_clone.csv
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\hasil_clone.json

===== DATA HASIL CLONING =====

,nim,url,status,message,module,py_files,ipynb_files,total_files
0,2341720040,https://github.com/AlexanderDev2004/2341720040...,SUCCESS,Clone berhasil,15,5,50,55
1,2341720131,https://github.com/annisaeka123/2341720131_ML_...,SUCCESS,Clone berhasil,13,2,48,50
2,2341720070,https://github.com/annisakrnn/2341720070_ML_2025,SUCCESS,Clone berhasil,14,1,53,54
3,2341720153,https://github.com/AqsaHerryPrastyo/2341720153...,SUCCESS,Clone berhasil,12,0,52,52
4,2241720092,https://github.com/Katakon17/2241720092_ML_2025,SUCCESS,Clone berhasil,5,0,22,22
5,2341720187,https://github.com/4rdnac/2341720187_ML_2025,SUCCESS,Clone berhasil,15,1,51,52
6,2341720144,https://github.com/DanendraPassadhi/2341720144...,SUCCESS,Clone berhasil,15,1,54,55
7,2341720041,https://github.com/dedybayu/2341720041_ML_2025,SUCCESS,Clone berhasil,15,2,52,54
8,2341720111,https://github.com/ekyaaa/2341720111_ML_2025,SUCCESS,Clone berhasil,13,0,51,51
9,2341720218,https://github.com/faishal-ai/machine-learning...,SUCCESS,Clone berhasil,0,0,11,11

# normalisasi struktur direktori

In [5]:
normalized_folder = projects_folder + "_normalized"
os.makedirs(normalized_folder, exist_ok=True)

In [ ]:
# LOG NORMALISASI

normStruktur_excel = os.path.join(log_folder, "log_normalisasi.xlsx")

log_records = []

def write_log(nim, action, detail, status="SUCCESS", message=""):

    log_records.append({
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "nim": nim,
        "action": action,
        "detail": detail,
        "status": status,
        "message": message
    })

In [ ]:
# IDENTIFIKASI MODULE

def identify_module(text):

    text = text.upper()
    
    # PBL
    if "PBL" in text:
        return "pbl"

    # UTS
    if re.search(r"\bUTS\b|UJIAN\s*TENGAH\s*SEMESTER", text):
        return "uts"

    # UAS
    if re.search(r"\bUAS\b|UJIAN\s*AKHIR\s*SEMESTER", text):
        return "uas"
    
    # KUIS
    if re.search(r"KUIS|QUIZ", text):
        return "kuis"
    
    # KELOMPOK
    match = re.search(r"KELOMPOK|GROUP", text)
    if match:
        return "kelompok"
    
    # JS / JOBSHEET / PERTEMUAN
    match = re.search(r"(JS|JOBSHEET|PERTEMUAN|SESI|MODUL|MODULE|PRAKTIKUM)\s*0?(\d+)", text)
    if match:
        return f"js{int(match.group(2)):02d}"

    return None

In [ ]:
# IDENTIFIKASI FILE TYPE

def normalize_filename(file):

    name = file.upper()
    ext = os.path.splitext(file)[1].lower()
    
    # PBL
    if "PBL" in name:
        return f"pbl{ext}"
    
    # KELOMPOK
    if re.search(r"KELOMPOK|GROUP", name):
        return f"kelompok{ext}"

    # UTS
    if re.search(r"\bUTS\b|UJIAN\s*TENGAH\s*SEMESTER", name):
        return f"uts{ext}"

    # UAS
    if re.search(r"\bUAS\b|UJIAN\s*AKHIR\s*SEMESTER", name):
        return f"uas{ext}"
    
    # KUIS
    if re.search(r"KUIS|QUIZ", name):
        return f"kuis{ext}"

    # PRAKTIKUM
    match = re.search(r"\bP\s*0?(\d+)", name)
    if match:
        return f"p{int(match.group(1)):02d}{ext}"

    # TUGAS PRAKTIKUM
    if re.search(r"(TP|TG|TUGAS)", name):
        return f"tp{ext}"

    return None

In [ ]:
# HAPUS FOLDER YANG TIDAK PERLU

def remove_readonly(func, path, _):
    os.chmod(path, stat.S_IWRITE)
    func(path)
    
def remove_unnecessary(repo, remove_list, nim):

    for root, dirs, files in os.walk(repo):

        for d in dirs[:]:
            if d in remove_list:
                path = os.path.join(root, d)

                try:
                    shutil.rmtree(path, onerror=remove_readonly)
                    dirs.remove(d)
                    write_log(nim, "REMOVE_FOLDER", path)
                except Exception as e:
                    write_log(nim, "REMOVE_FOLDER", path, "FAILED", str(e))
                    tqdm.write(f"[ERROR] {nim} | REMOVE_FOLDER | {path} | {str(e)}")

In [ ]:
# CARI MODULE DARI PATH

def detect_module_from_path(root, file):

    module = None

    # cek semua folder dalam path
    for part in root.split(os.sep):

        module = identify_module(part)

        if module:
            return module

    # jika tidak ditemukan → cek dari file
    module = identify_module(file)

    return module

In [ ]:
# NORMALISASI REPOSITORY

def normalize_repository(repo_path):

    nim = os.path.basename(repo_path)
    normalized_repo = os.path.join(normalized_folder, nim)

    if os.path.exists(normalized_repo):
        shutil.rmtree(normalized_repo)
    
    os.makedirs(normalized_repo, exist_ok=True)

    remove_list = [".env", ".venv", "env", "venv", "__pycache__", ".git"]
    remove_unnecessary(normalized_repo, remove_list, nim)

    unclassified = os.path.join(normalized_repo, "unclassified")
    os.makedirs(unclassified, exist_ok=True)

    moved_files = []

    # scan semua file dulu
    for root, dirs, files in os.walk(repo_path):
        # jangan masuk ke folder .git dan venv
        dirs[:] = [d for d in dirs if d not in [".git", ".venv", "__pycache__", "env", "colab lama"]]
        for file in files:

            if not (file.endswith(".py") or file.endswith(".ipynb")):
                continue

            file_path = os.path.join(root, file)

            moved_files.append((root, file, file_path))


    # proses pemindahan
    for root, file, file_path in tqdm(
        moved_files,
        desc=f"{nim}",
        unit="file",
        leave=False,
        dynamic_ncols=True
    ):

        module = detect_module_from_path(root, file)

        if module:
            target_folder = os.path.join(normalized_repo, module)
        else:
            target_folder = unclassified

        os.makedirs(target_folder, exist_ok=True)

        new_name = normalize_filename(file)
        if new_name and new_name != file:
            write_log(nim, "RENAME_FILE", f"{file} -> {new_name}")

        if not new_name:
            new_name = file

        target_path = os.path.join(target_folder, new_name)

        # hindari overwrite
        counter = 1
        base, ext = os.path.splitext(new_name)

        while os.path.exists(target_path):
            counter += 1
            target_path = os.path.join(
                target_folder,
                f"{base}{counter}{ext}"
            )
            write_log(nim, "DUPLICATE_RENAME", f"{new_name} -> {base}{counter}{ext}")

        try:
            shutil.copy2(file_path, target_path)
            write_log(nim, "MOVE_FILE", f"{file_path} -> {target_path}")
        except Exception as e:
            write_log(nim, "MOVE_FILE", file_path, "FAILED", str(e))
            tqdm.write(f"[ERROR] {nim} | MOVE_FILE | {file_path} | {str(e)}")

In [ ]:
# =====================================================
# NORMALISASI DATASET
# =====================================================

print("\nMulai normalisasi dataset...\n")

total_repo = 0
repos = [
    r for r in os.listdir(projects_folder)
    if os.path.isdir(os.path.join(projects_folder, r))
]

for repo in tqdm(repos, desc="Normalizing Repositories", unit="repo"):
    repo_path = os.path.join(projects_folder, repo)
    try:
        normalize_repository(repo_path)
    except Exception as e:
        tqdm.write(f"[ERROR] Repository {repo} gagal diproses: {str(e)}")
        write_log(repo, "NORMALIZE_REPO", repo_path, "FAILED", str(e))
    total_repo += 1


print("\n===== NORMALISASI SELESAI =====")
print(f"Total repository : {total_repo}")


# ===============================
# SIMPAN LOG
# ===============================

df_log = pd.DataFrame(log_records)

df_log.to_excel(normStruktur_excel, index=False)

print("\nLog normalisasi disimpan di:")
print(normStruktur_excel)

print("="*35)
print("DATA LOG NORMALISASI")
print("-"*35)
display(df_log.head(10))

Mulai normalisasi dataset...

Normalizing Repositories:   0%|          | 0/55 [00:00<?, ?repo/s]

2241720092:   0%|          | 0/22 [00:00<?, ?file/s]

2341720003:   0%|          | 0/50 [00:00<?, ?file/s]

2341720005:   0%|          | 0/53 [00:00<?, ?file/s]

2341720007:   0%|          | 0/77 [00:00<?, ?file/s]

2341720009:   0%|          | 0/50 [00:00<?, ?file/s]

2341720011:   0%|          | 0/50 [00:00<?, ?file/s]

2341720017:   0%|          | 0/28 [00:00<?, ?file/s]

2341720028:   0%|          | 0/58 [00:00<?, ?file/s]

2341720032:   0%|          | 0/62 [00:00<?, ?file/s]

2341720035:   0%|          | 0/52 [00:00<?, ?file/s]

2341720040:   0%|          | 0/55 [00:00<?, ?file/s]

2341720041:   0%|          | 0/54 [00:00<?, ?file/s]

2341720047:   0%|          | 0/54 [00:00<?, ?file/s]

2341720057:   0%|          | 0/79 [00:00<?, ?file/s]

2341720062:   0%|          | 0/71 [00:00<?, ?file/s]

2341720070:   0%|          | 0/54 [00:00<?, ?file/s]

2341720072:   0%|          | 0/61 [00:00<?, ?file/s]

2341720081:   0%|          | 0/52 [00:00<?, ?file/s]

2341720083:   0%|          | 0/46 [00:00<?, ?file/s]

2341720084:   0%|          | 0/50 [00:00<?, ?file/s]

2341720088:   0%|          | 0/62 [00:00<?, ?file/s]

2341720093:   0%|          | 0/41 [00:00<?, ?file/s]

2341720095:   0%|          | 0/43 [00:00<?, ?file/s]

2341720096:   0%|          | 0/55 [00:00<?, ?file/s]

2341720108:   0%|          | 0/67 [00:00<?, ?file/s]

2341720109:   0%|          | 0/9 [00:00<?, ?file/s]

2341720111:   0%|          | 0/51 [00:00<?, ?file/s]

2341720112:   0%|          | 0/60 [00:00<?, ?file/s]

2341720117:   0%|          | 0/59 [00:00<?, ?file/s]

2341720131:   0%|          | 0/50 [00:00<?, ?file/s]

2341720135:   0%|          | 0/41 [00:00<?, ?file/s]

2341720143:   0%|          | 0/51 [00:00<?, ?file/s]

2341720144:   0%|          | 0/55 [00:00<?, ?file/s]

2341720147:   0%|          | 0/51 [00:00<?, ?file/s]

2341720153:   0%|          | 0/52 [00:00<?, ?file/s]

2341720157:   0%|          | 0/78 [00:00<?, ?file/s]

2341720158:   0%|          | 0/51 [00:00<?, ?file/s]

2341720160:   0%|          | 0/55 [00:00<?, ?file/s]

2341720162:   0%|          | 0/53 [00:00<?, ?file/s]

2341720163:   0%|          | 0/4 [00:00<?, ?file/s]

2341720164:   0%|          | 0/49 [00:00<?, ?file/s]

2341720168:   0%|          | 0/51 [00:00<?, ?file/s]

2341720174:   0%|          | 0/54 [00:00<?, ?file/s]

2341720176:   0%|          | 0/51 [00:00<?, ?file/s]

2341720187:   0%|          | 0/52 [00:00<?, ?file/s]

2341720191:   0%|          | 0/50 [00:00<?, ?file/s]

2341720200:   0%|          | 0/58 [00:00<?, ?file/s]

2341720217:   0%|          | 0/52 [00:00<?, ?file/s]

2341720218:   0%|          | 0/11 [00:00<?, ?file/s]

2341720227:   0%|          | 0/86 [00:00<?, ?file/s]

2341720234:   0%|          | 0/67 [00:00<?, ?file/s]

2341720248:   0%|          | 0/63 [00:00<?, ?file/s]

2341720250:   0%|          | 0/51 [00:00<?, ?file/s]

2341720251:   0%|          | 0/50 [00:00<?, ?file/s]

244107023008:   0%|          | 0/80 [00:00<?, ?file/s]

===== NORMALISASI SELESAI =====
Total repository : 55

Log normalisasi disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\log_normalisasi.xlsx
===================================
DATA LOG NORMALISASI
-----------------------------------

,timestamp,nim,action,detail,status,message
0,2026-03-23 10:02:32,2241720092,RENAME_FILE,Uts.ipynb -> uts.ipynb,SUCCESS,
1,2026-03-23 10:02:32,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
2,2026-03-23 10:02:32,2241720092,RENAME_FILE,P1_JS13.ipynb -> p01.ipynb,SUCCESS,
3,2026-03-23 10:02:32,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
4,2026-03-23 10:02:32,2241720092,RENAME_FILE,P2_JS13.ipynb -> p02.ipynb,SUCCESS,
5,2026-03-23 10:02:32,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
6,2026-03-23 10:02:32,2241720092,RENAME_FILE,P3_JS13.ipynb -> p03.ipynb,SUCCESS,
7,2026-03-23 10:02:32,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
8,2026-03-23 10:02:32,2241720092,RENAME_FILE,TP_JS13.ipynb -> tp.ipynb,SUCCESS,
9,2026-03-23 10:02:32,2241720092,MOVE_FILE,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,

# convert ke py

In [8]:
# konfigurasi folder hasil convert
converted_folder = normalized_folder + "_converted"
os.makedirs(converted_folder, exist_ok=True)

In [9]:
# ===============================
# LOG CONVERT NOTEBOOK
# ===============================

convert_excel = os.path.join(log_folder, "log_convert.xlsx")

convert_logs = []

def write_convert_log(nim, module, source, target, status, message=""):

    convert_logs.append({
        "NIM": nim,
        "module": module,
        "source_file": source,
        "target_file": target,
        "status": status,
        "message": message
    })

In [10]:
# menghapus magic command dari ipynb
def clean_magic_commands(code):

    # line magic
    code = re.sub(r"^\s*%.*$", "", code, flags=re.MULTILINE)
    # shell command
    code = re.sub(r"^\s*!.*$", "", code, flags=re.MULTILINE)
    # cell magic
    code = re.sub(r"^\s*%%.*$", "", code, flags=re.MULTILINE)

    return code

In [11]:
# ambil nim dan modul

def extract_nim_module(root_path, base_folder):

    rel_path = os.path.relpath(root_path, base_folder)
    parts = rel_path.split(os.sep)

    nim = ""
    module = ""

    if len(parts) >= 1:
        nim = parts[0]

    if len(parts) >= 2:
        module = parts[1]

    return nim, module

In [12]:
# KONVERSI NOTEBOOK

def convert_ipynb_to_py(ipynb_path, py_path):

    try:
        with open(ipynb_path, "r", encoding="utf-8") as f:
            notebook = json.load(f)

        code_cells = []

        for cell in notebook.get("cells", []):

            if cell.get("cell_type") != "code":
                continue

            source = "".join(cell.get("source", []))
            source = clean_magic_commands(source)

            code_cells.append(source)

        if not code_cells:
            return False, "Notebook tidak memiliki code cell"

        code = "\n\n".join(code_cells)

        with open(py_path, "w", encoding="utf-8") as f:
            f.write(code)

        return True, None

    except Exception as e:
        return False, str(e)

In [15]:
def count_files_extension(dataset_folder, extensions):

    result = {ext: 0 for ext in extensions}

    for root, dirs, files in os.walk(dataset_folder):

        # dirs[:] = [d for d in dirs if d not in [".git", "__pycache__", ".ipynb_checkpoints"]]

        for file in files:

            for ext in extensions:

                if file.lower().endswith(ext):
                    result[ext] += 1

    return result

In [ ]:
converted_success = 0
converted_failed = 0

# kumpulkan file
all_files = []
for root, dirs, files in os.walk(normalized_folder):
    for file in files:
        all_files.append((root, file))
total_files = len(all_files)

# progress bar
pbar = tqdm(
    all_files,
    total=total_files,
    desc="Converting Dataset",
    unit="file",
)

# loop untuk convert
for root, file in pbar:
    nim, module = extract_nim_module(root, normalized_folder)
    
    relative_path = os.path.relpath(root, normalized_folder)
    new_root = os.path.join(converted_folder, relative_path)
    os.makedirs(new_root, exist_ok=True)

    source_path = os.path.join(root, file)

    if file.endswith(".py"):
        target_path = os.path.join(new_root, file)
        try:
            shutil.copy2(source_path, target_path)

            write_convert_log(
                nim,
                module,
                source_path,
                target_path,
                "SUCCESS"
            )

        except Exception as e:

            converted_failed += 1

            write_convert_log(
                nim,
                module,
                source_path,
                target_path,
                "FAILED",
                str(e)
            )
            pbar.write(f"[ERROR] {source_path} | {str(e)}")

    elif file.endswith(".ipynb"):
        new_name = file.replace(".ipynb", ".py")
        target_path = os.path.join(new_root, new_name)

        success, error = convert_ipynb_to_py(source_path, target_path)

        if success:
            converted_success += 1
            write_convert_log(
                nim,
                module,
                source_path,
                target_path,
                "SUCCESS",
            )
        else:
            converted_failed += 1
            
            write_convert_log(
                nim,
                module,
                source_path,
                target_path,
                "FAILED",
                error
            )
            pbar.write(
                f"[ERROR] {source_path}\n"
                f"      Alasan: {error}"
            )

    # update info kecil di progress bar
    pbar.set_postfix_str(f"success={converted_success} fail={converted_failed}")

pbar.close()


# SIMPAN LOG
df_convert = pd.DataFrame(convert_logs)

df_convert.to_excel(convert_excel, index=False)

# RINGKASAN HASIL CONVERT =====
total_repo = len([
    d for d in os.listdir(converted_folder)
    if os.path.isdir(os.path.join(converted_folder, d))
])

counts_before = count_files_extension(normalized_folder, [".py",".ipynb"])
counts_after = count_files_extension(converted_folder, [".py"])

print("="*60)
print("HASIL KONVERSI DATASET")
print("-"*60)
print(f"Total Repository        : {total_repo}")
print("-"*20)
print(f"Total file .py awal     : {counts_before['.py']}")
print(f"Total file .ipynb awal  : {counts_before['.ipynb']}")
print(f"Total file awal         : {counts_before['.py'] + counts_before ['.ipynb']}")
print("-"*20)
print(f"Berhasil convert        : {converted_success}")
print(f"Gagal convert           : {converted_failed}")
print(f"Total file .py output   : {counts_after['.py']}")

print("="*60)
print("DATA LOG CONVERT")
print(f"\nDataset hasil convert tersimpan di: {converted_folder}")
display(df_convert.head(10))

Converting Dataset:   0%|          | 0/2891 [00:00<?, ?file/s]

[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720003\js07\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720003\js15\p02.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720005\js15\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720009\js15\tp.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720032\js15\p02.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720032\js15\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720041\js11\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720041\js15\p02.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720081\js15\p02.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720111\js15\p02.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720111\js15\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720112\js04\Kmeans.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720112\js15\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720112\unclassified\db_sportify.ipynb
      Alasan: 'utf-8' codec can't encode character '\udfaf' in position 49484: surrogates not allowed
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720144\js07\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720144\js15\p02.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720144\js15\tp.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720147\js06\p02.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720157\js15\p02.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720157\js15\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720162\js15\p02.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720162\js15\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720191\js15\tp.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720217\js01\p01.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720217\js07\tp.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720218\js05\JS05.ipynb
      Alasan: Expecting value: line 2 column 1 (char 1)
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\2341720251\js01\tp.ipynb
      Alasan: Notebook tidak memiliki code cell
[ERROR] D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized\244107023008\js15\p02.ipynb
      Alasan: Expecting value: line 1 column 1 (char 0)
============================================================
HASIL KONVERSI DATASET
------------------------------------------------------------
Total Repository        : 55
--------------------
Total file .py awal     : 81
Total file .ipynb awal  : 2810
--------------------
Berhasil convert        : 2782
Gagal convert           : 28
Total file .py output   : 2864
============================================================
DATA LOG CONVERT

Dataset hasil convert tersimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\kode_github_normalized_converted

,NIM,module,source_file,target_file,status,message
0,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
1,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
2,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
3,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
4,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
5,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
6,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
7,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
8,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
9,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,

# Waktu eksekusi

## seluruh project (CProfile)

In [17]:
# KONFIGURASI

# dataset_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\kode_github_py"
dataset_folder = converted_folder

output_csv = os.path.join(log_folder, "runtime_cprofile.csv")
output_excel = os.path.join(log_folder, "runtime_cprofile.xlsx")
output_json = os.path.join(log_folder, "runtime_cprofile.json")

TIMEOUT = 30
ITERATIONS = 3

In [18]:
# menghitung jumlah function per file
def count_functions_in_file(file_path):

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read())

        function_count = sum(
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            for node in ast.walk(tree)
        )

        return function_count

    except Exception:
        return None

In [19]:
# EKSTRAK METADATA

def extract_metadata(file_path, dataset_folder):

    # ambil path relatif dari dataset
    rel_path = os.path.relpath(file_path, dataset_folder)

    parts = rel_path.split(os.sep)

    # file name
    file_name = parts[-1]

    # nim = folder pertama
    nim = parts[0] if len(parts) >= 2 else "unknown"

    # module = folder setelah nim (jika ada)
    module = parts[1] if len(parts) >= 3 else "root"

    return nim, module, file_name

In [20]:
def run_with_cprofile(file_path):

    runtimes = []
    try:

        for i in range(ITERATIONS):
            with tempfile.NamedTemporaryFile(delete=False) as temp_prof:
                profile_file = temp_prof.name

            subprocess.run(
                ["python","-m","cProfile","-o",profile_file,file_path],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                timeout=TIMEOUT
            )

            stats = pstats.Stats(profile_file)
            runtimes.append(stats.total_tt)
            os.remove(profile_file)

        runtime = sum(runtimes) / len(runtimes)
        function_count = count_functions_in_file(file_path)

        return "SUCCESS", runtime, function_count, ""

    except subprocess.TimeoutExpired:
        return "TIMEOUT", None, None, "Execution timeout"

    except Exception as e:
        return "FAILED", None, None, str(e)

In [21]:
# LOOP PROFILING DATASET

py_files = []

for root, dirs, files in os.walk(dataset_folder):
    dirs[:] = [d for d in dirs if d not in [".git", "__pycache__"]]
    
    for file in files:
        if file.endswith(".py"):
            py_files.append(os.path.join(root, file))

total_files = len(py_files)

print("========== MULAI PROFILING ==========")

records = []

pbar = tqdm(
    py_files,
    total=total_files,
    desc="Profiling Python Files",
    unit="file"
)

success_count = 0
fail_count = 0
timeout_count = 0

for file_path in pbar:
    nim, module, file_name = extract_metadata(file_path, dataset_folder)
    status, runtime, function_count, message = run_with_cprofile(file_path)

    if status == "SUCCESS":
        success_count += 1
    elif status == "FAILED":
        fail_count += 1
    elif status == "TIMEOUT":
        timeout_count += 1
        
    records.append({
        "nim": nim,
        "module": module,
        "file_name": file_name,
        "function_count" : function_count,
        "status": status,
        "execution_time_seconds": runtime,
        "message": message
    })

    pbar.set_postfix({
        "success": success_count,
        "fail": fail_count,
        "timeout": timeout_count
    })

pbar.close()


# ===============================
# SIMPAN HASIL ANALISIS
# ===============================
df = pd.DataFrame(records)

df["execution_time_seconds"] = df["execution_time_seconds"].round(6)

# SIMPAN CSV
df.to_csv(output_csv, index=False)
df.to_excel(output_excel, index=False)

with open(output_json, "w", encoding="utf-8") as f:
    json.dump(records, f, indent=4)

# RINGKASAN
print("="*50)
print("RINGKASAN HASIL PROFILING")
print("-"*50)
print(f"Total File dianalisis       : {total_files}")
print(f"File Sukses dianalisis      : {(df['status'] == 'SUCCESS').sum()}")
print(f"File Gagal dianalisis       : {(df['status'] == 'FAILED').sum()}")
print(f"File Timeout                : {(df['status'] == 'TIMEOUT').sum()}")
print(f"Rata-rata runtime           : {round(df['execution_time_seconds'].mean(), 6)}")

# TAMPILKAN TABEL
print("\n========== TABEL HASIL RUNTIME ==========")
print("\nHasil lengkap disimpan di:")
print(output_csv)
print(output_excel)
print(output_json)
display(df.head(10))

========== MULAI PROFILING ==========

Profiling Python Files:   0%|          | 0/2864 [00:00<?, ?file/s]

==================================================
RINGKASAN HASIL PROFILING
--------------------------------------------------
Total File dianalisis       : 2864
File Sukses dianalisis      : 2811
File Gagal dianalisis       : 49
File Timeout                : 4
Rata-rata runtime           : 0.882665

========== TABEL HASIL RUNTIME ==========

Hasil lengkap disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\runtime_cprofile.csv
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\runtime_cprofile.xlsx
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\runtime_cprofile.json

,nim,module,file_name,function_count,status,execution_time_seconds,message
0,2241720092,js02,p01.py,0.0,SUCCESS,0.269183,
1,2241720092,js02,p02.py,0.0,SUCCESS,0.281524,
2,2241720092,js02,p03.py,0.0,SUCCESS,0.246230,
3,2241720092,js02,p04.py,0.0,SUCCESS,0.000909,
4,2241720092,js02,tp.py,0.0,SUCCESS,0.272196,
5,2241720092,js03,p01.py,0.0,SUCCESS,0.251680,
6,2241720092,js03,p02.py,0.0,SUCCESS,0.001280,
7,2241720092,js03,p03.py,0.0,SUCCESS,0.257711,
8,2241720092,js03,p04.py,0.0,SUCCESS,0.103572,
9,2241720092,js03,tp.py,0.0,SUCCESS,0.239057,

In [22]:
# TOP x RUNTIME

df_success = df[df["status"] == "SUCCESS"].copy()

print("\n========== 10 RUNTIME TERLAMA ==========\n")
top_slowest = (
    df_success.sort_values("execution_time_seconds", ascending=False)
    [["nim", "module", "file_name","function_count", "execution_time_seconds"]]
    .head(10)
)

display(top_slowest)

print("\n========== 10 RUNTIME TERCEPAT ==========\n")

top_fastest = (
    df_success
    .sort_values("execution_time_seconds", ascending=True)
    [["nim", "module", "file_name", "function_count", "execution_time_seconds"]]
    .head(10)
)

display(top_fastest)

print("-"*60)
df_success["execution_time_seconds"].describe()

========== 10 RUNTIME TERLAMA ==========

,nim,module,file_name,function_count,execution_time_seconds
2182,2341720174,js11,p03.py,1.0,367.173101
2449,2341720217,js13,p01.py,8.0,8.238274
287,2341720011,js13,p01.py,13.0,8.232512
2462,2341720218,js06,JS06.py,1.0,6.910212
2672,2341720248,js13,tp.py,8.0,6.360773
2515,2341720227,js13,JS13_Artificial_Neural_Network_(ANN)_dan_Evalu...,9.0,6.255354
2467,2341720218,js13,JS13.py,9.0,6.241862
2512,2341720227,js11,p04.py,1.0,5.211565
2641,2341720248,js05,tp.py,1.0,5.183967
2700,2341720250,js05,p01.py,1.0,5.178048

========== 10 RUNTIME TERCEPAT ==========

,nim,module,file_name,function_count,execution_time_seconds
1884,2341720158,js01,p01.py,0.0,0.000006
1809,2341720157,js01,tp.py,0.0,0.000006
1936,2341720160,js01,tp.py,0.0,0.000006
2145,2341720174,js01,tp.py,0.0,0.000006
1808,2341720157,js01,DEMO-PRAK-1.py,0.0,0.000006
1654,2341720144,js01,p01.py,0.0,0.000006
1443,2341720112,unclassified,db_sportify.py,0.0,0.000006
973,2341720083,js01,tp.py,0.0,0.000007
1131,2341720093,js01,JS01_2341720093_Tionusa.py,0.0,0.000007
1706,2341720147,js01,p01.py,0.0,0.000007

------------------------------------------------------------

count    2811.000000
mean        0.882665
std         6.996759
min         0.000006
25%         0.062120
50%         0.236469
75%         1.096692
max       367.173101
Name: execution_time_seconds, dtype: float64

## per function (timeit)

In [23]:
# KONFIGURASI
# dataset_folder = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\kode_github(10)_py"
dataset_folder = converted_folder

output_csv = os.path.join(log_folder, "runtime_per_function.csv")
output_excel = os.path.join(log_folder, "runtime_per_function.xlsx")
output_json = os.path.join(log_folder, "runtime_per_function.json")

RUN_REPEAT = 3
TIMEOUT = 30

In [24]:
# BLOK INPUT
builtins.input = lambda *args: "0"

In [25]:
# EKSTRAK METADATA

def extract_metadata(file_path, dataset_folder):
    # ambil path relatif dari dataset
    rel_path = os.path.relpath(file_path, dataset_folder)
    parts = rel_path.split(os.sep)

    # file name
    file_name = parts[-1]

    # nim = folder pertama
    nim = parts[0] if len(parts) >= 2 else "unknown"

    # module = folder setelah nim (jika ada)
    module = parts[1] if len(parts) >= 3 else "root"

    return nim, module, file_name

In [26]:
# EXTRACT FUNCTION DARI AST
def extract_functions(file_path):

    with open(file_path, "r", encoding="utf8", errors="ignore") as f:
        code = f.read()

    try:
        tree = ast.parse(code)
    except:
        return []

    functions = []

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):

            func_code = ast.get_source_segment(code, node)

            if func_code:
                functions.append((node.name, func_code))

    return functions

In [27]:
# GENERATE WRAPPER
def generate_wrapper(func_name, func_code):

    try:
        tree = ast.parse(func_code)
        func_node = tree.body[0]

        param_count = len(func_node.args.args)

        dummy_args = ",".join(["0"] * param_count)

    except:
        dummy_args = ""

    wrapper = f"""
{func_code}

def __wrapper():
    try:
        {func_name}({dummy_args})
    except:
        pass
"""

    return wrapper

In [28]:
# RUN DENGAN TIMEOUT 
def run_with_timeout(code):
    result = {"status": None, "runtime": None, "message": ""}

    def worker():
        original_stdout = sys.stdout
        try:
            local_env = {}
            dummy = io.StringIO()

            # override input agar tidak menunggu user
            local_env["input"] = lambda *args: "0"
            exec(code, local_env)

            with contextlib.redirect_stdout(dummy), contextlib.redirect_stderr(dummy):
                runtime = timeit.timeit(
                    "__wrapper()",
                    globals=local_env,
                    number=RUN_REPEAT
                )

            result["status"] = "SUCCESS"
            result["runtime"] = runtime / RUN_REPEAT

        except Exception as e:
            result["status"] = "FAILED"
            result["message"] = str(e)

    thread = threading.Thread(target=worker)

    thread.start()
    thread.join(TIMEOUT)

    if thread.is_alive():
        return "TIMEOUT", None, "Execution timeout"

    return result["status"], result["runtime"], result["message"]

In [29]:
records = []

print("\n" + "-"*50)
print(" ANALISIS RUNTIME per FUNCTION")

skip_funcs = ["main", "menu", "run", "start", "program", "main_menu"]

status_counter = defaultdict(int)

# Ambil semua file dulu (biar tqdm bisa hitung total)
all_py_files = []
for root, dirs, files in os.walk(dataset_folder):
    for file in files:
        if file.endswith(".py"):
            all_py_files.append(os.path.join(root, file))

# Progress bar untuk FILE
pbar_files = tqdm(
    all_py_files,
    desc="Processing Files",
    unit="file",
    dynamic_ncols=True
)

for file_path in pbar_files:

    nim, module, file_name = extract_metadata(file_path, dataset_folder)
    functions = extract_functions(file_path)

    if not functions:
        status_counter["NO FUNCTION"] += 1

        records.append({
            "nim": nim,
            "module": module,
            "file_name": file_name,
            "function_name": "NO_FUNCTION",
            "status": "NO FUNCTION",
            "runtime_seconds": None,
            "message": "No function detected"
        })
        continue

    # Progress bar untuk FUNCTION
    for func_name, func_code in functions:

        if func_name.lower() in skip_funcs:
            status_counter["SKIPPED"] += 1

            records.append({
                "nim": nim,
                "module": module,
                "file_name": file_name,
                "function_name": func_name,
                "status": "SKIPPED",
                "runtime_seconds": None,
                "message": "Skipped Function"
            })
            continue

        wrapper_code = generate_wrapper(func_name, func_code)
        status, runtime, message = run_with_timeout(wrapper_code)

        status_counter[status] += 1

        records.append({
            "nim": nim,
            "module": module,
            "file_name": file_name,
            "function_name": func_name,
            "status": status,
            "runtime_seconds": runtime,
            "message": message
        })
        
    pbar_files.set_postfix_str(
        f"success={status_counter['SUCCESS']} "    
        f"fail={status_counter['FAILED']} "
        f"timeout={status_counter['TIMEOUT']} "
        f"skip={status_counter['SKIPPED']}"
    )
pbar_files.close()

# SIMPAN DATA RUNTIME PER FUNCTION
df_runtimeFunct = pd.DataFrame(records)

df_runtimeFunct["runtime_seconds"] = pd.to_numeric(df_runtimeFunct["runtime_seconds"], errors="coerce")
# format runtime agar tidak scientific notation
df_runtimeFunct["runtime_seconds"] = df_runtimeFunct["runtime_seconds"].round(10)

df_runtimeFunct.to_csv(output_csv, index=False, float_format="%.10f")

with pd.ExcelWriter(output_excel, engine="xlsxwriter") as writer:

    df_runtimeFunct.to_excel(writer, index=False, sheet_name="runtimeFunction")
    workbook = writer.book
    worksheet = writer.sheets["runtimeFunction"]
    number_format = workbook.add_format({'num_format': '0.0000000000'})

    runtime_col = df_runtimeFunct.columns.get_loc("runtime_seconds")

    worksheet.set_column(runtime_col, runtime_col, 18, number_format)
    # auto width untuk kolom lain
    for i, col in enumerate(df_runtimeFunct.columns):

        max_len = max(
            df_runtimeFunct[col].astype(str).map(len).max(),
            len(col)
        ) + 2

        worksheet.set_column(i, i, max_len)

with open(output_json, "w", encoding="utf-8") as f:
    json.dump(records, f, indent=4, default=str)


# ===== SUMMARY =====
print("\n" + "="*50)
print("RINGKASAN ANALISIS RUNTIME PER FUNCTION")
print("-"*50)

total_repo = len([
    d for d in os.listdir(dataset_folder)
    if os.path.isdir(os.path.join(dataset_folder, d))
])

total_files = len(all_py_files)

total_no_function_files = (df_runtimeFunct["status"] == "NO FUNCTION").sum()

total_functions = df_runtimeFunct[df_runtimeFunct["function_name"] != "NO_FUNCTION"].shape[0]

success_func = (df_runtimeFunct["status"] == "SUCCESS").sum()
timeout_func = (df_runtimeFunct["status"] == "TIMEOUT").sum()
failed_func = (df_runtimeFunct["status"] == "FAILED").sum()
skipped_func = (df_runtimeFunct["status"] == "SKIPPED").sum()

print(f"Total Repository             : {total_repo}")
print(f"Total File Python            : {total_files}")
print(f"Total File tanpa Function    : {total_no_function_files}")
print(f"Total Function ditemukan     : {total_functions}")

print("---------------------------------\nStatus Function:")
print(f"- SUCCESS                    : {success_func}")
print(f"- TIMEOUT                    : {timeout_func}")
print(f"- FAILED                     : {failed_func}")
print(f"- SKIPPED                    : {skipped_func}")

print("="*50)

print("Hasil disimpan di:")
print(output_csv)
print(output_excel)
print(output_json)

display(df_runtimeFunct.head(20))

--------------------------------------------------
 ANALISIS RUNTIME per FUNCTION

Processing Files:   0%|          | 0/2864 [00:00<?, ?file/s]

==================================================
RINGKASAN ANALISIS RUNTIME PER FUNCTION
--------------------------------------------------
Total Repository             : 55
Total File Python            : 2864
Total File tanpa Function    : 1864
Total Function ditemukan     : 9007
---------------------------------
Status Function:
- SUCCESS                    : 8394
- TIMEOUT                    : 0
- FAILED                     : 599
- SKIPPED                    : 14
==================================================
Hasil disimpan di:
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\runtime_per_function.csv
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\runtime_per_function.xlsx
D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\OutputPreprocessing\runtime_per_function.json

,nim,module,file_name,function_name,status,runtime_seconds,message
0,2241720092,js02,p01.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
1,2241720092,js02,p02.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
2,2241720092,js02,p03.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
3,2241720092,js02,p04.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
4,2241720092,js02,tp.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
5,2241720092,js03,p01.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
6,2241720092,js03,p02.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
7,2241720092,js03,p03.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
8,2241720092,js03,p04.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
9,2241720092,js03,tp.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
10,2241720092,js04,p01.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
11,2241720092,js04,p02.py,find_clusters,SUCCESS,4.900000e-06,
12,2241720092,js04,p02.py,plot_pixels,SUCCESS,3.333300e-06,
13,2241720092,js04,p03.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
14,2241720092,js04,tp.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
15,2241720092,js13,p01.py,sigmoid,SUCCESS,2.466700e-06,
16,2241720092,js13,p01.py,sigmoid_derivative,SUCCESS,9.333000e-07,
17,2241720092,js13,p01.py,sigmoid,SUCCESS,2.500000e-06,
18,2241720092,js13,p01.py,sigmoid_derivative,SUCCESS,9.667000e-07,
19,2241720092,js13,p01.py,relu,SUCCESS,3.666700e-06,

In [30]:
print("\n========== 10 FUNCTION TERLAMA ==========\n")

top_slowest = (
    df_runtimeFunct[df_runtimeFunct["status"] == "SUCCESS"]
    .sort_values("runtime_seconds", ascending=False)
    [["nim", "module", "file_name", "function_name", "runtime_seconds"]]
    .head(10)
)

display(top_slowest)

print("\n========== 10 FUNCTION TERCEPAT ==========\n")

top_fastest = (
    df_runtimeFunct[df_runtimeFunct["status"] == "SUCCESS"]
    .sort_values("runtime_seconds", ascending=True)
    [["nim", "module", "file_name", "function_name", "runtime_seconds"]]
    .head(10)
)

display(top_fastest)

========== 10 FUNCTION TERLAMA ==========

,nim,module,file_name,function_name,runtime_seconds
7262,2341720174,js05,tp.py,simple_plot,0.728837
3947,2341720088,pbl,main.py,startup_event,0.001718
9946,2341720227,pbl,Notebook_PCVK_Patch_ML train-95_smooth-0.1.py,visualize_haralick_features,0.001480
7833,2341720200,pbl,Notebook_PCVK_Patch_ML train-40.py,visualize_haralick_features,0.001463
8885,2341720227,pbl,Notebook_PCVK_Patch_ML 21K-train-90.py,segment_u2netp,0.001447
9286,2341720227,pbl,Notebook_PCVK_Patch_ML train-40_smooth-0.1.py,visualize_haralick_features,0.001429
9820,2341720227,pbl,Notebook_PCVK_Patch_ML train-90_smooth-0.1.py,segment_u2netp,0.001414
7817,2341720200,pbl,Notebook_PCVK_Patch_ML train-40.py,segment_u2netp,0.001412
9930,2341720227,pbl,Notebook_PCVK_Patch_ML train-95_smooth-0.1.py,segment_u2netp,0.001404
9380,2341720227,pbl,Notebook_PCVK_Patch_ML train-50_smooth-0.1.py,segment_u2netp,0.001400

========== 10 FUNCTION TERCEPAT ==========

,nim,module,file_name,function_name,runtime_seconds
4821,2341720117,pbl,feature_builder.py,__init__,5.333000e-07
4410,2341720108,pbl,ANN_SPLIT_70_30.py,get_augmented_image,5.667000e-07
2734,2341720047,js13,p01.py,activation,5.667000e-07
3319,2341720062,pbl,SVM_SPLIT_90_10.py,get_augmented_image,5.667000e-07
3235,2341720062,pbl,SVM_SPLIT_20_80.py,get_augmented_image,5.667000e-07
3322,2341720062,pbl,SVM_SPLIT_90_10.py,get_augmented_image,5.667000e-07
3238,2341720062,pbl,SVM_SPLIT_20_80.py,get_augmented_image,5.667000e-07
4437,2341720108,pbl,SVM_SPLIT_10_90.py,get_augmented_image,5.667000e-07
3178,2341720062,pbl,ANN_SPLIT_50_50.py,get_augmented_image,6.000000e-07
3187,2341720062,pbl,ANN_SPLIT_60_40.py,get_augmented_image,6.000000e-07