# Preprocessing

## 1. Import Library

In [4]:
import os
import sys
import re
import csv
import ast
import json
import stat
import shutil
import time
import tokenize
import io
import threading
import contextlib
import tempfile
import subprocess
import builtins
import cProfile
import pstats
import timeit
from datetime import datetime
from collections import defaultdict

import pandas as pd
from tqdm.notebook import tqdm
from IPython.display import display

## 2. Konfigurasi

In [5]:
# DIRECTORY CONFIGURATION & INITIALIZATION
# Menentukan path utama, struktur folder dataset, dan file output
# ------------------------------------------------------------------------------

# 1. Root Path Setup & Input
BASE_DIR = r"D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code"
INPUT_GITHUB = os.path.join(BASE_DIR, "asli", "nim_github.txt")
DATASET_FOLDER = "dataset"

# 2. Directory Path
DIRS = {
    "DATASET": os.path.join(BASE_DIR, DATASET_FOLDER),
    "RAW": os.path.join(BASE_DIR, DATASET_FOLDER, "01_Raw"),
    "NORM": os.path.join(BASE_DIR, DATASET_FOLDER, "02_Normalized"),
    "CONV": os.path.join(BASE_DIR, DATASET_FOLDER, "03_Converted"),
    "CLEAN": os.path.join(BASE_DIR, DATASET_FOLDER, "04_Cleaned"),
    "BLACK": os.path.join(BASE_DIR, DATASET_FOLDER, "05a_Black"),
    "AUTOPEP8": os.path.join(BASE_DIR, DATASET_FOLDER, "05b_Autopep8"),
    "LOGS": os.path.join(BASE_DIR, "Output"),
}

# 3. Output file
RESULTS = {
    "CLONE_REPORT": os.path.join(DIRS["LOGS"], "01_clone_report.xlsx"),
    "NORM_REPORT": os.path.join(DIRS["LOGS"], "02_normalization_report.xlsx"),
    "CONV_REPORT": os.path.join(DIRS["LOGS"], "03_conversion_report.xlsx"),
    "CLEAN_REPORT": os.path.join(DIRS["LOGS"], "04_cleaning_report.xlsx"),
    "ERR_BLACK": os.path.join(DIRS["LOGS"], "05a_black_errors.json"),
    "ERR_AUTOPEP": os.path.join(DIRS["LOGS"], "05b_autopep_errors.json"),
    "RUN_PROJECT": os.path.join(DIRS["LOGS"], "07a_runtime_project_level.xlsx"),
    "RUN_FUNCTION": os.path.join(DIRS["LOGS"], "07b_runtime_function_level.xlsx"),
}

# 4. Execution
print("="*65)
print(f"{'KONFIGURASI':^65}")
print("-"*65)

folders_created = 0

if not os.path.isdir(BASE_DIR):
    raise FileNotFoundError(f"❌ BASE_DIR tidak ditemukan: {BASE_DIR}")

if not os.path.isfile(INPUT_GITHUB):
    raise FileNotFoundError(f"❌ File input tidak ditemukan: {INPUT_GITHUB}")

for name, path in DIRS.items():
    if not os.path.exists(path):
        os.makedirs(path, exist_ok=True)
        folders_created += 1
        print(f"[NEW] Folder {name.ljust(10)} created at: {path}")
    else:
        print(f"[EXISTS]  Folder {name.ljust(10)} : {path}")

print("-" * 65)
print(f"Project Root       : {BASE_DIR}")
print(f"Dataset            : {DIRS['DATASET']}")
print(f"Input File         : {INPUT_GITHUB}\n")
print(f"Folders Created    : {folders_created}")
print("="*65)

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

=================================================================
                           KONFIGURASI
-----------------------------------------------------------------
[EXISTS]  Folder DATASET    : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset
[EXISTS]  Folder RAW        : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\01_Raw
[EXISTS]  Folder NORM       : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\02_Normalized
[EXISTS]  Folder CONV       : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\03_Converted
[EXISTS]  Folder CLEAN      : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\04_Cleaned
[EXISTS]  Folder BLACK      : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\05a_Black
[EXISTS]  Folder AUTOPEP8   : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\05b_Autopep8
[EXISTS]  Folder LOGS       : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output
-----------------------------------------------------------------
Project Root       : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code
Dataset            : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset
Input File         : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\asli\nim_github.txt

Folders Created    : 0
=================================================================
Diproses pada 2026-04-07 22:13:01

In [6]:
# HELPER FUNCTION

def count_all_files(dataset_path, extensions=None, exclude_dirs=None):
    total_files = 0
    by_extension = {}

    exclude_dirs = set(exclude_dirs or [])

    for root, dirs, files in os.walk(dataset_path):
        # skip folder tertentu
        dirs[:] = [d for d in dirs if d not in exclude_dirs]

        for file in files:
            ext = os.path.splitext(file)[1].lower()

            # filter ekstensi jika diberikan
            if extensions and ext not in extensions:
                continue

            total_files += 1
            by_extension[ext] = by_extension.get(ext, 0) + 1

    return {
        "total_files": total_files,
        "by_extension": by_extension
    }

## 3. Pengumpulan Data (Cloning)

In [4]:
# HELPER FUNCTIONS (CLONING)
# Kumpulan fungsi bantu untuk proses cloning repository
# ------------------------------------------------------------------------------

# token github
GITHUB_TOKEN = "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"

# Fungsi untuk menyisipkan token GitHub ke dalam URL untuk autentikasi
def add_token(url):
    if url.startswith("https://github.com"):
        url = url.replace(
            "https://",
            f"https://{GITHUB_TOKEN}@"
        )
    return url

# Fungsi untuk membaca file dataset dengan format nim | url
def load_dataset(file_path):
    dataset = []
    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or "|" not in line:
                continue
            parts = line.split("|")
            nim = parts[0].strip()
            url = parts[1].strip()
            dataset.append((nim, url))
    return dataset

# Handler untuk menghapus file/folder yang bersifat read-only
def remove_readonly(func, path, exc_info):
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except Exception as e:
        print(f"    [WARNING] Gagal hapus : {path} \n       -> {str(e)}")

# Fungsi untuk menghapus semua file kecuali .py dan .ipynb, serta membersihkan folder kosong
def keep_only_code_files(repo_path):
    for root, dirs, files in os.walk(repo_path, topdown=True):
        # Jangan proses folder .git
        if ".git" in dirs:
            dirs.remove(".git")

        for file in files:
            if not (file.endswith(".py") or file.endswith(".ipynb")):
                try:
                    os.remove(os.path.join(root, file))
                except:
                    pass

    # Hapus folder yang menjadi kosong setelah pembersihan file (secara bottom-up)
    for root, dirs, files in os.walk(repo_path, topdown=False):
        if not os.listdir(root):
            try:
                os.rmdir(root)
            except:
                pass

# Fungsi untuk menghitung jumlah file .py dan .ipynb dalam sebuah direktori
def count_code_files(repo_path):
    py_count = sum(1 for root, _, files in os.walk(repo_path)
                for f in files if f.endswith(".py"))
    ipynb_count = sum(1 for root, _, files in os.walk(repo_path)
                    for f in files if f.endswith(".ipynb"))
    return py_count, ipynb_count

# Fungsi untuk menghitung jumlah folder (modul) di level utama repo
def count_modules(repo_path):
    try:
        return len([d for d in os.listdir(repo_path)
                    if os.path.isdir(os.path.join(repo_path, d)) and d != ".git"])
    except:
        return 0

In [6]:
# CLONING EXECUTION
# ------------------------------------------------------------------------------
results = []


def run_cloning_process(repo_list):
    global success_count, fail_count, skip_count
    global total_py_files, total_ipynb_files

    # Inisialisasi ulang counter
    success_count = fail_count = skip_count = 0
    total_py_files = total_ipynb_files = 0
    results.clear()

    with tqdm(total=len(repo_list), desc="Cloning Repos", unit="repo") as pbar:
        for nim, url in repo_list:
            target_path = os.path.join(DIRS['RAW'], nim)

            # Helper internal untuk menyimpan data hasil ke list
            def save_log(status, message, module=0, py=0, ipynb=0):
                results.append({
                    "nim": nim, "url": url, "status": status, "message": message,
                    "module": module, "py_files": py, "ipynb_files": ipynb, "total_files": py + ipynb
                })

            # Validasi jika NIM kosong
            if not nim:
                pbar.write(f"[SKIP] URL tanpa NIM → {url}")
                skip_count += 1
                save_log("SKIPPED", "NIM Kosong")
                pbar.update(1)
                continue

            # Menghapus suffix folder/branch jika ada di URL (misal: /tree/main)
            clean_url = url.split("/tree/")[0] if "/tree/" in url else url

            # Cek jika folder tujuan sudah ada (hindari clone ulang)
            if os.path.exists(target_path):
                pbar.write(f"[SKIP] {nim} sudah ada di direktori.")
                skip_count += 1
                py, ipynb = count_code_files(target_path)
                module = count_modules(target_path)
                total_py_files += py
                total_ipynb_files += ipynb
                save_log("SKIPPED", "Folder sudah ada", module, py, ipynb)
                pbar.update(1)
                continue

            try:
                # Proses clone menggunakan subprocess
                auth_url = add_token(clean_url)
                subprocess.run(
                    ["git", "clone", "--depth", "1", auth_url, target_path],
                    check=True, timeout=900, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE
                )

                # Pembersihan file non-kode
                keep_only_code_files(target_path)
                py, ipynb = count_code_files(target_path)
                module = count_modules(target_path)

                total_py_files += py
                total_ipynb_files += ipynb
                success_count += 1
                save_log("SUCCESS", "Clone berhasil", module, py, ipynb)

            except (subprocess.CalledProcessError) as e:
                error_msg = e.stderr.decode(errors="ignore")
                pbar.write(f"❌ Gagal clone {url} \n    -> {error_msg}")

                # Hapus folder jika terbentuk tapi gagal/error di tengah jalan
                if os.path.exists(target_path):
                    shutil.rmtree(target_path, onerror=remove_readonly)

                fail_count += 1
                save_log("FAILED", error_msg)

            except subprocess.TimeoutExpired:
                pbar.write(f"❌ Gagal clone {url} \n    -> Timeout Clone")

                if os.path.exists(target_path):
                    shutil.rmtree(target_path, onerror=remove_readonly)

                fail_count += 1
                save_log("FAILED", "Timeout Clone")

            finally:
                pbar.update(1)


# --- EKSEKUSI/RUN PROSES CLONE ---
print("="*60)
print(f"{'PROSES CLONING REPOSITORY':^60}")
print("-"*60)

dataset = load_dataset(INPUT_GITHUB)
print(f"Total input URL: {len(dataset)}\n")
run_cloning_process(dataset)
print(f"{' CLONING SELESAI':=^60}")

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
                 PROSES CLONING REPOSITORY
------------------------------------------------------------
Total input URL: 57

Cloning Repos:   0%|          | 0/57 [00:00<?, ?repo/s]

❌ Gagal clone https://github.com/fajrulsantoso/244107023010_ML_2025
    -> Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\01_Raw\244107023010'...
error: invalid path 'JS08 /JS08'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


❌ Gagal clone https://github.com/alfbrynn/2341720025_ML_2025
    -> Cloning into 'D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\01_Raw\2341720025'...
remote: Repository not found.
fatal: repository 'https://github.com/alfbrynn/2341720025_ML_2025/' not found

====================== CLONING SELESAI======================
Diproses pada 2026-04-07 09:23:18

In [7]:
# SUMMARY
# Menampilkan ringkasan hasil cloning
# ------------------------------------------------------------------------------

# Verifikasi jumlah folder fisik yang ada di direktori RAW
repo_in_dir = len([d for d in os.listdir(DIRS['RAW']) if os.path.isdir(os.path.join(DIRS['RAW'], d))])

print("="*60)
print(f"{'RINGKASAN PROSES CLONING':^60}")
print("-"*60)
print(f"Total Repo di Direktori : {repo_in_dir}")
print(f"Status Berhasil          : {success_count}")
print(f"Status Gagal             : {fail_count}")
print(f"Status Dilewati (Skip)   : {skip_count}")
print("-" * 60)
print(f"Total File Python (.py)     : {total_py_files}")
print(f"Total File Notebook (.ipynb): {total_ipynb_files}")
print(f"Total Keseluruhan File      : {count_all_files(DIRS['RAW'])['total_files']}")
print("-"*60)

# Membuat DataFrame dari list hasil
df_results = pd.DataFrame(results)

# Menyimpan laporan ke file Excel
df_results.to_excel(RESULTS['CLONE_REPORT'], index=False)
print(f"Laporan Clone disimpan di: {RESULTS['CLONE_REPORT']}")

# Menampilkan 10 baris pertama tabel hasil
print(f"{' RINGKASAN PROSES CLONING ':=^60}")
display(df_results.head(10))

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
                  RINGKASAN PROSES CLONING
------------------------------------------------------------
Total Repo di Direktori : 55
Status Berhasil          : 55
Status Gagal             : 2
Status Dilewati (Skip)   : 0
------------------------------------------------------------
Total File Python (.py)     : 572
Total File Notebook (.ipynb): 2822
Total Keseluruhan File      : 5017
------------------------------------------------------------
Laporan Clone disimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output\01_clone_report.xlsx
================= RINGKASAN PROSES CLONING =================

,nim,url,status,message,module,py_files,ipynb_files,total_files
0,2341720040,https://github.com/AlexanderDev2004/2341720040...,SUCCESS,Clone berhasil,15,5,50,55
1,2341720131,https://github.com/annisaeka123/2341720131_ML_...,SUCCESS,Clone berhasil,13,2,48,50
2,2341720070,https://github.com/annisakrnn/2341720070_ML_2025,SUCCESS,Clone berhasil,14,1,53,54
3,2341720153,https://github.com/AqsaHerryPrastyo/2341720153...,SUCCESS,Clone berhasil,12,0,52,52
4,2241720092,https://github.com/Katakon17/2241720092_ML_2025,SUCCESS,Clone berhasil,5,0,22,22
5,2341720187,https://github.com/4rdnac/2341720187_ML_2025,SUCCESS,Clone berhasil,15,1,51,52
6,2341720144,https://github.com/DanendraPassadhi/2341720144...,SUCCESS,Clone berhasil,15,1,54,55
7,2341720041,https://github.com/dedybayu/2341720041_ML_2025,SUCCESS,Clone berhasil,15,2,52,54
8,2341720111,https://github.com/ekyaaa/2341720111_ML_2025,SUCCESS,Clone berhasil,13,0,51,51
9,2341720218,https://github.com/faishal-ai/machine-learning...,SUCCESS,Clone berhasil,0,0,11,11

Diproses pada 2026-04-07 09:23:20

## 4. Normalisasi Struktur Direktori

In [8]:
# HELPER FUNCTIONS (NORMALIZATION)
# ------------------------------------------------------------------------------

# LOG SYSTEM
# Menyimpan seluruh aktivitas normalisasi
log_records = []
def write_log(nim, action, detail, status="SUCCESS", message=""):
    log_records.append({
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "nim": nim,
        "action": action,
        "detail": detail,
        "status": status,
        "message": message
    })

# IDENTIFIKASI MODULE DARI TEKS
# Fungsi untuk mendeteksi kategori modul dari nama folder/file.
# Hasil normalisasi folder akan menggunakan format standar:  pbl, uts, uas, kuis, kelompok, js01, js02, dst.
def identify_module(text):
    text = text.upper()

    if "PBL" in text:
        return "pbl"

    if re.search(r"\bUTS\b|UJIAN\s*TENGAH\s*SEMESTER", text):
        return "uts"

    if re.search(r"\bUAS\b|UJIAN\s*AKHIR\s*SEMESTER", text):
        return "uas"

    if re.search(r"KUIS|QUIZ", text):
        return "kuis"

    if re.search(r"KELOMPOK|GROUP", text):
        return "kelompok"

    # Mendeteksi jobsheet per pertemuan → format: js01, js02, dst.
    match = re.search(
        r"(JS|JOBSHEET|PERTEMUAN|SESI|MODUL|MODULE|PRAKTIKUM)\s*0?(\d+)", text)
    if match:
        return f"js{int(match.group(2)):02d}"

    return None  # Modul tidak terdeteksi

# NORMALISASI NAMA FILE
# Menyeragamkan nama file menjadi format standar berdasarkan jenisnya.
# Contoh: "Jobsheet 3.ipynb" → "p03.ipynb"
def normalize_filename(file):
    name = file.upper()
    ext = os.path.splitext(file)[1].lower()  # Pertahankan ekstensi asli

    if "PBL" in name:
        return f"pbl{ext}"

    if re.search(r"KELOMPOK|GROUP", name):
        return f"kelompok{ext}"

    if re.search(r"\bUTS\b|UJIAN\s*TENGAH\s*SEMESTER", name):
        return f"uts{ext}"

    if re.search(r"\bUAS\b|UJIAN\s*AKHIR\s*SEMESTER", name):
        return f"uas{ext}"

    if re.search(r"KUIS|QUIZ", name):
        return f"kuis{ext}"

    # Mendeteksi file praktikum (P1, P02, dst.) → format: p01, p02, dst.
    match = re.search(r"\bP\s*0?(\d+)", name)
    if match:
        return f"p{int(match.group(1)):02d}{ext}"

    # Mendeteksi file tugas praktikum (TP/TG/TUGAS)
    if re.search(r"(TP|TG|TUGAS)", name):
        return f"tp{ext}"

    return None  # Nama file tidak dikenali dan tidak perlu diubah

# PEMBERSIHAN FOLDER TIDAK PERLU
# Menghapus folder yang tidak diperlukan agar hasil dataset bersih.
# Contoh: .git, venv, __pycache__, dll.
def remove_readonly(func, path, _):  # bisa dijadikan func umum agar reusable
    os.chmod(path, stat.S_IWRITE)
    func(path)


# DETEKSI MODUL DARI PATH LENGKAP
# Menelusuri setiap segmen path (folder-folder induk) untuk mendeteksi modul.
# Jika tidak ditemukan dari path, fallback ke nama file.
def detect_module_from_path(root, file):
    # Telusuri setiap segmen folder dalam path
    for part in root.split(os.sep):
        module = identify_module(part)
        if module:
            return module

    # Fallback: coba deteksi langsung dari nama file
    return identify_module(file)

In [9]:
# CORE LOGIC: NORMALISASI REPOSITORY
# ------------------------------------------------------------------------------
def normalize_repository(repo_path):
    nim = os.path.basename(repo_path)
    target_repo_root = os.path.join(DIRS["NORM"], nim)
    
    removed_file = 0

    # reset target repo
    if os.path.exists(target_repo_root):
        shutil.rmtree(target_repo_root, onerror=remove_readonly)
    os.makedirs(target_repo_root, exist_ok=True)

    unclassified_dir = os.path.join(target_repo_root, "unclassified")
    os.makedirs(unclassified_dir, exist_ok=True)

    remove_list = {".env", ".venv", "env", "venv", "__pycache__", ".git", "colab lama", ".ipynb_checkpoints"}

    files_to_move = []

    # SCAN SOURCE REPOSITORY
    for root, dirs, files in os.walk(repo_path):
        # catat semua folder yang di-skip
        for d in dirs[:]:
            if d in remove_list:
                removed_path = os.path.join(root, d)
                removed_count = count_all_files(removed_path)["total_files"]
                removed_file += removed_count
                
                write_log(
                    nim,
                    "REMOVE_FOLDER",
                    removed_path,
                    "SUCCESS",
                    f"removed_files= {removed_count}"
                )

        # skip traversal folder noise
        dirs[:] = [d for d in dirs if d not in remove_list]

        # scan file
        for file in files:
            full_path = os.path.join(root, file)

            if file.endswith((".py", ".ipynb")):
                files_to_move.append((root, file, full_path))
            else:
                write_log(nim, "SKIP_NON_CODE", full_path)
                removed_file += 1

    # MOVE TO NORMALIZED
    for root, original_name, full_path in files_to_move:
        module = detect_module_from_path(root, original_name)

        target_subfolder = (
            os.path.join(target_repo_root, module)
            if module else unclassified_dir
        )
        os.makedirs(target_subfolder, exist_ok=True)

        new_name = normalize_filename(original_name) or original_name

        # log rename
        if new_name != original_name:
            write_log(
                nim,
                "RENAME_FILE",
                f"{original_name} -> {new_name}"
            )

        target_file_path = os.path.join(target_subfolder, new_name)

        # HANDLE DUPLICATE
        if os.path.exists(target_file_path):
            base, ext = os.path.splitext(new_name)
            counter = 2

            while os.path.exists(
                os.path.join(target_subfolder, f"{base}{counter}{ext}")
            ):
                counter += 1

            new_name = f"{base}{counter}{ext}"
            target_file_path = os.path.join(target_subfolder, new_name)

            write_log(
                nim,
                "DUPLICATE_HANDLE",
                f"Rename Duplicate: {original_name} -> {new_name}"
            )

        # COPY FILE
        try:
            shutil.copy2(full_path, target_file_path)
            write_log(nim, "MOVE_FILE", f"{original_name} -> {module or 'unclassified'}")

        except Exception as e:
            write_log(
                nim,
                "MOVE_FILE",
                original_name,
                "FAILED",
                str(e)
            )
    return removed_file

# ------------------------------------------------------------------------------
# EKSEKUSI: JALANKAN NORMALISASI SELURUH DATASET
# Memproses semua repository dalam direktori RAW secara berurutan.

print("="*60)
print(f"{' PROSES NORMALISASI DIREKTORI ' : ^60}")
print("-"*60)

# Ambil daftar semua subfolder (repository) dari direktori RAW
raw_repos = [
    r for r in os.listdir(DIRS['RAW']) 
    if os.path.isdir(os.path.join(DIRS['RAW'], r))
]

total_processed = 0
total_removed_files = 0
log_records = [] # Reset log sebelum eksekusi dimulai

for repo in tqdm(raw_repos, desc="Normalizing Repositories", unit="repo"):
    repo_path = os.path.join(DIRS['RAW'], repo)
    try:
        removed_file = normalize_repository(repo_path)
        total_removed_files += removed_file
        total_processed += 1
    except Exception as e:
        tqdm.write(f"[ERROR] Gagal proses {repo}: {str(e)}")
        write_log(repo, "NORMALIZE_REPO", "Global Error", "FAILED", str(e))

print(f"\n[SELESAI] Berhasil memproses {total_processed} repository.")
print("="*60)
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
                PROSES NORMALISASI DIREKTORI
------------------------------------------------------------

Normalizing Repositories:   0%|          | 0/55 [00:00<?, ?repo/s]

[SELESAI] Berhasil memproses 55 repository.
============================================================
Diproses pada 2026-04-07 09:29:23

In [10]:
# SUMMARY & REPORTING
# Mengekspor seluruh log ke file Excel dan menampilkan ringkasan hasil.
# ------------------------------------------------------------------------------
df_log = pd.DataFrame(log_records)
df_log.to_excel(RESULTS['NORM_REPORT'], index=False)

print("\n" + "=" * 60)
print(f"{' RINGKASAN HASIL NORMALISASI ':^60}")
print("-" * 60)
print(f"{'Total File Input':<30} : {count_all_files(DIRS['RAW'])['total_files']}")
print(f"{'Total File Setelah Normalisasi':<30} : {count_all_files(DIRS['NORM'])['total_files']}")
print(f"{'Total file excluded':<30} : {total_removed_files}")
print(f"{'Total Aksi Terdeteksi':<30} : {len(df_log)}")
print(f"{'Lokasi Penyimpanan':<30} : {DIRS['NORM']}")
print("-" * 60)

if not df_log.empty:
    action_counts = df_log["action"].value_counts()

    for action, count in action_counts.items():
        print(f"{action:<30} : {count}")

print("=" * 60)
display(df_log.head(10))

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
                RINGKASAN HASIL NORMALISASI
------------------------------------------------------------
Total File Input               : 5017
Total File Setelah Normalisasi : 2891
Total file excluded            : 2126
Total Aksi Terdeteksi          : 5561
Lokasi Penyimpanan             : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\02_Normalized
------------------------------------------------------------
MOVE_FILE                      : 2891
RENAME_FILE                    : 2516
DUPLICATE_HANDLE               : 97
REMOVE_FOLDER                  : 57
============================================================

,timestamp,nim,action,detail,status,message
0,2026-04-07 09:27:06,2241720092,REMOVE_FOLDER,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,removed_files= 29
1,2026-04-07 09:27:06,2241720092,RENAME_FILE,Uts.ipynb -> uts.ipynb,SUCCESS,
2,2026-04-07 09:27:07,2241720092,MOVE_FILE,Uts.ipynb -> uts,SUCCESS,
3,2026-04-07 09:27:07,2241720092,RENAME_FILE,P1_JS13.ipynb -> p01.ipynb,SUCCESS,
4,2026-04-07 09:27:07,2241720092,MOVE_FILE,P1_JS13.ipynb -> js13,SUCCESS,
5,2026-04-07 09:27:07,2241720092,RENAME_FILE,P2_JS13.ipynb -> p02.ipynb,SUCCESS,
6,2026-04-07 09:27:07,2241720092,MOVE_FILE,P2_JS13.ipynb -> js13,SUCCESS,
7,2026-04-07 09:27:07,2241720092,RENAME_FILE,P3_JS13.ipynb -> p03.ipynb,SUCCESS,
8,2026-04-07 09:27:07,2241720092,MOVE_FILE,P3_JS13.ipynb -> js13,SUCCESS,
9,2026-04-07 09:27:07,2241720092,RENAME_FILE,TP_JS13.ipynb -> tp.ipynb,SUCCESS,

Diproses pada 2026-04-07 09:29:26

## 5. Convert file ke .py

In [11]:
# HELPER FUNCTIONS (CONVERTING)
# ------------------------------------------------------------------------------

# LOG SYSTEM
# Menyimpan catatan hasil konversi setiap file
convert_logs = []
def write_convert_log(nim, module, source, target, status, message=""):
    convert_logs.append({
        "NIM": nim,
        "module": module,
        "source_file": source,
        "target_file": target,
        "status": status,
        "message": message
    })


# PEMBERSIHAN MAGIC COMMAND
# Menghapus sintaks khusus Jupyter (%, !, %%) yang tidak valid untuk kode Python
def clean_magic_commands(code):
    """
    Pola yang dihapus:
        %...   → line magic       (misal %matplotlib inline)
        !...   → shell command    (misal !pip install ...)
        %%...  → cell magic       (misal %%time)
    """
    code = re.sub(r"^\s*%.*$",  "", code, flags=re.MULTILINE)  # Line magic
    code = re.sub(r"^\s*!.*$",  "", code, flags=re.MULTILINE)  # Shell command
    code = re.sub(r"^\s*%%.*$", "", code, flags=re.MULTILINE)  # Cell magic
    return code


# MENGAMBIL NIM DAN NAMA MODUL
# Menguraikan path relatif untuk mendapatkan NIM dan nama modul
# berdasarkan struktur folder: <base_folder>/<nim>/<module>/
def extract_nim_module(root_path, base_folder):
    parts = os.path.relpath(root_path, base_folder).split(os.sep)

    nim = parts[0] if len(parts) >= 1 else ""
    module = parts[1] if len(parts) >= 2 else ""

    return nim, module


# KONVERSI NOTEBOOK KE PYTHON
def convert_ipynb_to_py(ipynb_path, py_path):
    """
    Mengkonversi file Jupyter Notebook (.ipynb) menjadi file Python (.py).
    Hanya code cell yang diekstrak; markdown dan output diabaikan.
    """
    try:
        with open(ipynb_path, "r", encoding="utf-8") as f:
            notebook = json.load(f)

        code_cells = []
        for cell in notebook.get("cells", []):

            if cell.get("cell_type") != "code":
                continue  # Lewati markdown cell dan raw cell

            source = "".join(cell.get("source", []))
            source = clean_magic_commands(source)
            code_cells.append(source)

        if not code_cells:
            return False, "Notebook tidak memiliki code cell"

        # Gabungkan semua code cell dengan pemisah baris kosong
        with open(py_path, "w", encoding="utf-8") as f:
            f.write("\n\n".join(code_cells))

        return True, None

    except Exception as e:
        return False, str(e)


# PENGHITUNG FILE BERDASARKAN EKSTENSI
# Digunakan untuk membandingkan jumlah file sebelum dan sesudah konversi.
def count_files_extension(dataset_folder, extensions):
    result = {ext: 0 for ext in extensions}

    for root, dirs, files in os.walk(dataset_folder):
        for file in files:
            for ext in extensions:
                if file.lower().endswith(ext):
                    result[ext] += 1

    return result

In [12]:
# EXECUTION: CONVERT DATASET
# ------------------------------------------------------------------------------

converted_success = 0
converted_failed = 0
convert_logs = []  # Reset log sebelum mulai

# Kumpulkan semua file dari folder hasil normalisasi
all_files = []
for root, dirs, files in os.walk(DIRS['NORM']):
    for file in files:
        all_files.append((root, file))

print("="*60)
print(f"{' MEMULAI KONVERSI KE .PY ':^60}")
print("-"*60)

pbar = tqdm(all_files, total=len(all_files), desc="Converting", unit="file")

# Looping untuk convert
for root, file in pbar:
    nim, module = extract_nim_module(root, DIRS['NORM'])

    # Siapkan folder tujuan di DIRS['CONV']
    relative_path = os.path.relpath(root, DIRS['NORM'])
    new_root = os.path.join(DIRS['CONV'], relative_path)
    os.makedirs(new_root, exist_ok=True)

    source_path = os.path.join(root, file)

    # 1. Jika file sudah .py, cukup copy saja
    if file.endswith(".py"):
        target_path = os.path.join(new_root, file)
        try:
            shutil.copy2(source_path, target_path)
            write_convert_log(nim, module, source_path, target_path, "SUCCESS")
        except Exception as e:
            converted_failed += 1
            write_convert_log(nim, module, source_path,
                              target_path, "FAILED", str(e))

    # 2. Jika file .ipynb, lakukan konversi
    elif file.endswith(".ipynb"):
        new_name = file.replace(".ipynb", ".py")
        target_path = os.path.join(new_root, new_name)

        success, error = convert_ipynb_to_py(source_path, target_path)
        if success:
            converted_success += 1
            write_convert_log(nim, module, source_path, target_path, "SUCCESS")
        else:
            converted_failed += 1
            write_convert_log(nim, module, source_path,
                              target_path, "FAILED", error)
            pbar.write(f"[ERROR] {nim} | {module} | {file} | {error}")

    pbar.set_postfix_str(
        f"success={converted_success} fail={converted_failed}")

pbar.close()
print(f"\n{' PROSES KONVERSI SELESAI ':=^60}")

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
                  MEMULAI KONVERSI KE .PY
------------------------------------------------------------

Converting:   0%|          | 0/2891 [00:00<?, ?file/s]

[ERROR] 2341720003 | js07 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720003 | js15 | p02.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720005 | js15 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720009 | js15 | tp.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720032 | js15 | p02.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720032 | js15 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720041 | js11 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720041 | js15 | p02.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720081 | js15 | p02.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720111 | js15 | p02.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720111 | js15 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720112 | js04 | Kmeans.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720112 | js15 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720112 | unclassified | db_sportify.ipynb | 'utf-8' codec can't encode character '\udfaf' in position 49484: surrogates not allowed
[ERROR] 2341720144 | js07 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720144 | js15 | p02.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720144 | js15 | tp.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720147 | js06 | p02.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720157 | js15 | p02.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720157 | js15 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720162 | js15 | p02.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720162 | js15 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 2341720191 | js15 | tp.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720217 | js01 | p01.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720217 | js07 | tp.ipynb | Expecting value: line 1 column 1 (char 0)
[ERROR] 2341720218 | js05 | JS05.ipynb | Expecting value: line 2 column 1 (char 1)
[ERROR] 2341720251 | js01 | tp.ipynb | Notebook tidak memiliki code cell
[ERROR] 244107023008 | js15 | p02.ipynb | Expecting value: line 1 column 1 (char 0)

================= PROSES KONVERSI SELESAI ==================
Diproses pada 2026-04-07 09:34:22

In [13]:
#  SUMMARY
# ------------------------------------------------------------------------------

# Simpan Log
df_convert = pd.DataFrame(convert_logs)
df_convert.to_excel(RESULTS['CONV_REPORT'], index=False)

# Hitung statistik untuk verifikasi
counts_before = count_files_extension(DIRS['NORM'], [".py", ".ipynb"])
counts_after = count_files_extension(DIRS['CONV'], [".py"])
total_repo = len([
    d for d in os.listdir(DIRS['CONV'])
    if os.path.isdir(os.path.join(DIRS['CONV'], d))
])

print("\n" + "="*60)
print(f"{' RINGKASAN KONVERSI ' : ^60}")
print("-"*60)
print(f"{'Total Repository':<30} : {total_repo}")
print("-" * 60)
print(f"{'File .py Awal':<30} : {counts_before['.py']}")
print(f"{'File .ipynb Awal':<30} : {counts_before['.ipynb']}")
print(
    f"{'Total File Sumber':<30} : {counts_before['.py'] + counts_before['.ipynb']}")
print("-" * 60)
print(f"{'Sukses Konversi (.ipynb)':<30} : {converted_success}")
print(f"{'Gagal Konversi':<30} : {converted_failed}")
print(f"{'Total File Akhir':<30} : {counts_after['.py']}")
print("="*60)
print(f"{'Dataset hasil convert tersimpan di':<30}: {DIRS['CONV']}")
print(f"\nLaporan disimpan di: {RESULTS['CONV_REPORT']}")
display(df_convert.head(10))

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
                     RINGKASAN KONVERSI
------------------------------------------------------------
Total Repository               : 55
------------------------------------------------------------
File .py Awal                  : 81
File .ipynb Awal               : 2810
Total File Sumber              : 2891
------------------------------------------------------------
Sukses Konversi (.ipynb)       : 2782
Gagal Konversi                 : 28
Total File Akhir               : 2864
============================================================
Dataset hasil convert tersimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\03_Converted

Laporan disimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output\03_conversion_report.xlsx

,NIM,module,source_file,target_file,status,message
0,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
1,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
2,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
3,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
4,2241720092,js02,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
5,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
6,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
7,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
8,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,
9,2241720092,js03,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\datas...,SUCCESS,

Diproses pada 2026-04-07 09:34:25

## 6. Data Cleaning

In [14]:
# HELPER FUNCTION (CLEANING)
# --------------------------------------------------------------------------------------------

# HAPUS KOMENTAR
# Tujuan: Menghapus semua komentar (#) dari file .py
# Metode: Tokenize → fallback manual jika gagal
def hapus_komentar_fallback(kode):
    lines_bersih = []
    removed = 0

    for line in kode.split('\n'):
        if '#' in line:
            in_string = False
            chars = list(line)

            for i, ch in enumerate(chars):
                if ch in ('"', "'") and (i == 0 or chars[i-1] != '\\'):
                    in_string = not in_string

                if ch == '#' and not in_string:
                    line = line[:i]
                    removed += 1
                    break

        lines_bersih.append(line.rstrip())

    return '\n'.join(lines_bersih), removed


def hapus_komentar(kode):
    try:
        tokens = tokenize.generate_tokens(io.StringIO(kode).readline)
        tokens_bersih = []
        removed = 0

        for t in tokens:
            if t.type == tokenize.COMMENT:
                removed += 1
            else:
                tokens_bersih.append(t)

        return tokenize.untokenize(tokens_bersih), 'TOKENIZE', removed

    except:
        kode_bersih, removed = hapus_komentar_fallback(kode)
        return kode_bersih, 'FALLBACK', removed


# HAPUS DOCSTRING
class DocstringRemover(ast.NodeTransformer):
    def _strip(self, node):
        if (
            node.body
            and isinstance(node.body[0], ast.Expr)
            and isinstance(node.body[0].value, ast.Constant)
            and isinstance(node.body[0].value.value, str)
        ):
            node.body.pop(0)

        if not node.body:
            node.body.append(ast.Pass())

        self.generic_visit(node)
        return node

    visit_Module = visit_FunctionDef = visit_AsyncFunctionDef = visit_ClassDef = _strip


def hapus_docstring_fallback(kode):
    lines = kode.split('\n')
    lines_bersih = []

    in_doc = False
    doc_char = None
    removed = 0

    for line in lines:
        if not in_doc:
            for q in ('"""', "'''"):
                idx = line.find(q)

                if idx != -1:
                    removed += 1
                    closing = line.find(q, idx + 3)

                    if closing != -1:
                        line = line[:idx] + line[closing + 3:]
                    else:
                        line = line[:idx]
                        in_doc = True
                        doc_char = q
                    break

            lines_bersih.append(line.rstrip())

        else:
            if doc_char in line:
                pos = line.find(doc_char)
                line = line[pos + 3:]
                in_doc = False
                doc_char = None

            lines_bersih.append(line.rstrip())

    return '\n'.join(lines_bersih), removed


def hapus_docstring(kode):
    try:
        removed = 0
        tree = ast.parse(kode)
        for node in ast.walk(tree):
            if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                if (
                    node.body
                    and isinstance(node.body[0], ast.Expr)
                    and isinstance(node.body[0].value, ast.Constant)
                    and isinstance(node.body[0].value.value, str)
                ):
                    removed += 1
        tree = DocstringRemover().visit(tree)
        ast.fix_missing_locations(tree)
        
        return ast.unparse(tree), 'AST', removed

    except:
        kode_bersih, removed = hapus_docstring_fallback(kode)
        return kode_bersih, 'FALLBACK', removed


# NORMALISASI WHITESPACE
def normalisasi_whitespace(kode):
    lines = kode.split('\n')
    lines_bersih = []

    for line in lines:
        stripped = line.rstrip()
        if stripped.strip() == '':
            continue

        lines_bersih.append(stripped)

    return '\n'.join(lines_bersih)

In [15]:
# EKSEKUSI CLEANING
# ---------------------------------------------------------------------

cleaning_logs = []

os.makedirs(DIRS['CLEAN'], exist_ok=True)

all_py_files = []
for root, dirs, files in os.walk(DIRS['CONV']):
    for fname in files:
        if fname.endswith('.py'):
            all_py_files.append((os.path.join(root, fname), root))

print(f"{' MULAI CLEANING CODE ':=^60}")

for source_path, root in tqdm(all_py_files, desc="Cleaning Process", unit="file"):
    rel_path = os.path.relpath(root, DIRS['CONV'])
    target_dir = os.path.join(DIRS['CLEAN'], rel_path)
    os.makedirs(target_dir, exist_ok=True)

    target_path = os.path.join(target_dir, os.path.basename(source_path))

    parts = rel_path.split(os.sep)
    nim = parts[0] if len(parts) >= 1 else "unknown"
    modul = parts[1] if len(parts) >= 2 else "root"

    try:
        with open(source_path, 'r', encoding='utf-8', errors='replace') as f:
            kode = f.read()

        loc_before = len(kode.split('\n'))
        # baseline whitespace sebelum cleaning
        blank_before = sum(
            1 for line in kode.split('\n')
            if line.strip() == ''
        )

        kode, m_komentar, komentar_removed = hapus_komentar(kode)
        kode, m_docstring, docstring_removed = hapus_docstring(kode)
        kode = normalisasi_whitespace(kode)

        loc_after = len(kode.split('\n'))
        
        # hitung whitespace setelah cleaning final
        blank_after = sum(
            1 for line in kode.split('\n')
            if line.strip() == ''
        )

        with open(target_path, 'w', encoding='utf-8') as f:
            f.write(kode)

        cleaning_logs.append({
            "nim": nim,
            "modul": modul,
            "file": os.path.basename(source_path),
            "method_komentar": m_komentar,
            "method_docstring": m_docstring,
            "status": "SUCCESS",
            "loc_before": loc_before,
            "loc_after": loc_after,
            "comment_removed": komentar_removed,
            "docstring_removed": docstring_removed,
            "blank_lines_removed": (blank_before - blank_after),
            "message": ""
        })

    except Exception as e:
        cleaning_logs.append({
            "nim": nim,
            "modul": modul,
            "file": os.path.basename(source_path),
            "status": "FAILED",
            "loc_before": 0,
            "loc_after": 0,
            "comment_removed": 0,
            "docstring_removed": 0,
            "blank_lines_removed": 0,
            "message": str(e)
        })

print(f"\n{' PROSES CLEANING SELESAI ':=^60}")

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

=================== MULAI CLEANING CODE ====================

Cleaning Process:   0%|          | 0/2864 [00:00<?, ?file/s]

================= PROSES CLEANING SELESAI ==================
Diproses pada 2026-04-07 09:39:12

In [16]:
# Simpan Log ke Excel khusus cleaning
df_clean = pd.DataFrame(cleaning_logs)
df_clean.to_excel(RESULTS['CLEAN_REPORT'], index=False)

print("\n" + "="*60)
print(f"{' RINGKASAN CLEANING DATA ' : ^60}")
print("-"*60)
print(f"{'Input File':<30} : {count_all_files(DIRS['CONV'])['total_files']}")
print(
    f"{'Total File Sukses':<30} : {len(df_clean[df_clean['status']=='SUCCESS']):<5}")
print(f"{'Dataset Clean':<30} : {DIRS['CLEAN']}")
print("-"*60)
print(f"{'File disimpan di':<30} : {RESULTS['CLEAN_REPORT']}")
display(df_clean.head(10))
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"\nDiproses pada {timestamp}")

============================================================
                  RINGKASAN CLEANING DATA
------------------------------------------------------------
Input File                     : 2864
Total File Sukses              : 2864
Dataset Clean                  : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\04_Cleaned
------------------------------------------------------------
File disimpan di               : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output\04_cleaning_report.xlsx

,nim,modul,file,method_komentar,method_docstring,status,loc_before,loc_after,comment_removed,docstring_removed,blank_lines_removed,message
0,2241720092,js02,p01.py,TOKENIZE,AST,SUCCESS,69,47,5,0,17,
1,2241720092,js02,p02.py,TOKENIZE,AST,SUCCESS,26,12,5,0,9,
2,2241720092,js02,p03.py,TOKENIZE,AST,SUCCESS,40,27,2,0,11,
3,2241720092,js02,p04.py,TOKENIZE,AST,SUCCESS,32,18,5,0,9,
4,2241720092,js02,tp.py,TOKENIZE,AST,SUCCESS,120,67,30,0,23,
5,2241720092,js03,p01.py,TOKENIZE,AST,SUCCESS,75,41,9,0,21,
6,2241720092,js03,p02.py,TOKENIZE,AST,SUCCESS,31,18,4,0,9,
7,2241720092,js03,p03.py,TOKENIZE,AST,SUCCESS,36,22,10,0,7,
8,2241720092,js03,p04.py,TOKENIZE,AST,SUCCESS,17,6,4,0,8,
9,2241720092,js03,tp.py,TOKENIZE,AST,SUCCESS,219,108,44,0,48,

Diproses pada 2026-04-07 09:39:13

## 7. Normalisasi Format Spasi (Black & Autopep8)

### Install Library Normalisasi

In [17]:
# ============================================================
# CELL 13 — Install Library Normalisasi
# Tujuan: Memastikan black dan autopep8 tersedia
# ============================================================

import subprocess, sys

norm_packages = ['black', 'autopep8', 'openpyxl']
for pkg in norm_packages:
    subprocess.run([sys.executable, '-m', 'pip', 'install', pkg, '-q'], check=True)

import black
import autopep8
import openpyxl

print('=' * 50)
print('✅ Library normalisasi berhasil diimport!')
print('  📌 black    —', black.__version__)
print('  📌 autopep8 —', autopep8.__version__)
print('  📌 openpyxl —', openpyxl.__version__)
print('=' * 50)

==================================================
✅ Library normalisasi berhasil diimport!
  📌 black    — 26.3.1
  📌 autopep8 — 2.3.2
  📌 openpyxl — 3.1.5
==================================================

### 7a. Normalisasi Format Spasi dengan Black

In [18]:
# ============================================================
# CELL 14 — Normalisasi Format Spasi dengan Black
# Tujuan: Memformat semua .py di converted_py menggunakan Black
# Output : dataset\normalized_black\
# File asli di converted_py TIDAK diubah
# ============================================================

import black
from pathlib import Path

# ── Folder output ────────────────────────────────────────────
# BLACK_DIR = os.path.join(DATASET_DIR, 'normalized_black')
# os.makedirs(BLACK_DIR, exist_ok=True)

# ── Konfigurasi Black ────────────────────────────────────────
BLACK_MODE = black.Mode(
    line_length=88,
    string_normalization=False,
    magic_trailing_comma=True,
)

# ── Kumpulkan semua .py dari converted_py ───────────────────
all_py = []
for nim in os.listdir(DIRS['CLEAN']):
    nim_path = os.path.join(DIRS['CLEAN'], nim)
    if not os.path.isdir(nim_path):
        continue
    for root, dirs, files in os.walk(nim_path):
        for fname in files:
            if fname.endswith('.py'):
                src = os.path.join(root, fname)
                rel = os.path.relpath(src, DIRS['CLEAN'])
                all_py.append((src, rel))

print('=' * 70)
print('🖤 Normalisasi dengan Black')
print(f'   Sumber     : {DIRS["CLEAN"]}')
print(f'   Output     : {DIRS["BLACK"]}')
print(f'   Line length: 88 karakter')
print(f'   Total file : {len(all_py)}')
print('=' * 70)

black_ok   = 0
black_fail = 0
black_fail_list = []

for src_path, rel_path in tqdm(all_py, desc='Black'):

    dst_path = os.path.join(DIRS['BLACK'], rel_path)
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)

    # Idempotent — skip jika sudah ada
    if os.path.exists(dst_path):
        black_ok += 1
        continue

    # Baca file sumber
    try:
        with open(src_path, 'r', encoding='utf-8', errors='replace') as f:
            original = f.read()
    except Exception as e:
        black_fail += 1
        black_fail_list.append({'file': rel_path, 'error': str(e)})
        continue

    # Format dengan Black
    try:
        formatted = black.format_str(original, mode=BLACK_MODE)
        with open(dst_path, 'w', encoding='utf-8') as f:
            f.write(formatted)
        black_ok += 1
    except Exception as e:
        # Syntax error — salin apa adanya agar file tetap ada
        with open(dst_path, 'w', encoding='utf-8') as f:
            f.write(original)
        black_fail += 1
        black_fail_list.append({'file': rel_path, 'error': str(e)})

# Simpan log gagal
if black_fail_list:
    # log_path = os.path.join(LOG_DIR, 'black_errors.json')
    with open(RESULTS['ERR_BLACK'], 'w', encoding='utf-8') as f:
        json.dump(black_fail_list, f, indent=2, ensure_ascii=False)
    print(f'\n⚠️  Log error disimpan di: {RESULTS["ERR_BLACK"]}')

print()
print('=' * 70)
print('📊 Hasil Normalisasi Black')
print('=' * 70)
print(f'  ✅ Berhasil diformat   : {black_ok}')
print(f'  ❌ Gagal (syntax error): {black_fail}')
print(f'  📂 Output              : {DIRS["BLACK"]}')
print('=' * 70)

======================================================================
🖤 Normalisasi dengan Black
   Sumber     : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\04_Cleaned
   Output     : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\05a_Black
   Line length: 88 karakter
   Total file : 2864
======================================================================

Black:   0%|          | 0/2864 [00:00<?, ?it/s]

⚠️  Log error disimpan di: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output\05a_black_errors.json

======================================================================
📊 Hasil Normalisasi Black
======================================================================
  ✅ Berhasil diformat   : 2816
  ❌ Gagal (syntax error): 48
  📂 Output              : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\05a_Black
======================================================================

### 7b. Normalisasi Format Spasi dengan Autopep8

In [19]:
# ============================================================
# CELL 15 — Normalisasi Format Spasi dengan Autopep8
# Tujuan: Memformat semua .py di converted_py menggunakan Autopep8
# Output : dataset\normalized_autopep8\
# File asli di converted_py TIDAK diubah
# ============================================================

import autopep8

# ── Folder output ────────────────────────────────────────────
# AUTOPEP_DIR = os.path.join(DATASET_DIR, 'normalized_autopep8')
# os.makedirs(AUTOPEP_DIR, exist_ok=True)

print('=' * 70)
print('🔵 Normalisasi dengan Autopep8')
print(f'   Sumber     : {DIRS["CLEAN"]}')
print(f'   Output     : {DIRS["AUTOPEP8"]}')
print(f'   Line length: 79 karakter (PEP8 standar)')
print(f'   Aggressive : level 1')
print(f'   Total file : {len(all_py)}')
print('=' * 70)

autopep_ok   = 0
autopep_fail = 0
autopep_fail_list = []

for src_path, rel_path in tqdm(all_py, desc='Autopep8'):

    dst_path = os.path.join(DIRS["AUTOPEP8"], rel_path)
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)

    # Idempotent — skip jika sudah ada
    if os.path.exists(dst_path):
        autopep_ok += 1
        continue

    # Baca file sumber
    try:
        with open(src_path, 'r', encoding='utf-8', errors='replace') as f:
            original = f.read()
    except Exception as e:
        autopep_fail += 1
        autopep_fail_list.append({'file': rel_path, 'error': str(e)})
        continue

    # Format dengan Autopep8
    try:
        formatted = autopep8.fix_code(
            original,
            options={
                'max_line_length': 79,
                'aggressive'     : 1,
            }
        )
        with open(dst_path, 'w', encoding='utf-8') as f:
            f.write(formatted)
        autopep_ok += 1
    except Exception as e:
        # Fallback — salin apa adanya
        with open(dst_path, 'w', encoding='utf-8') as f:
            f.write(original)
        autopep_fail += 1
        autopep_fail_list.append({'file': rel_path, 'error': str(e)})

# Simpan log gagal
if autopep_fail_list:
    # log_path = os.path.join(LOG_DIR, 'autopep8_errors.json')
    with open(RESULTS['ERR_AUTOPEP'], 'w', encoding='utf-8') as f:
        json.dump(autopep_fail_list, f, indent=2, ensure_ascii=False)
    print(f'\n⚠️  Log error disimpan di: {RESULTS["ERR_AUTOPEP"]}')

print()
print('=' * 70)
print('📊 Hasil Normalisasi Autopep8')
print('=' * 70)
print(f'  ✅ Berhasil diformat   : {autopep_ok}')
print(f'  ❌ Gagal               : {autopep_fail}')
print(f'  📂 Output              : {DIRS["AUTOPEP8"]}')
print('=' * 70)

======================================================================
🔵 Normalisasi dengan Autopep8
   Sumber     : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\04_Cleaned
   Output     : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\05b_Autopep8
   Line length: 79 karakter (PEP8 standar)
   Aggressive : level 1
   Total file : 2864
======================================================================

Autopep8:   0%|          | 0/2864 [00:00<?, ?it/s]

======================================================================
📊 Hasil Normalisasi Autopep8
======================================================================
  ✅ Berhasil diformat   : 2864
  ❌ Gagal               : 0
  📂 Output              : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\05b_Autopep8
======================================================================

### Analisis Diff Black vs Autopep8

In [20]:
# ============================================================
# CELL 16 — Analisis Diff Black vs Autopep8
# Tujuan: Menghitung perubahan per file untuk kedua formatter
#         Hasil disimpan ke df_report untuk diekspor di Cell 14
# ============================================================

import difflib

def count_changed_lines(original: str, formatted: str):
    """
    Hitung jumlah baris yang berubah antara original dan formatted.
    Return: (jumlah_baris_berubah, contoh_sebelum, contoh_sesudah)
    """
    orig_lines = original.splitlines()
    fmt_lines  = formatted.splitlines()
    changed    = 0
    ex_before  = ''
    ex_after   = ''

    matcher = difflib.SequenceMatcher(None, orig_lines, fmt_lines)
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag in ('replace', 'insert', 'delete'):
            changed += max(i2 - i1, j2 - j1)
            # Ambil 1 contoh baris replace yang paling representatif
            if not ex_before and tag == 'replace':
                for k in range(i1, i2):
                    if k < len(orig_lines) and orig_lines[k].strip():
                        ex_before = orig_lines[k][:80]
                        j_idx = j1 + (k - i1)
                        ex_after = fmt_lines[j_idx][:80] if j_idx < len(fmt_lines) else ''
                        break
    return changed, ex_before, ex_after

print('=' * 70)
print('🔍 Menganalisis diff per file...')
print(f'   Total file dianalisis: {len(all_py)}')
print('=' * 70)

records = []

for src_path, rel_path in tqdm(all_py, desc='Analisis diff'):
    nim       = rel_path.split(os.sep)[0]
    fname     = os.path.basename(rel_path)
    subfolder = os.path.dirname(rel_path.split(os.sep, 1)[-1]) if os.sep in rel_path else ''

    path_black = os.path.join(DIRS['BLACK'], rel_path)
    path_auto  = os.path.join(DIRS['AUTOPEP8'], rel_path)

    # ── Baca original ────────────────────────────────────────
    try:
        with open(src_path, 'r', encoding='utf-8', errors='replace') as f:
            orig = f.read()
        orig_lines = len(orig.splitlines())
    except Exception:
        orig = ''
        orig_lines = 0

    # ── Analisis Black ───────────────────────────────────────
    try:
        with open(path_black, 'r', encoding='utf-8', errors='replace') as f:
            blk = f.read()
        blk_lines            = len(blk.splitlines())
        blk_changed, beb, bea = count_changed_lines(orig, blk)
        blk_pct              = round(blk_changed / orig_lines * 100, 1) if orig_lines else 0
        blk_status           = 'Berubah' if blk_changed > 0 else 'Tidak Berubah'
    except Exception:
        blk_lines = blk_changed = blk_pct = 0
        beb = bea = ''
        blk_status = 'Gagal'

    # ── Analisis Autopep8 ────────────────────────────────────
    try:
        with open(path_auto, 'r', encoding='utf-8', errors='replace') as f:
            auto = f.read()
        auto_lines             = len(auto.splitlines())
        auto_changed, aeb, aea = count_changed_lines(orig, auto)
        auto_pct               = round(auto_changed / orig_lines * 100, 1) if orig_lines else 0
        auto_status            = 'Berubah' if auto_changed > 0 else 'Tidak Berubah'
    except Exception:
        auto_lines = auto_changed = auto_pct = 0
        aeb = aea = ''
        auto_status = 'Gagal'

    records.append({
        'NIM'                        : nim,
        'Subfolder'                  : subfolder,
        'Nama File'                  : fname,
        'Baris Original'             : orig_lines,
        'Black — Baris Hasil'        : blk_lines,
        'Black — Baris Berubah'      : blk_changed,
        'Black — % Perubahan'        : blk_pct,
        'Black — Status'             : blk_status,
        'Black — Contoh Sebelum'     : beb,
        'Black — Contoh Sesudah'     : bea,
        'Autopep8 — Baris Hasil'     : auto_lines,
        'Autopep8 — Baris Berubah'   : auto_changed,
        'Autopep8 — % Perubahan'     : auto_pct,
        'Autopep8 — Status'          : auto_status,
        'Autopep8 — Contoh Sebelum'  : aeb,
        'Autopep8 — Contoh Sesudah'  : aea,
    })

df_report = pd.DataFrame(records)

# Preview ringkasan
blk_b  = (df_report['Black — Status']    == 'Berubah').sum()
blk_u  = (df_report['Black — Status']    == 'Tidak Berubah').sum()
blk_f  = (df_report['Black — Status']    == 'Gagal').sum()
auto_b = (df_report['Autopep8 — Status'] == 'Berubah').sum()
auto_u = (df_report['Autopep8 — Status'] == 'Tidak Berubah').sum()
auto_f = (df_report['Autopep8 — Status'] == 'Gagal').sum()

print()
print('=' * 70)
print('📊 Ringkasan Hasil Analisis Diff')
print('=' * 70)
print(f'  {"Metrik":<30} {"Black":>10} {"Autopep8":>10}')
print(f'  {"-"*50}')
print(f'  {"File Berubah":<30} {blk_b:>10} {auto_b:>10}')
print(f'  {"File Tidak Berubah":<30} {blk_u:>10} {auto_u:>10}')
print(f'  {"File Gagal":<30} {blk_f:>10} {auto_f:>10}')
print(f'  {"Rata-rata % Perubahan":<30} '
      f'{df_report["Black — % Perubahan"].mean():>9.1f}% '
      f'{df_report["Autopep8 — % Perubahan"].mean():>9.1f}%')
print('=' * 70)
print(f'  ✅ df_report siap — {len(df_report)} baris. Lanjutkan ke Cell 14.')
print('=' * 70)

======================================================================
🔍 Menganalisis diff per file...
   Total file dianalisis: 2864
======================================================================

Analisis diff:   0%|          | 0/2864 [00:00<?, ?it/s]

======================================================================
📊 Ringkasan Hasil Analisis Diff
======================================================================
  Metrik                              Black   Autopep8
  --------------------------------------------------
  File Berubah                         2756       2510
  File Tidak Berubah                    108        354
  File Gagal                              0          0
  Rata-rata % Perubahan               41.4%      40.8%
======================================================================
  ✅ df_report siap — 2864 baris. Lanjutkan ke Cell 14.
======================================================================

### Export Laporan Perbandingan ke Excel

In [21]:
# ============================================================
# CELL 17 — Export Laporan Perbandingan ke Excel
# Tujuan: Menyimpan df_report ke .xlsx dengan 3 sheet:
#   Sheet 1 — Detail Per File
#   Sheet 2 — Ringkasan per NIM
#   Sheet 3 — Ringkasan Keseluruhan (Black vs Autopep8)
# Output : Skripsi_AST1\normalisasi_perbandingan.xlsx
# ============================================================

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

REPORT_PATH = os.path.join(DIRS['LOGS'], '05_normalisasi_perbandingan.xlsx')

# ── Palet warna ──────────────────────────────────────────────
C_HDR_BASE  = '2E7D32'   # hijau tua   — kolom info file
C_HDR_BLACK = '2C2C2C'   # hitam       — kolom Black
C_HDR_AUTO  = '1565C0'   # biru tua    — kolom Autopep8
C_ROW_EVEN  = 'F5F5F5'
C_ROW_ODD   = 'FFFFFF'
C_CHANGED   = 'FFF9C4'   # kuning muda — ada perubahan
C_UNCHANGED = 'E8F5E9'   # hijau muda  — tidak berubah
C_FAIL      = 'FFEBEE'   # merah muda  — gagal

GROUP_COLOR = {'base': C_HDR_BASE, 'black': C_HDR_BLACK, 'auto': C_HDR_AUTO}

def thin_border():
    s = Side(style='thin', color='CCCCCC')
    return Border(left=s, right=s, top=s, bottom=s)

STATUS_FILL = {
    'Berubah'      : PatternFill('solid', fgColor=C_CHANGED),
    'Tidak Berubah': PatternFill('solid', fgColor=C_UNCHANGED),
    'Gagal'        : PatternFill('solid', fgColor=C_FAIL),
}

wb = Workbook()

# ════════════════════════════════════════════════════════════
# SHEET 1 — Detail Per File
# ════════════════════════════════════════════════════════════
ws1 = wb.active
ws1.title = 'Detail Per File'

COLS_DETAIL = [
    ('NIM',                        16, 'base'),
    ('Subfolder',                  30, 'base'),
    ('Nama File',                  28, 'base'),
    ('Baris Original',             15, 'base'),
    ('Black — Baris Hasil',        18, 'black'),
    ('Black — Baris Berubah',      20, 'black'),
    ('Black — % Perubahan',        18, 'black'),
    ('Black — Status',             16, 'black'),
    ('Black — Contoh Sebelum',     45, 'black'),
    ('Black — Contoh Sesudah',     45, 'black'),
    ('Autopep8 — Baris Hasil',     20, 'auto'),
    ('Autopep8 — Baris Berubah',   22, 'auto'),
    ('Autopep8 — % Perubahan',     20, 'auto'),
    ('Autopep8 — Status',          18, 'auto'),
    ('Autopep8 — Contoh Sebelum',  45, 'auto'),
    ('Autopep8 — Contoh Sesudah',  45, 'auto'),
]

for ci, (label, width, grp) in enumerate(COLS_DETAIL, 1):
    c = ws1.cell(row=1, column=ci, value=label)
    c.font      = Font(name='Arial', bold=True, color='FFFFFF', size=10)
    c.fill      = PatternFill('solid', fgColor=GROUP_COLOR[grp])
    c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    c.border    = thin_border()
    ws1.column_dimensions[get_column_letter(ci)].width = width
ws1.row_dimensions[1].height = 32

for ri, rec in enumerate(records, 2):
    bg = PatternFill('solid', fgColor=(C_ROW_EVEN if ri % 2 == 0 else C_ROW_ODD))
    for ci, (label, _, _) in enumerate(COLS_DETAIL, 1):
        val  = rec.get(label, '')
        cell = ws1.cell(row=ri, column=ci, value=val)
        cell.font      = Font(name='Arial', size=9)
        cell.border    = thin_border()
        cell.alignment = Alignment(vertical='center')
        if 'Status' in label:
            cell.fill = STATUS_FILL.get(str(val), bg)
        elif '% Perubahan' in label:
            cell.fill          = bg
            cell.number_format = '0.0"%"'
        else:
            cell.fill = bg

ws1.freeze_panes = 'A2'
ws1.auto_filter.ref = ws1.dimensions

# ════════════════════════════════════════════════════════════
# SHEET 2 — Ringkasan per NIM
# ════════════════════════════════════════════════════════════
ws2 = wb.create_sheet('Ringkasan per NIM')

COLS_NIM = [
    ('NIM',                          16, 'base'),
    ('Total File',                   12, 'base'),
    ('Black — Berubah',              16, 'black'),
    ('Black — Tidak Berubah',        20, 'black'),
    ('Black — Gagal',                14, 'black'),
    ('Black — Rata-rata % Ubah',     22, 'black'),
    ('Autopep8 — Berubah',           18, 'auto'),
    ('Autopep8 — Tidak Berubah',     22, 'auto'),
    ('Autopep8 — Gagal',             16, 'auto'),
    ('Autopep8 — Rata-rata % Ubah',  24, 'auto'),
]

for ci, (label, width, grp) in enumerate(COLS_NIM, 1):
    c = ws2.cell(row=1, column=ci, value=label)
    c.font      = Font(name='Arial', bold=True, color='FFFFFF', size=10)
    c.fill      = PatternFill('solid', fgColor=GROUP_COLOR[grp])
    c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    c.border    = thin_border()
    ws2.column_dimensions[get_column_letter(ci)].width = width
ws2.row_dimensions[1].height = 35

for ri, (nim, grp) in enumerate(df_report.groupby('NIM'), 2):
    bg = PatternFill('solid', fgColor=(C_ROW_EVEN if ri % 2 == 0 else C_ROW_ODD))
    row_vals = [
        nim,
        len(grp),
        (grp['Black — Status']    == 'Berubah').sum(),
        (grp['Black — Status']    == 'Tidak Berubah').sum(),
        (grp['Black — Status']    == 'Gagal').sum(),
        round(grp['Black — % Perubahan'].mean(), 1),
        (grp['Autopep8 — Status'] == 'Berubah').sum(),
        (grp['Autopep8 — Status'] == 'Tidak Berubah').sum(),
        (grp['Autopep8 — Status'] == 'Gagal').sum(),
        round(grp['Autopep8 — % Perubahan'].mean(), 1),
    ]
    for ci, val in enumerate(row_vals, 1):
        cell = ws2.cell(row=ri, column=ci, value=val)
        cell.font      = Font(name='Arial', size=9)
        cell.fill      = bg
        cell.border    = thin_border()
        cell.alignment = Alignment(horizontal='center', vertical='center')
        if ci in (6, 10):
            cell.number_format = '0.0"%"'

ws2.freeze_panes = 'A2'
ws2.auto_filter.ref = ws2.dimensions

# ════════════════════════════════════════════════════════════
# SHEET 3 — Ringkasan Keseluruhan
# ════════════════════════════════════════════════════════════
ws3 = wb.create_sheet('Ringkasan Keseluruhan')

total_files = len(df_report)
blk_b    = (df_report['Black — Status']    == 'Berubah').sum()
blk_u    = (df_report['Black — Status']    == 'Tidak Berubah').sum()
blk_f    = (df_report['Black — Status']    == 'Gagal').sum()
blk_avg  = round(df_report['Black — % Perubahan'].mean(), 1)
auto_b   = (df_report['Autopep8 — Status'] == 'Berubah').sum()
auto_u   = (df_report['Autopep8 — Status'] == 'Tidak Berubah').sum()
auto_f   = (df_report['Autopep8 — Status'] == 'Gagal').sum()
auto_avg = round(df_report['Autopep8 — % Perubahan'].mean(), 1)

summary_rows = [
    ['METRIK',                        'BLACK',       'AUTOPEP8'     ],
    ['Total File Diproses',            total_files,   total_files    ],
    ['File Berubah',                   blk_b,         auto_b         ],
    ['File Tidak Berubah',             blk_u,         auto_u         ],
    ['File Gagal (syntax error)',      blk_f,         auto_f         ],
    ['Rata-rata % Perubahan',          blk_avg,       auto_avg       ],
    ['',                               '',            ''             ],
    ['KONFIGURASI',                    'BLACK',       'AUTOPEP8'     ],
    ['Line Length Target',             '88 karakter', '79 karakter'  ],
    ['Normalisasi Tanda Kutip String', 'Tidak',       'Tidak'        ],
    ['Perbaiki Indentasi',             'Ya',          'Ya'           ],
    ['Perbaiki Spasi Operator',        'Ya',          'Ya'           ],
    ['Perbaiki Blank Lines',           'Ya',          'Sebagian'     ],
    ['Toleransi Syntax Error',         'Tidak',       'Ya (dilewati)'],
    ['Aggressive Mode',                'Tidak ada',   'Level 1'      ],
]

HDR_ROWS = {1, 8}  # baris yang menjadi header (nomor baris di sheet)

for ri, row in enumerate(summary_rows, 1):
    for ci, val in enumerate(row, 1):
        cell = ws3.cell(row=ri, column=ci, value=val)
        cell.border    = thin_border()
        cell.alignment = Alignment(horizontal='center', vertical='center')
        if ri in HDR_ROWS:
            colors = {1: '2E7D32', 2: C_HDR_BLACK, 3: C_HDR_AUTO}
            cell.font = Font(name='Arial', bold=True, color='FFFFFF', size=11)
            cell.fill = PatternFill('solid', fgColor=colors.get(ci, '333333'))
            ws3.row_dimensions[ri].height = 28
        elif row[0] == '':
            pass  # baris pemisah
        else:
            bg = C_ROW_EVEN if ri % 2 == 0 else C_ROW_ODD
            cell.font = Font(name='Arial', size=10, bold=(ci == 1))
            cell.fill = PatternFill('solid', fgColor=bg)

ws3.column_dimensions['A'].width = 32
ws3.column_dimensions['B'].width = 20
ws3.column_dimensions['C'].width = 20

# ── Simpan file ──────────────────────────────────────────────
wb.save(REPORT_PATH)

print()
print('=' * 70)
print('✅ Laporan Excel berhasil disimpan!')
print(f'   📊 {REPORT_PATH}')
print()
print(f'   📋 Sheet 1 — Detail Per File       : {total_files} baris')
print(f'   📋 Sheet 2 — Ringkasan per NIM     : {df_report["NIM"].nunique()} baris')
print(f'   📋 Sheet 3 — Ringkasan Keseluruhan')
print()
print('  ┌──────────────────────────────┬──────────┬──────────┐')
print('  │ Metrik                       │  Black   │ Autopep8 │')
print('  ├──────────────────────────────┼──────────┼──────────┤')
print(f'  │ File Berubah                 │ {blk_b:>8} │ {auto_b:>8} │')
print(f'  │ File Tidak Berubah           │ {blk_u:>8} │ {auto_u:>8} │')
print(f'  │ File Gagal                   │ {blk_f:>8} │ {auto_f:>8} │')
print(f'  │ Rata-rata % Perubahan        │ {blk_avg:>7}% │ {auto_avg:>7}% │')
print('  └──────────────────────────────┴──────────┴──────────┘')
print('=' * 70)

======================================================================
✅ Laporan Excel berhasil disimpan!
   📊 D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output\05_normalisasi_perbandingan.xlsx

   📋 Sheet 1 — Detail Per File       : 2864 baris
   📋 Sheet 2 — Ringkasan per NIM     : 55 baris
   📋 Sheet 3 — Ringkasan Keseluruhan

  ┌──────────────────────────────┬──────────┬──────────┐
  │ Metrik                       │  Black   │ Autopep8 │
  ├──────────────────────────────┼──────────┼──────────┤
  │ File Berubah                 │     2756 │     2510 │
  │ File Tidak Berubah           │      108 │      354 │
  │ File Gagal                   │        0 │        0 │
  │ Rata-rata % Perubahan        │    41.4% │    40.8% │
  └──────────────────────────────┴──────────┴──────────┘
======================================================================

## 8. Hitung Jumlah Baris Kode per Project

In [22]:
# ============================================================
# CELL 18 — Hitung Jumlah Baris Kode per Project
# Tujuan: Menghitung komposisi tipe baris per file & per NIM:
#   - total_lines    : total baris mentah
#   - code_lines     : baris berisi kode aktif
#   - comment_lines  : baris komentar murni (#)
#   - blank_lines    : baris kosong
#   - docstring_lines: baris di dalam docstring
#
# Catatan: dijalankan SETELAH Cell 10/11/12 (hapus komentar,
#          docstring, whitespace) sehingga hasilnya mencerminkan
#          kode yang sudah bersih.
# ============================================================

print('=' * 75)
print('📏 CELL 13 — Hitung Jumlah Baris per Project')
print(f'   Sumber: {DIRS["BLACK"]}')
print('=' * 75)

# ── Fungsi hitung tipe baris ─────────────────────────────────
def hitung_tipe_baris(kode: str) -> dict:
    """
    Hitung baris berdasarkan tipe dari teks kode Python.
    Return dict dengan key:
      total_lines, code_lines, comment_lines,
      blank_lines, docstring_lines
    """
    counts = {
        'total_lines'    : 0,
        'code_lines'     : 0,
        'comment_lines'  : 0,
        'blank_lines'    : 0,
        'docstring_lines': 0,
    }

    lines = kode.splitlines()
    counts['total_lines'] = len(lines)

    in_docstring   = False
    docstring_char = ''

    for line in lines:
        stripped = line.strip()

        # ── Deteksi docstring ──────────────────────────────
        if not in_docstring:
            found_doc = False
            for q in ('"""', "'''"):
                if q in stripped:
                    in_docstring   = True
                    docstring_char = q
                    counts['docstring_lines'] += 1
                    # Tutup di baris yang sama (inline docstring)
                    rest = stripped.replace(q, '', 1)
                    if q in rest:
                        in_docstring = False
                    found_doc = True
                    break
            if found_doc:
                continue

        elif in_docstring:
            counts['docstring_lines'] += 1
            if docstring_char in stripped:
                in_docstring = False
            continue

        # ── Tipe baris biasa ───────────────────────────────
        if not stripped:
            counts['blank_lines'] += 1
        elif stripped.startswith('#'):
            counts['comment_lines'] += 1
        else:
            counts['code_lines'] += 1

    return counts


# ── Kumpulkan semua .py ──────────────────────────────────────
file_records = []

for nim in sorted(os.listdir(DIRS["BLACK"])):
    nim_path = os.path.join(DIRS["BLACK"], nim)
    if not os.path.isdir(nim_path):
        continue

    for root, dirs, files in os.walk(nim_path):
        for fname in sorted(files):
            if not fname.endswith('.py'):
                continue

            full_path = os.path.join(root, fname)
            rel_path  = os.path.relpath(full_path, DIRS["BLACK"])
            parts     = rel_path.split(os.sep)

            # Tentukan NIM dan jobsheet dari path
            nim_val  = parts[0]
            jobsheet = parts[1] if len(parts) > 2 else '(root)'
            file_val = parts[-1]

            try:
                with open(full_path, 'r', encoding='utf-8', errors='replace') as f:
                    kode = f.read()
                size_bytes = os.path.getsize(full_path)
                counts     = hitung_tipe_baris(kode)
                status     = 'OK'
            except Exception as e:
                counts     = {
                    'total_lines': 0, 'code_lines': 0,
                    'comment_lines': 0, 'blank_lines': 0,
                    'docstring_lines': 0
                }
                size_bytes = 0
                status     = f'ERROR: {str(e)[:40]}'

            file_records.append({
                'NIM'            : nim_val,
                'Jobsheet'       : jobsheet,
                'Nama File'      : file_val,
                'Path Relatif'   : rel_path,
                'Size (bytes)'   : size_bytes,
                'Size (KB)'      : round(size_bytes / 1024, 3),
                'total_lines'    : counts['total_lines'],
                'code_lines'     : counts['code_lines'],
                'comment_lines'  : counts['comment_lines'],
                'blank_lines'    : counts['blank_lines'],
                'docstring_lines': counts['docstring_lines'],
                'Status'         : status,
            })

df_baris = pd.DataFrame(file_records)

# ── Agregasi per NIM (project) ───────────────────────────────
df_per_nim = df_baris.groupby('NIM').agg(
    Total_File       = ('Nama File',       'count'),
    Total_Jobsheet   = ('Jobsheet',        'nunique'),
    Size_bytes       = ('Size (bytes)',    'sum'),
    Size_KB          = ('Size (KB)',       'sum'),
    total_lines      = ('total_lines',     'sum'),
    code_lines       = ('code_lines',      'sum'),
    comment_lines    = ('comment_lines',   'sum'),
    blank_lines      = ('blank_lines',     'sum'),
    docstring_lines  = ('docstring_lines', 'sum'),
).reset_index()

df_per_nim['Size_MB']         = (df_per_nim['Size_KB'] / 1024).round(3)
df_per_nim['Avg_Lines/File']  = (df_per_nim['total_lines']  / df_per_nim['Total_File']).round(2)
df_per_nim['Avg_Code/File']   = (df_per_nim['code_lines']   / df_per_nim['Total_File']).round(2)
df_per_nim['% Code']          = (
    df_per_nim['code_lines'] / df_per_nim['total_lines'].replace(0, 1) * 100
).round(1)

# ── Agregasi per NIM + Jobsheet ──────────────────────────────
df_per_js = df_baris.groupby(['NIM', 'Jobsheet']).agg(
    Total_File      = ('Nama File',       'count'),
    Size_bytes      = ('Size (bytes)',    'sum'),
    Size_KB         = ('Size (KB)',       'sum'),
    total_lines     = ('total_lines',     'sum'),
    code_lines      = ('code_lines',      'sum'),
    comment_lines   = ('comment_lines',   'sum'),
    blank_lines     = ('blank_lines',     'sum'),
    docstring_lines = ('docstring_lines', 'sum'),
).reset_index()

df_per_js['% Code'] = (
    df_per_js['code_lines'] / df_per_js['total_lines'].replace(0, 1) * 100
).round(1)

# ── Tampilkan ringkasan konsol ───────────────────────────────
print(f'\n  Total file dianalisis : {len(df_baris):,}')
print(f'  Total NIM             : {df_baris["NIM"].nunique()}')
print()
print(f'  {"NIM":<16} {"File":>5} {"JS":>4} {"Total Baris":>12} '
      f'{"Kode":>8} {"Komentar":>9} {"Kosong":>7} '
      f'{"Docstring":>10} {"% Kode":>7} {"Size KB":>8}')
print('  ' + '-' * 90)

for _, r in df_per_nim.iterrows():
    print(f'  {r["NIM"]:<16} {int(r["Total_File"]):>5} '
          f'{int(r["Total_Jobsheet"]):>4} '
          f'{int(r["total_lines"]):>12,} '
          f'{int(r["code_lines"]):>8,} '
          f'{int(r["comment_lines"]):>9,} '
          f'{int(r["blank_lines"]):>7,} '
          f'{int(r["docstring_lines"]):>10,} '
          f'{r["% Code"]:>6.1f}% '
          f'{r["Size_KB"]:>8.1f}')

# Baris TOTAL
print('  ' + '-' * 90)
print(f'  {"TOTAL":<16} '
      f'{len(df_baris):>5} '
      f'{df_baris["Jobsheet"].nunique():>4} '
      f'{int(df_per_nim["total_lines"].sum()):>12,} '
      f'{int(df_per_nim["code_lines"].sum()):>8,} '
      f'{int(df_per_nim["comment_lines"].sum()):>9,} '
      f'{int(df_per_nim["blank_lines"].sum()):>7,} '
      f'{int(df_per_nim["docstring_lines"].sum()):>10,} '
      f'{"":>7} '
      f'{df_per_nim["Size_KB"].sum():>8.1f}')

print()
print(f'  ✅ df_baris   — {len(df_baris)} baris (per file)')
print(f'  ✅ df_per_nim — {len(df_per_nim)} baris (per NIM/project)')
print(f'  ✅ df_per_js  — {len(df_per_js)} baris (per NIM + jobsheet)')
print()
print('  Lanjutkan ke Cell 14 untuk export Excel.')
print('=' * 75)

===========================================================================
📏 CELL 13 — Hitung Jumlah Baris per Project
   Sumber: D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\dataset\05a_Black
===========================================================================

  Total file dianalisis : 2,864
  Total NIM             : 55

  NIM               File   JS  Total Baris     Kode  Komentar  Kosong  Docstring  % Kode  Size KB
  ------------------------------------------------------------------------------------------
  2241720092          22    6        2,330    2,260         0      70          0   97.0%     80.8
  2341720003          48   14        3,772    3,487         0     285          0   92.4%    125.6
  2341720005          52   16        5,112    4,673         0     439          0   91.4%    166.0
  2341720007          77   15       79,109   74,842         0   4,267          0   94.6%   2947.8
  2341720009          49   13        4,703    4,316         0     387          0   91.8%    152.5
  2341720011          50   15        5,891    5,474         0     417          0   92.9%    203.6
  2341720017          28   14        3,434    3,189         0     245          0   92.9%    113.8
  2341720028          58   16        6,981    6,526         0     455          0   93.5%    242.8
  2341720032          60   16       18,853   18,273         0     580          0   96.9%    769.8
  2341720035          52   14        4,683    4,382         0     301          0   93.6%    157.5
  2341720040          55   15        3,992    3,675         0     317          0   92.1%    134.6
  2341720041          52   15        4,111    3,796         0     315          0   92.3%    135.9
  2341720047          54   16        6,168    5,742         0     426          0   93.1%    202.5
  2341720057          79   14        9,029    8,328         0     701          0   92.2%    305.4
  2341720062          71   16       15,346   14,422         0     924          0   94.0%    549.5
  2341720070          54   14        4,349    3,997         0     352          0   91.9%    142.5
  2341720072          61   14       16,083   15,556         0     527          0   96.7%    665.0
  2341720081          51   14        5,309    5,018         0     291          0   94.5%    183.1
  2341720083          46   13        3,827    3,569         0     258          0   93.3%    128.7
  2341720084          50   14        5,879    5,538         0     341          0   94.2%    194.9
  2341720088          62   15        6,580    6,104         0     476          0   92.8%    219.2
  2341720093          41   14       16,247   15,804         0     443          0   97.3%    672.7
  2341720095          43   10        3,919    3,628         0     291          0   92.6%    129.5
  2341720096          55   15        4,757    4,460         0     297          0   93.8%    158.5
  2341720108          67   15       16,219   15,327         0     892          0   94.5%    587.2
  2341720109           9    8        1,686    1,600         0      86          0   94.9%     57.2
  2341720111          49   13        4,470    4,200         0     270          0   94.0%    149.8
  2341720112          58   15        9,093    8,645         0     448          0   95.1%    299.5
  2341720117          59   15        5,059    4,665         0     394          0   92.2%    165.7
  2341720131          50   13        3,675    3,385         0     289          1   92.1%    122.4
  2341720135          41   11        3,316    3,103         0     213          0   93.6%    111.1
  2341720143          51   13        6,366    5,955         0     411          0   93.5%    219.7
  2341720144          52   15        4,621    4,302         0     319          0   93.1%    156.7
  2341720147          50   15        3,691    3,452         0     239          0   93.5%    128.4
  2341720153          52   14        4,770    4,514         0     256          0   94.6%    166.8
  2341720157          76   17       72,637   68,732         0   3,905          0   94.6%   2697.6
  2341720158          51   16        6,515    6,155         0     360          0   94.5%    220.5
  2341720160          55   15        4,633    4,332         0     301          0   93.5%    155.7
  2341720162          51   15        3,849    3,544         0     305          0   92.1%    124.2
  2341720163           4    4          222      214         0       8          0   96.4%      6.9
  2341720164          49   14        3,685    3,393         0     292          0   92.1%    120.6
  2341720168          51   14        4,223    3,944         0     279          0   93.4%    142.9
  2341720174          54   16        4,642    4,249         0     393          0   91.5%    152.6
  2341720176          51   13        3,663    3,445         0     218          0   94.0%    123.6
  2341720187          52   15        3,856    3,526         0     330          0   91.4%    125.2
  2341720191          49   14        4,067    3,755         0     312          0   92.3%    136.1
  2341720200          58   16       29,680   28,022         0   1,658          0   94.4%   1092.2
  2341720217          50   15        6,553    6,179         0     374          0   94.3%    221.0
  2341720218          10   10        2,306    2,121         0     185          0   92.0%     74.7
  2341720227          86   16       83,767   79,182         0   4,585          0   94.5%   3119.1
  2341720234          67   15       14,433   13,542         0     891          0   93.8%    522.4
  2341720248          63   16       11,484   10,795         0     689          0   94.0%    386.4
  2341720250          51   14        3,797    3,483         0     314          0   91.7%    123.8
  2341720251          49   14        3,699    3,480         0     219          0   94.1%    125.1
  244107023008        79   14        9,185    8,461         0     724          0   92.1%    313.8
  ------------------------------------------------------------------------------------------
  TOTAL             2864   19      580,326  546,761         0  33,564          1          20931.0

  ✅ df_baris   — 2864 baris (per file)
  ✅ df_per_nim — 55 baris (per NIM/project)
  ✅ df_per_js  — 768 baris (per NIM + jobsheet)

  Lanjutkan ke Cell 14 untuk export Excel.
===========================================================================

### Export Laporan Baris & Size ke Excel

In [23]:
# ============================================================
# CELL 19 — Export Laporan Baris & Size ke Excel
# Output : Skripsi_AST1\laporan_baris_dan_size.xlsx
#
# Sheet 1 — Ringkasan per NIM (Project)
# Sheet 2 — Ringkasan per NIM + Jobsheet
# Sheet 3 — Detail per File
# Sheet 4 — Statistik Global
# ============================================================

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils  import get_column_letter
from openpyxl.chart  import BarChart, Reference

BARIS_REPORT_PATH = os.path.join(DIRS['LOGS'], '06_laporan_baris_dan_size.xlsx')

# ── Palet warna ──────────────────────────────────────────────
C_HDR_NIM   = '1A237E'   # biru tua    — per NIM
C_HDR_JS    = '1B5E20'   # hijau tua   — per jobsheet
C_HDR_FILE  = '4A148C'   # ungu tua    — per file
C_HDR_STAT  = 'B71C1C'   # merah tua   — statistik global
C_ROW_EVEN  = 'F3F4F6'
C_ROW_ODD   = 'FFFFFF'
C_HIGH_CODE = 'E8F5E9'   # hijau muda  — % kode tinggi (≥70%)
C_LOW_CODE  = 'FFEBEE'   # merah muda  — % kode rendah (<30%)

def thin_border():
    s = Side(style='thin', color='CCCCCC')
    return Border(left=s, right=s, top=s, bottom=s)

def write_header(ws, headers, color, row=1):
    for ci, (label, width) in enumerate(headers, 1):
        cell = ws.cell(row=row, column=ci, value=label)
        cell.font      = Font(name='Arial', bold=True, color='FFFFFF', size=10)
        cell.fill      = PatternFill('solid', fgColor=color)
        cell.alignment = Alignment(horizontal='center', vertical='center',
                                   wrap_text=True)
        cell.border    = thin_border()
        ws.column_dimensions[get_column_letter(ci)].width = width
    ws.row_dimensions[row].height = 32

def write_data_rows(ws, records, start_row=2, pct_cols=None,
                    num_cols=None, highlight_fn=None):
    pct_cols = pct_cols or []
    num_cols = num_cols or []
    for ri, rec in enumerate(records, start_row):
        default_bg = C_ROW_EVEN if ri % 2 == 0 else C_ROW_ODD
        hl         = highlight_fn(rec) if highlight_fn else None
        bg_fill    = PatternFill('solid', fgColor=(hl or default_bg))
        for ci, val in enumerate(rec.values(), 1):
            cell = ws.cell(row=ri, column=ci, value=val)
            cell.font      = Font(name='Arial', size=9)
            cell.fill      = bg_fill
            cell.border    = thin_border()
            cell.alignment = Alignment(
                horizontal='left' if ci == 1 else 'center',
                vertical='center'
            )
            if ci in pct_cols:
                cell.number_format = '0.0"%"'
            if ci in num_cols:
                cell.number_format = '#,##0'

def human_readable(n_bytes: int) -> str:
    for unit in ('B', 'KB', 'MB', 'GB'):
        if abs(n_bytes) < 1024:
            return f'{n_bytes:.2f} {unit}'
        n_bytes /= 1024
    return f'{n_bytes:.2f} TB'


wb = Workbook()

# ════════════════════════════════════════════════════════════
# SHEET 1 — Ringkasan per NIM (Project)
# ════════════════════════════════════════════════════════════
ws1 = wb.active
ws1.title = 'Ringkasan per NIM'

HDR_NIM = [
    ('NIM / Project',        16),
    ('Total File',           11),
    ('Total Jobsheet',       14),
    ('Size (bytes)',         13),
    ('Size (KB)',            10),
    ('Size (MB)',            10),
    ('Total Baris',          12),
    ('Kode',                 10),
    ('Komentar',             10),
    ('Baris Kosong',         13),
    ('Docstring',            11),
    ('% Kode',               10),
    ('Rata-rata Baris/File', 20),
    ('Rata-rata Kode/File',  20),
]

write_header(ws1, HDR_NIM, C_HDR_NIM)

nim_rows = []
for _, r in df_per_nim.iterrows():
    nim_rows.append({
        'NIM / Project'       : r['NIM'],
        'Total File'          : int(r['Total_File']),
        'Total Jobsheet'      : int(r['Total_Jobsheet']),
        'Size (bytes)'        : int(r['Size_bytes']),
        'Size (KB)'           : round(r['Size_KB'], 2),
        'Size (MB)'           : round(r['Size_MB'], 3),
        'Total Baris'         : int(r['total_lines']),
        'Kode'                : int(r['code_lines']),
        'Komentar'            : int(r['comment_lines']),
        'Baris Kosong'        : int(r['blank_lines']),
        'Docstring'           : int(r['docstring_lines']),
        '% Kode'              : round(r['% Code'], 1),
        'Rata-rata Baris/File': round(r['Avg_Lines/File'], 2),
        'Rata-rata Kode/File' : round(r['Avg_Code/File'], 2),
    })

def hl_nim(rec):
    pct = rec.get('% Kode', 0)
    if pct >= 70:
        return C_HIGH_CODE
    if pct < 30 and pct > 0:
        return C_LOW_CODE
    return None

write_data_rows(ws1, nim_rows,
                pct_cols=[12],
                num_cols=[4, 7, 8, 9, 10, 11],
                highlight_fn=hl_nim)

# Baris TOTAL
total_ri = len(nim_rows) + 2
total_vals = [
    'TOTAL',
    int(df_per_nim['Total_File'].sum()),
    int(df_per_nim['Total_Jobsheet'].sum()),
    int(df_per_nim['Size_bytes'].sum()),
    round(df_per_nim['Size_KB'].sum(), 2),
    round(df_per_nim['Size_MB'].sum(), 3),
    int(df_per_nim['total_lines'].sum()),
    int(df_per_nim['code_lines'].sum()),
    int(df_per_nim['comment_lines'].sum()),
    int(df_per_nim['blank_lines'].sum()),
    int(df_per_nim['docstring_lines'].sum()),
    round(df_per_nim['% Code'].mean(), 1),
    round(df_per_nim['Avg_Lines/File'].mean(), 2),
    round(df_per_nim['Avg_Code/File'].mean(), 2),
]
for ci, val in enumerate(total_vals, 1):
    cell = ws1.cell(row=total_ri, column=ci, value=val)
    cell.font      = Font(name='Arial', bold=True, color='FFFFFF', size=10)
    cell.fill      = PatternFill('solid', fgColor=C_HDR_NIM)
    cell.alignment = Alignment(horizontal='center' if ci > 1 else 'left',
                               vertical='center')
    cell.border    = thin_border()
    if ci in [12]:
        cell.number_format = '0.0"%"'
    if ci in [4, 7, 8, 9, 10, 11]:
        cell.number_format = '#,##0'

ws1.freeze_panes    = 'A2'
ws1.auto_filter.ref = f'A1:{get_column_letter(len(HDR_NIM))}1'

# Bar chart — Total baris per NIM
chart1 = BarChart()
chart1.type         = 'col'
chart1.title        = 'Komposisi Baris Kode per NIM'
chart1.y_axis.title = 'Jumlah Baris'
chart1.x_axis.title = 'NIM'
chart1.style        = 10
chart1.width        = 28
chart1.height       = 14
chart1.grouping     = 'stacked'

n = len(nim_rows)
# Kolom: Kode=8, Komentar=9, Kosong=10, Docstring=11
data_ref = Reference(ws1, min_col=8, max_col=11, min_row=1, max_row=n + 1)
cats_ref = Reference(ws1, min_col=1, min_row=2, max_row=n + 1)
chart1.add_data(data_ref, titles_from_data=True)
chart1.set_categories(cats_ref)
ws1.add_chart(chart1, f'A{total_ri + 2}')

# ════════════════════════════════════════════════════════════
# SHEET 2 — Ringkasan per NIM + Jobsheet
# ════════════════════════════════════════════════════════════
ws2 = wb.create_sheet('Per NIM & Jobsheet')

HDR_JS = [
    ('NIM',              14),
    ('Jobsheet',         14),
    ('Total File',       11),
    ('Size (bytes)',     13),
    ('Size (KB)',        10),
    ('Total Baris',      12),
    ('Kode',             10),
    ('Komentar',         10),
    ('Baris Kosong',     13),
    ('Docstring',        11),
    ('% Kode',           10),
]

write_header(ws2, HDR_JS, C_HDR_JS)

js_rows = []
for _, r in df_per_js.iterrows():
    js_rows.append({
        'NIM'         : r['NIM'],
        'Jobsheet'    : r['Jobsheet'],
        'Total File'  : int(r['Total_File']),
        'Size (bytes)': int(r['Size_bytes']),
        'Size (KB)'   : round(r['Size_KB'], 2),
        'Total Baris' : int(r['total_lines']),
        'Kode'        : int(r['code_lines']),
        'Komentar'    : int(r['comment_lines']),
        'Baris Kosong': int(r['blank_lines']),
        'Docstring'   : int(r['docstring_lines']),
        '% Kode'      : round(r['% Code'], 1),
    })

write_data_rows(ws2, js_rows,
                pct_cols=[11],
                num_cols=[4, 6, 7, 8, 9, 10],
                highlight_fn=lambda r: C_HIGH_CODE if r.get('% Kode', 0) >= 70 else None)

ws2.freeze_panes    = 'A2'
ws2.auto_filter.ref = f'A1:{get_column_letter(len(HDR_JS))}1'

# ════════════════════════════════════════════════════════════
# SHEET 3 — Detail per File
# ════════════════════════════════════════════════════════════
ws3 = wb.create_sheet('Detail per File')

HDR_FILE = [
    ('NIM',              14),
    ('Jobsheet',         14),
    ('Nama File',        22),
    ('Path Relatif',     45),
    ('Size (bytes)',     13),
    ('Size (KB)',        10),
    ('Total Baris',      12),
    ('Kode',             10),
    ('Komentar',         10),
    ('Baris Kosong',     13),
    ('Docstring',        11),
    ('% Kode',           10),
    ('Status',           12),
]

write_header(ws3, HDR_FILE, C_HDR_FILE)

file_rows = []
for _, r in df_baris.iterrows():
    pct = round(
        r['code_lines'] / r['total_lines'] * 100
        if r['total_lines'] > 0 else 0, 1
    )
    file_rows.append({
        'NIM'          : r['NIM'],
        'Jobsheet'     : r['Jobsheet'],
        'Nama File'    : r['Nama File'],
        'Path Relatif' : r['Path Relatif'],
        'Size (bytes)' : int(r['Size (bytes)']),
        'Size (KB)'    : round(r['Size (KB)'], 3),
        'Total Baris'  : int(r['total_lines']),
        'Kode'         : int(r['code_lines']),
        'Komentar'     : int(r['comment_lines']),
        'Baris Kosong' : int(r['blank_lines']),
        'Docstring'    : int(r['docstring_lines']),
        '% Kode'       : pct,
        'Status'       : r['Status'],
    })

def hl_file(rec):
    if rec.get('Status', 'OK') != 'OK':
        return 'FFEBEE'   # error — merah muda
    if rec.get('Total Baris', 0) == 0:
        return 'FFF9C4'   # file kosong — kuning
    return None

write_data_rows(ws3, file_rows,
                pct_cols=[12],
                num_cols=[5, 7, 8, 9, 10, 11],
                highlight_fn=hl_file)

ws3.freeze_panes    = 'A2'
ws3.auto_filter.ref = f'A1:{get_column_letter(len(HDR_FILE))}1'

# ════════════════════════════════════════════════════════════
# SHEET 4 — Statistik Global
# ════════════════════════════════════════════════════════════
ws4 = wb.create_sheet('Statistik Global')

total_bytes      = int(df_per_nim['Size_bytes'].sum())
total_kb         = round(df_per_nim['Size_KB'].sum(), 2)
total_mb         = round(df_per_nim['Size_MB'].sum(), 3)
total_all_lines  = int(df_per_nim['total_lines'].sum())
total_code       = int(df_per_nim['code_lines'].sum())
total_comment    = int(df_per_nim['comment_lines'].sum())
total_blank      = int(df_per_nim['blank_lines'].sum())
total_docstring  = int(df_per_nim['docstring_lines'].sum())
pct_code_global  = round(total_code / total_all_lines * 100 if total_all_lines else 0, 1)
nim_most_code    = df_per_nim.loc[df_per_nim['code_lines'].idxmax(), 'NIM']
nim_most_file    = df_per_nim.loc[df_per_nim['Total_File'].idxmax(), 'NIM']

stat_blocks = [
    ('📦 DATASET', [
        ('Total NIM / Project',             df_baris['NIM'].nunique()),
        ('Total Jobsheet',                  df_baris['Jobsheet'].nunique()),
        ('Total File .py',                  len(df_baris)),
        ('Total Size',                      human_readable(total_bytes)),
        ('Total Size (KB)',                 total_kb),
        ('Total Size (MB)',                 total_mb),
    ]),
    ('📏 KOMPOSISI BARIS', [
        ('Total Semua Baris',               f'{total_all_lines:,}'),
        ('Baris Kode Aktif',                f'{total_code:,}'),
        ('Baris Komentar',                  f'{total_comment:,}'),
        ('Baris Kosong',                    f'{total_blank:,}'),
        ('Baris Docstring',                 f'{total_docstring:,}'),
        ('% Kode dari Total',               f'{pct_code_global}%'),
    ]),
    ('📐 RATA-RATA', [
        ('Rata-rata Baris / File',          round(df_baris['total_lines'].mean(), 2)),
        ('Rata-rata Kode / File',           round(df_baris['code_lines'].mean(), 2)),
        ('Rata-rata File / NIM',            round(df_per_nim['Total_File'].mean(), 2)),
        ('Rata-rata Size / File (KB)',      round(df_baris['Size (KB)'].mean(), 3)),
    ]),
    ('🏆 TERTINGGI', [
        ('NIM dengan Kode Terbanyak',       nim_most_code),
        ('NIM dengan File Terbanyak',       nim_most_file),
        ('Max Baris dalam 1 File',          int(df_baris['total_lines'].max())),
        ('Max Size dalam 1 File (KB)',      round(df_baris['Size (KB)'].max(), 2)),
    ]),
]

ws4.column_dimensions['A'].width = 34
ws4.column_dimensions['B'].width = 24

current_row = 1
for block_title, items in stat_blocks:
    # Header blok
    for ci, txt in enumerate([block_title, ''], 1):
        c = ws4.cell(row=current_row, column=ci, value=txt if ci == 1 else '')
        c.font      = Font(name='Arial', bold=True, color='FFFFFF', size=11)
        c.fill      = PatternFill('solid', fgColor=C_HDR_STAT)
        c.alignment = Alignment(horizontal='left', vertical='center')
        c.border    = thin_border()
    ws4.row_dimensions[current_row].height = 26
    current_row += 1

    for ri, (label, val) in enumerate(items):
        bg = C_ROW_EVEN if ri % 2 == 0 else C_ROW_ODD
        for ci, v in enumerate([label, val], 1):
            c = ws4.cell(row=current_row, column=ci, value=v)
            c.font      = Font(name='Arial', size=10, bold=(ci == 1))
            c.fill      = PatternFill('solid', fgColor=bg)
            c.alignment = Alignment(
                horizontal='left' if ci == 1 else 'center',
                vertical='center'
            )
            c.border = thin_border()
        current_row += 1

    current_row += 1  # baris kosong antar blok

# ── Simpan ───────────────────────────────────────────────────
wb.save(BARIS_REPORT_PATH)

print()
print('=' * 75)
print('✅ Laporan berhasil disimpan!')
print(f'   📊 {BARIS_REPORT_PATH}')
print()
print(f'   📋 Sheet 1 — Ringkasan per NIM      : {len(nim_rows)} baris + chart')
print(f'   📋 Sheet 2 — Per NIM & Jobsheet     : {len(js_rows)} baris')
print(f'   📋 Sheet 3 — Detail per File        : {len(file_rows)} baris')
print(f'   📋 Sheet 4 — Statistik Global')
print()
print('  ┌──────────────────────────────┬──────────────────┐')
print('  │ Metrik                       │       Nilai      │')
print('  ├──────────────────────────────┼──────────────────┤')
print(f'  │ Total File                   │ {len(df_baris):>16,} │')
print(f'  │ Total Size                   │ {human_readable(total_bytes):>16} │')
print(f'  │ Total Semua Baris            │ {total_all_lines:>16,} │')
print(f'  │ Baris Kode Aktif             │ {total_code:>16,} │')
print(f'  │ Baris Komentar               │ {total_comment:>16,} │')
print(f'  │ Baris Kosong                 │ {total_blank:>16,} │')
print(f'  │ Baris Docstring              │ {total_docstring:>16,} │')
print(f'  │ % Kode Aktif                 │ {pct_code_global:>15.1f}% │')
print('  └──────────────────────────────┴──────────────────┘')
print('=' * 75)

===========================================================================
✅ Laporan berhasil disimpan!
   📊 D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output\06_laporan_baris_dan_size.xlsx

   📋 Sheet 1 — Ringkasan per NIM      : 55 baris + chart
   📋 Sheet 2 — Per NIM & Jobsheet     : 768 baris
   📋 Sheet 3 — Detail per File        : 2864 baris
   📋 Sheet 4 — Statistik Global

  ┌──────────────────────────────┬──────────────────┐
  │ Metrik                       │       Nilai      │
  ├──────────────────────────────┼──────────────────┤
  │ Total File                   │            2,864 │
  │ Total Size                   │         20.44 MB │
  │ Total Semua Baris            │          580,326 │
  │ Baris Kode Aktif             │          546,761 │
  │ Baris Komentar               │                0 │
  │ Baris Kosong                 │           33,564 │
  │ Baris Docstring              │                1 │
  │ % Kode Aktif                 │            94.2% │
  └──────────────────────────────┴──────────────────┘
===========================================================================

## 9. Waktu eksekusi

### Project Level (CProfile)

In [12]:
# HELPER FUNCTIONS (PROJECT LEVEL CPROFILE)
# -----------------------------------------------------------------
TIMEOUT = 30
ITERATIONS = 3

# HITUNG JUMLAH FUNCTION PER FILE
def count_functions_in_file(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read())

        function_count = sum(
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            for node in ast.walk(tree)
        )
        return function_count

    except Exception:
        return None


# EKSTRAK METADATA FILE
def extract_metadata(file_path, dataset_folder):
    rel_path = os.path.relpath(file_path, dataset_folder)
    parts = rel_path.split(os.sep)

    file_name = parts[-1]
    nim = parts[0] if len(parts) >= 2 else "unknown"
    module = parts[1] if len(parts) >= 3 else "root"

    return nim, module, file_name


# JALANKAN CPROFILE
def run_with_cprofile(file_path):
    runtimes = []

    try:
        for _ in range(ITERATIONS):
            with tempfile.NamedTemporaryFile(delete=False) as temp_prof:
                profile_file = temp_prof.name

            subprocess.run(
                [sys.executable, "-m", "cProfile", "-o", profile_file, file_path],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
                timeout=TIMEOUT,
            )

            stats = pstats.Stats(profile_file)
            runtimes.append(stats.total_tt)
            os.remove(profile_file)

        runtime = sum(runtimes) / len(runtimes)
        function_count = count_functions_in_file(file_path)

        return "SUCCESS", runtime, function_count, ""

    except subprocess.TimeoutExpired:
        return "TIMEOUT", None, None, "Execution timeout"

    except Exception as e:
        return "FAILED", None, None, str(e)

In [ ]:
# EXECUTION (PROJECT LEVEL CPROFILE)
# -----------------------------------------------------------------

DATASET_INPUT = DIRS["AUTOPEP8"]
FILE_REPORT = RESULTS["RUN_PROJECT"]

py_files = []

for root, dirs, files in os.walk(DATASET_INPUT):
    dirs[:] = [d for d in dirs if d not in [".git", "__pycache__"]]

    for file in files:
        if file.endswith(".py"):
            py_files.append(os.path.join(root, file))

total_files = len(py_files)

print("=" * 60)
print(f"{'MULAI PROFILING PROJECT LEVEL (CPROFILE)':^60}")
print("-" * 60)

records = []

success_count = 0
fail_count = 0
timeout_count = 0

pbar = tqdm(
    py_files,
    total=total_files,
    desc="Profiling Python Files",
    unit="file"
)

for file_path in pbar:
    nim, module, file_name = extract_metadata(file_path, DATASET_INPUT)
    status, runtime, function_count, message = run_with_cprofile(file_path)

    if status == "SUCCESS":
        success_count += 1
    elif status == "FAILED":
        fail_count += 1
    elif status == "TIMEOUT":
        timeout_count += 1

    records.append({
        "nim": nim,
        "module": module,
        "file_name": file_name,
        "function_count": function_count,
        "status": status,
        "execution_time_seconds": runtime,
        "message": message
    })
    
    # tampilkan detail error jika gagal
    if status in ["FAILED", "TIMEOUT"]:
        pbar.write(
            f"[{status}] {nim} | {module} | {file_name}\n"
            f" -> {message}"
        )

    pbar.set_postfix({
        "success": success_count,
        "fail": fail_count,
        "timeout": timeout_count
    })

pbar.close()

df_cprofile = pd.DataFrame(records)

if not df_cprofile.empty:
    df_cprofile["execution_time_seconds"] = (
        df_cprofile["execution_time_seconds"].fillna(0).round(6)
    )

print(f"{' Selesai ':-^60}")
print(f"Total file diproses : {len(df_cprofile)}")

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")
print("="*60)

In [ ]:
# SUMMARY & REPORT
# ------------------------------------------------------------------------

# simpan ke excel
df_cprofile.to_excel(FILE_REPORT, index=False)

print("=" * 60)
print(f"{'RINGKASAN HASIL PROFILING':^60}")
print("-" * 60)
print(f"{'Total File Dianalisis':<30}: {len(df_cprofile)}")
print(f"{'File SUCCESS':<30}: {(df_cprofile['status'] == 'SUCCESS').sum()}")
print(f"{'File FAILED':<30}: {(df_cprofile['status'] == 'FAILED').sum()}")
print(f"{'File TIMEOUT':<30}: {(df_cprofile['status'] == 'TIMEOUT').sum()}")
print(f"{'Rata-rata Runtime':<30}: {round(df_cprofile['execution_time_seconds'].mean(), 6)}\n")

print("-" * 60)
print(f"{'File Report disimpan di ':<30}: {FILE_REPORT}\n")
display(df_cprofile.head(10))

print("=" * 60)
# TOP 10 RUNTIME
df_success = df_cprofile[df_cprofile["status"] == "SUCCESS"].copy()

print(f"{'10 RUNTIME TERLAMA':^60}")
top_slowest = (
    df_success
    .sort_values("execution_time_seconds", ascending=False)
    [["nim", "module", "file_name", "function_count", "execution_time_seconds"]]
    .head(10)
)
display(top_slowest)
print("=" * 60)
print(f"{'10 RUNTIME TERCEPAT':^60}")
top_fastest = (
    df_success
    .sort_values("execution_time_seconds", ascending=True)
    [["nim", "module", "file_name", "function_count", "execution_time_seconds"]]
    .head(10)
)
display(top_fastest)

print("-" * 60)

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
                 RINGKASAN HASIL PROFILING
------------------------------------------------------------
Total File Dianalisis         : 219
File SUCCESS                  : 217
File FAILED                   : 0
File TIMEOUT                  : 2
Rata-rata Runtime             : 3.056261

------------------------------------------------------------
File Report disimpan di       : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output(6)\07a_runtime_project_level.xlsx

,nim,module,file_name,function_count,status,execution_time_seconds,message
0,2241720092,js02,p01.py,NaN,TIMEOUT,0.000000,Execution timeout
1,2241720092,js02,p02.py,0.0,SUCCESS,1.174523,
2,2241720092,js02,p03.py,0.0,SUCCESS,9.565122,
3,2241720092,js02,p04.py,0.0,SUCCESS,0.001139,
4,2241720092,js02,tp.py,0.0,SUCCESS,2.452671,
5,2241720092,js03,p01.py,0.0,SUCCESS,5.247983,
6,2241720092,js03,p02.py,0.0,SUCCESS,0.001119,
7,2241720092,js03,p03.py,0.0,SUCCESS,2.070893,
8,2241720092,js03,p04.py,0.0,SUCCESS,0.062384,
9,2241720092,js03,tp.py,0.0,SUCCESS,2.129865,

============================================================
                     10 RUNTIME TERLAMA

            nim module file_name  function_count  execution_time_seconds
33   2341720095   js04    p02.py             2.0               22.594117
83   2341720176   js04    p02.py             2.0               21.753703
132  2341720191   js04    p02.py             2.0               18.159385
182  2341720217   js04    p02.py             2.0               17.395598
11   2241720092   js04    p02.py             2.0               15.092833
55   2341720095   js11    p01.py             2.0               10.199304
56   2341720095   js11    p02.py             2.0                9.990661
53   2341720095   js09     tp.py             0.0                9.706352
2    2241720092   js02    p03.py             0.0                9.565122
57   2341720095   js11    p03.py             1.0                9.389036

============================================================
                    10 RUNTIME TERCEPAT

,nim,module,file_name,function_count,execution_time_seconds
68,2341720163,unclassified,tp.py,0.0,0.000009
69,2341720176,js01,p01.py,0.0,0.000011
75,2341720176,js02,tp.py,0.0,0.000011
170,2341720217,js01,tp.py,0.0,0.000015
169,2341720217,js01,DEMO_P1_JS01.py,0.0,0.000018
114,2341720176,js13,tp.py,0.0,0.000735
116,2341720176,js14,p02.py,0.0,0.000739
110,2341720176,js11,tp.py,1.0,0.000752
217,2341720217,kuis,kuis.py,0.0,0.000770
117,2341720176,js14,tp.py,0.0,0.000776

------------------------------------------------------------
Diproses pada 2026-04-06 19:24:29

### Function Level (timeit)

In [7]:
# HELPER FUNCTIONS (FUNCTION LEVEL TIMEIT)
# ------------------------------------------------------------------------------

RUN_REPEAT = 3
TIMEOUT = 30

# blok input agar tidak menunggu user
builtins.input = lambda *args: "0"

# EKSTRAK METADATA
def extract_metadata(file_path, dataset_folder):
    rel_path = os.path.relpath(file_path, dataset_folder)
    parts = rel_path.split(os.sep)

    file_name = parts[-1]
    nim = parts[0] if len(parts) >= 2 else "unknown"
    module = parts[1] if len(parts) >= 3 else "root"

    return nim, module, file_name

# EXTRACT FUNCTION DARI AST
def extract_functions(file_path):
    with open(file_path, "r", encoding="utf8", errors="ignore") as f:
        code = f.read()

    try:
        tree = ast.parse(code)
    except Exception:
        return []

    functions = []

    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            func_code = ast.get_source_segment(code, node)

            if func_code:
                functions.append((node.name, func_code))

    return functions


# GENERATE WRAPPER FUNCTION
def generate_wrapper(func_name, func_code):
    try:
        tree = ast.parse(func_code)
        func_node = tree.body[0]

        param_count = len(func_node.args.args)
        dummy_args = ",".join(["0"] * param_count)

    except Exception:
        dummy_args = ""

    wrapper = f"""
{func_code}

def __wrapper():
    try:
        {func_name}({dummy_args})
    except:
        pass
"""
    return wrapper


# RUN DENGAN TIMEOUT
def run_with_timeout(code):
    result = {"status": None, "runtime": None, "message": ""}

    def worker():
        original_stdout = sys.stdout
        try:
            local_env = {}
            dummy = io.StringIO()

            local_env["input"] = lambda *args: "0"

            exec(code, local_env)

            with contextlib.redirect_stdout(dummy), contextlib.redirect_stderr(dummy):
                runtime = timeit.timeit(
                    "__wrapper()",
                    globals=local_env,
                    number=RUN_REPEAT
                )

            result["status"] = "SUCCESS"
            result["runtime"] = runtime / RUN_REPEAT

        except Exception as e:
            result["status"] = "FAILED"
            result["message"] = str(e)

    thread = threading.Thread(target=worker)
    thread.start()
    thread.join(TIMEOUT)

    if thread.is_alive():
        return "TIMEOUT", None, "Execution timeout"

    return result["status"], result["runtime"], result["message"]

In [10]:
# EXECUTION
# ------------------------------------------------------------------------------

DATASET_INPUT = DIRS["AUTOPEP8"]
FILE_REPORT = RESULTS["RUN_FUNCTION"]

records = []

print("=" * 60)
print("ANALISIS RUNTIME per FUNCTION")

skip_funcs = ["main", "menu", "run", "start", "program", "main_menu"]
status_counter = defaultdict(int)

# kumpulkan semua file python
all_py_files = []
for root, dirs, files in os.walk(DATASET_INPUT):
    for file in files:
        if file.endswith(".py"):
            all_py_files.append(os.path.join(root, file))

pbar_files = tqdm(
    all_py_files,
    desc="Processing Files",
    unit="file",
    dynamic_ncols=True
)

for file_path in pbar_files:
    nim, module, file_name = extract_metadata(file_path, DATASET_INPUT)
    functions = extract_functions(file_path)

    if not functions:
        status_counter["NO FUNCTION"] += 1

        records.append({
            "nim": nim,
            "module": module,
            "file_name": file_name,
            "function_name": "NO_FUNCTION",
            "status": "NO FUNCTION",
            "execution_time_seconds": None,
            "message": "No function detected"
        })
        continue

    for func_name, func_code in functions:
        if func_name.lower() in skip_funcs:
            status_counter["SKIPPED"] += 1

            records.append({
                "nim": nim,
                "module": module,
                "file_name": file_name,
                "function_name": func_name,
                "status": "SKIPPED",
                "execution_time_seconds": None,
                "message": "Skipped Function"
            })
            
            pbar_files.write(
                f"[SKIPPED] {nim} | {module} | {file_name} | {func_name} \n"
                f" -> Skipped Function"
            )
            
            continue

        wrapper_code = generate_wrapper(func_name, func_code)
        status, runtime, message = run_with_timeout(wrapper_code)

        status_counter[status] += 1

        records.append({
            "nim": nim,
            "module": module,
            "file_name": file_name,
            "function_name": func_name,
            "status": status,
            "execution_time_seconds": runtime,
            "message": message
        })
        # tampilkan detail error jika gagal
        if status in ["FAILED", "TIMEOUT"]:
            pbar_files.write(
                f"[{status}] {nim} | {module} | {file_name} | {func_name} \n"
                f" -> {message}"
            )

    pbar_files.set_postfix_str(
        f"success={status_counter['SUCCESS']} "
        f"fail={status_counter['FAILED']} "
        f"timeout={status_counter['TIMEOUT']} "
        f"skip={status_counter['SKIPPED']}"
    )

pbar_files.close()

df_runtimeFunct = pd.DataFrame(records)

df_runtimeFunct["execution_time_seconds"] = pd.to_numeric(
    df_runtimeFunct["execution_time_seconds"],
    errors="coerce"
).round(7)

print(f"{' SELESAI ':=^60}")
print(f"Total record: {len(df_runtimeFunct)}")

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Diproses pada {timestamp}")

============================================================
ANALISIS RUNTIME per FUNCTION

Processing Files:   0%|          | 0/2864 [00:00<?, ?file/s]

[FAILED] 2341720003 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720005 | js09 | tp2.py | load_spam_dataset
 -> name 'Tuple' is not defined
[FAILED] 2341720005 | js09 | tp2.py | build_pipeline_count
 -> name 'Pipeline' is not defined
[FAILED] 2341720005 | js09 | tp2.py | build_pipeline_tfidf
 -> name 'Pipeline' is not defined
[FAILED] 2341720005 | js09 | tp2.py | evaluate_model
 -> name 'Pipeline' is not defined
[FAILED] 2341720005 | js09 | tp2.py | print_eval
 -> name 'EvalResult' is not defined
[SKIPPED] 2341720005 | js09 | tp2.py | main
 -> Skipped Function
[FAILED] 2341720005 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720007 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-20.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-30.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-40.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-50.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-60.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-70.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-80.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-90.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML 21K-train-95.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-20.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-20_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-30.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-30_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-40.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-40_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-50.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-50_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-60.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-60_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-70.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-70_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-80.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-80_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-90.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-90_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-95.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720007 | pbl | Notebook_PCVK_Patch_ML train-95_smooth-0.1.py | __init__
 -> name 'TOTAL_FEAUTURES' is not defined
[FAILED] 2341720009 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720009 | pbl | Digital_Text_OCR.py | show_images_by_label
 -> name 'pd' is not defined
[FAILED] 2341720009 | pbl | Digital_Text_OCR.py | plot_learning_curve
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | Digital_Text_OCR.py | predict_all_models
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | Digital_Text_OCR.py | predict_all_models_with_confidence
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | preprocess_char
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | process_text_detection
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | process_line_grouping
 -> name 'List' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | merge_small_vertical_components
 -> name 'List' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | segment_characters_grayscale
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | segment_characters
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | predict_char_models
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | extract_text_from_line
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | parse_line_by_position
 -> name 'Tuple' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | extract_amount_from_text
 -> name 'Optional' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | parse_detail_line
 -> name 'Tuple' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | process_text_extraction
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | process_verification
 -> name 'List' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | get_field_colors
 -> name 'Dict' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | extract_layout_fingerprint
 -> name 'List' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | get_template_layout_fingerprint
 -> name 'Dict' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | calculate_layout_similarity
 -> name 'LayoutFingerprint' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | validate_layout_structure
 -> name 'List' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | validate_line_count
 -> name 'List' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | display_verification_results
 -> name 'VerificationResult' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | create_legend_image
 -> name 'List' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | visualize_results
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | create_annotated_image
 -> name 'np' is not defined
[FAILED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | layout_aware_receipt_verification
 -> name 'Dict' is not defined
[SKIPPED] 2341720009 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | main
 -> Skipped Function
[FAILED] 2341720011 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720011 | pbl | pbl.py | list_classes
 -> name 'Path' is not defined
[FAILED] 2341720011 | pbl | pbl.py | collect_files_labels
 -> name 'Path' is not defined
[FAILED] 2341720011 | pbl | pbl.py | make_stratified_split
 -> name 'SEED' is not defined
[FAILED] 2341720011 | pbl | pbl.py | glcm_props
 -> name 'np' is not defined
[FAILED] 2341720011 | pbl | pbl.py | build_hog_pca_pipeline_from_split
 -> name 'SEED' is not defined
[FAILED] 2341720011 | pbl | pbl.py | create_xgb_objective
 -> name 'SEED' is not defined
[FAILED] 2341720011 | pbl | pbl.py | tune_xgb_with_optuna
 -> name 'SEED' is not defined
[FAILED] 2341720017 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720028 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720028 | js11 | tp.py | infer_label_from_path
 -> name 'Path' is not defined
[FAILED] 2341720028 | pbl | pbl.py | list_classes
 -> name 'Path' is not defined
[FAILED] 2341720028 | pbl | pbl.py | collect_files_labels
 -> name 'Path' is not defined
[FAILED] 2341720028 | pbl | pbl.py | make_stratified_split
 -> name 'SEED' is not defined
[FAILED] 2341720028 | pbl | pbl.py | glcm_props
 -> name 'np' is not defined
[FAILED] 2341720028 | pbl | pbl.py | build_hog_pca_pipeline_from_split
 -> name 'SEED' is not defined
[FAILED] 2341720028 | pbl | pbl.py | create_xgb_objective
 -> name 'SEED' is not defined
[FAILED] 2341720028 | pbl | pbl.py | tune_xgb_with_optuna
 -> name 'SEED' is not defined
[FAILED] 2341720032 | js07 | p02.py | compute_recall_at_k
 -> name 'np' is not defined
[FAILED] 2341720032 | js07 | p02.py | run_experiment
 -> name 'Dict' is not defined
[SKIPPED] 2341720032 | js07 | p02.py | main
 -> Skipped Function
[FAILED] 2341720032 | js07 | p04.py | safe_normalize_l2
 -> name 'np' is not defined
[FAILED] 2341720032 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720035 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720040 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720040 | uas | controller.py | predict_image_endpoint
 -> name 'File' is not defined
[FAILED] 2341720040 | uas | service.py | segment_grabcut
 -> name 'np' is not defined
[FAILED] 2341720040 | uas | service.py | extract_hog_features
 -> name 'np' is not defined
[FAILED] 2341720040 | uas | service.py | extract_lbp_features
 -> name 'np' is not defined
[FAILED] 2341720040 | uas | service.py | extract_features
 -> name 'np' is not defined
[FAILED] 2341720040 | uas | service.py | predict_from_file
 -> name 'Tuple' is not defined
[FAILED] 2341720041 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720041 | uas | app_api.py | predict_fruit
 -> name 'File' is not defined
[FAILED] 2341720047 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720047 | js15 | app2.py | resize_image
 -> name 'Image' is not defined
[FAILED] 2341720047 | js15 | app2.py | extract_30_patches
 -> name 'Image' is not defined
[FAILED] 2341720057 | js11 | p02.py | plot_3D
 -> name 'X' is not defined
[FAILED] 2341720057 | pbl | Dataset_preparation.py | move_column_after
 -> name 'pd' is not defined
[FAILED] 2341720057 | pbl | data_preprocessing.py | preprocess_char
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Digital_Text_OCR.py | show_images_by_label
 -> name 'pd' is not defined
[FAILED] 2341720057 | pbl | Digital_Text_OCR.py | plot_learning_curve
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Digital_Text_OCR.py | predict_all_models
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Digital_Text_OCR.py | predict_all_models_with_confidence
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | preprocess_char
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | process_text_detection
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | process_line_grouping
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | merge_small_vertical_components
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | segment_characters_grayscale
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | segment_characters
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | predict_char_models
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | extract_text_from_line
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | parse_line_by_position
 -> name 'Tuple' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | extract_amount_from_text
 -> name 'Optional' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | parse_detail_line
 -> name 'Tuple' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | process_text_extraction
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | process_verification
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | get_field_colors
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | extract_layout_fingerprint
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | get_template_layout_fingerprint
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | calculate_layout_similarity
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | validate_layout_structure
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | validate_line_count
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | display_verification_results
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | create_legend_image
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | visualize_results
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | create_annotated_image
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | layout_aware_receipt_verification
 -> name 'Optional' is not defined
[SKIPPED] 2341720057 | pbl | Full_Pipeline_Fake_Receipt_Detection.py | main
 -> Skipped Function
[FAILED] 2341720057 | pbl | Image_Forensic.py | show_image
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | detect_format
 -> name 'Optional' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | ela
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | block_variance
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | noise_map
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | sharpness_map
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | compute_scores
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | decide_fakeness
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | Image_Forensic.py | tampering_heatmap
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | get_field_colors
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | extract_layout_fingerprint
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | get_template_layout_fingerprint
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | calculate_layout_similarity
 -> name 'LayoutFingerprint' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | validate_layout_structure
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | validate_line_count
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | display_verification_results
 -> name 'VerificationResult' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | create_legend_image
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | visualize_results
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | create_annotated_image
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | layout_aware_receipt_verification.py | layout_aware_receipt_verification
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Layout_Matching.py | preprocess
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Layout_Matching.py | template_score
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Layout_Matching.py | orb_match_score
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Layout_Matching.py | load_prototypes
 -> name 'Dict' is not defined
[FAILED] 2341720057 | pbl | Layout_Matching.py | detect_category
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | Layout_Matching.py | category_check
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | main.py | lifespan
 -> name 'FastAPI' is not defined
[FAILED] 2341720057 | pbl | main.py | detect_fake_receipt
 -> name 'UploadFile' is not defined
[FAILED] 2341720057 | pbl | ml_model_loader.py | load_model
 -> name 'LogisticRegression' is not defined
[FAILED] 2341720057 | pbl | No_Deep_Learning_OCR_model.py | preprocess
 -> name 'NDArray' is not defined
[FAILED] 2341720057 | pbl | No_Deep_Learning_OCR_model.py | segment_lines
 -> name 'NDArray' is not defined
[FAILED] 2341720057 | pbl | No_Deep_Learning_OCR_model.py | segment_chars
 -> name 'NDArray' is not defined
[FAILED] 2341720057 | pbl | No_Deep_Learning_OCR_model.py | normalize
 -> name 'NDArray' is not defined
[FAILED] 2341720057 | pbl | No_Deep_Learning_OCR_model.py | zoning
 -> name 'NDArray' is not defined
[FAILED] 2341720057 | pbl | No_Deep_Learning_OCR_model.py | classify_char
 -> name 'NDArray' is not defined
[FAILED] 2341720057 | pbl | No_Deep_Learning_OCR_model.py | classical_ocr
 -> name 'NDArray' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | preprocess_char
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | process_text_detection
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | process_line_grouping
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | merge_small_vertical_components
 -> name 'List' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | segment_characters_grayscale
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | segment_characters
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | predict_char_models
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | extract_text_from_line
 -> name 'np' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | parse_line_by_position
 -> name 'Tuple' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | extract_amount_from_text
 -> name 'Optional' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | parse_detail_line
 -> name 'Tuple' is not defined
[FAILED] 2341720057 | pbl | OPTIMIZED_Full_Pipeline_Fake_Receipt_Detection.py | process_text_extraction

In [13]:
# SUMMARY & REPORT
# ------------------------------------------------------------------------------

# simpan
with pd.ExcelWriter(FILE_REPORT, engine="xlsxwriter") as writer:
    df_runtimeFunct.to_excel(
        writer,
        index=False,
        sheet_name="runtimeFunction"
    )

    workbook = writer.book
    worksheet = writer.sheets["runtimeFunction"]

    runtime_col = df_runtimeFunct.columns.get_loc("execution_time_seconds")
    number_format = workbook.add_format({
        "num_format": "0.0000000"
    })

    worksheet.set_column(runtime_col, runtime_col, 30, number_format)

    # auto width kolom lain
    for i, col in enumerate(df_runtimeFunct.columns):
        if i == runtime_col:
            continue
        max_len = max(
            df_runtimeFunct[col].astype(str).map(len).max(),
            len(col)
        ) + 2

        worksheet.set_column(i, i, max_len)


# ===== SUMMARY =====
print("=" * 60)
print("RINGKASAN ANALISIS RUNTIME PER FUNCTION")
print("-" * 60)

total_repo = len([
    d for d in os.listdir(DATASET_INPUT)
    if os.path.isdir(os.path.join(DATASET_INPUT, d))
])

total_files = len(all_py_files)

total_no_function_files = (
    df_runtimeFunct["status"] == "NO FUNCTION"
).sum()

total_functions = df_runtimeFunct[
    df_runtimeFunct["function_name"] != "NO_FUNCTION"
].shape[0]

status_summary = df_runtimeFunct["status"].value_counts()

print(f"Total Repository             : {total_repo}")
print(f"Total File Python            : {total_files}")
print(f"Total File tanpa Function    : {total_no_function_files}")
print(f"Total Function ditemukan     : {total_functions}")
print("-" * 60)
print("Status Function:")
for status, total in status_summary.items():
    print(f"- {status:<30}: {total}")

print("=" * 60)
print(f"Hasil disimpan di : {FILE_REPORT}")

display(df_runtimeFunct.head(20))

print(f"{' 10 Function Terlama ':=^60}")
top_slowest = (
    df_runtimeFunct[df_runtimeFunct["status"] == "SUCCESS"]
    .sort_values("execution_time_seconds", ascending=False)
    [["nim", "module", "file_name", "function_name", "execution_time_seconds"]]
    .head(10)
)
display(top_slowest)

print(f"{' 10 Function Tercepat ':=^60}")
top_fastest = (
    df_runtimeFunct[df_runtimeFunct["status"] == "SUCCESS"]
    .sort_values("execution_time_seconds", ascending=True)
    [["nim", "module", "file_name", "function_name", "execution_time_seconds"]]
    .head(10)
)
display(top_fastest)

timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"\nDiproses pada {timestamp}")

============================================================
RINGKASAN ANALISIS RUNTIME PER FUNCTION
------------------------------------------------------------
Total Repository             : 55
Total File Python            : 2864
Total File tanpa Function    : 1873
Total Function ditemukan     : 8954
------------------------------------------------------------
Status Function:
- SUCCESS                       : 8356
- NO FUNCTION                   : 1873
- FAILED                        : 584
- SKIPPED                       : 14
============================================================
Hasil disimpan di : D:\PUTRI\D4\SEMESTER 8 (4C)\skripsi\code\Output\07b_runtime_function_level.xlsx

,nim,module,file_name,function_name,status,execution_time_seconds,message
0,2241720092,js02,p01.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
1,2241720092,js02,p02.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
2,2241720092,js02,p03.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
3,2241720092,js02,p04.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
4,2241720092,js02,tp.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
5,2241720092,js03,p01.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
6,2241720092,js03,p02.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
7,2241720092,js03,p03.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
8,2241720092,js03,p04.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
9,2241720092,js03,tp.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
10,2241720092,js04,p01.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
11,2241720092,js04,p02.py,find_clusters,SUCCESS,2.194000e-04,
12,2241720092,js04,p02.py,plot_pixels,SUCCESS,3.600000e-06,
13,2241720092,js04,p03.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
14,2241720092,js04,tp.py,NO_FUNCTION,NO FUNCTION,NaN,No function detected
15,2241720092,js13,p01.py,sigmoid,SUCCESS,2.500000e-06,
16,2241720092,js13,p01.py,sigmoid_derivative,SUCCESS,8.000000e-07,
17,2241720092,js13,p01.py,sigmoid,SUCCESS,2.700000e-06,
18,2241720092,js13,p01.py,sigmoid_derivative,SUCCESS,7.000000e-07,
19,2241720092,js13,p01.py,relu,SUCCESS,1.800000e-06,

=================== 10 Function Terlama ====================

,nim,module,file_name,function_name,execution_time_seconds
7232,2341720174,js05,tp.py,simple_plot,0.255428
296,2341720007,pbl,Notebook_PCVK_Patch_ML 21K-train-20.py,prepare_dataset,0.003369
1237,2341720007,pbl,Notebook_PCVK_Patch_ML train-60.py,segment_u2netp,0.002769
593,2341720007,pbl,Notebook_PCVK_Patch_ML 21K-train-70.py,visualize_haralick_features,0.002378
3916,2341720088,pbl,main.py,startup_event,0.002268
7787,2341720200,pbl,Notebook_PCVK_Patch_ML train-40.py,visualize_haralick_features,0.001989
577,2341720007,pbl,Notebook_PCVK_Patch_ML 21K-train-70.py,segment_u2netp,0.001585
357,2341720007,pbl,Notebook_PCVK_Patch_ML 21K-train-30.py,segment_u2netp,0.001499
742,2341720007,pbl,Notebook_PCVK_Patch_ML 21K-train-95.py,segment_u2netp,0.001325
8509,2341720227,pbl,Notebook_PCVK_Patch_ML 21K-train-30.py,segment_u2netp,0.001295

=================== 10 Function Tercepat ===================

,nim,module,file_name,function_name,execution_time_seconds
4005,2341720093,js13,p01.py,sigmoid_derivative,5.000000e-07
4325,2341720108,pbl,ANN_SPLIT_10_90.py,get_augmented_image,5.000000e-07
201,2341720005,js13,p01.py,sigmoid_derivative,5.000000e-07
10195,2341720234,pbl,SVM_SPLIT_70_30.py,get_augmented_image,6.000000e-07
3111,2341720062,pbl,ANN_SPLIT_10_90.py,get_augmented_image,6.000000e-07
3243,2341720062,pbl,SVM_SPLIT_50_50.py,get_augmented_image,6.000000e-07
10204,2341720234,pbl,SVM_SPLIT_80_20.py,get_augmented_image,6.000000e-07
10207,2341720234,pbl,SVM_SPLIT_80_20.py,get_augmented_image,6.000000e-07
4490,2341720108,pbl,SVM_SPLIT_80_20.py,get_augmented_image,6.000000e-07
4334,2341720108,pbl,ANN_SPLIT_20_80.py,get_augmented_image,6.000000e-07

Diproses pada 2026-04-07 22:38:14

In [ ]:
# ============================================================
# COMPARISON TABLE — FILE LEVEL vs FUNCTION LEVEL
# Tujuan : Membandingkan runtime file-level (cProfile)
#          dengan akumulasi runtime function-level (timeit)
# ============================================================

COMPARE_REPORT = os.path.join(DIRS["LOGS"], "07_compare_runtime.xlsx")

# --- 1) Ambil runtime function yang sukses ---
df_func_success = df_runtimeFunct[
    df_runtimeFunct["status"] == "SUCCESS"
].copy()

# jumlah runtime function per file
df_func_sum = (
    df_func_success
    .groupby(["nim", "module", "file_name"], as_index=False)
    ["runtime_seconds"]
    .sum()
    .rename(columns={
        "runtime_seconds": "runtime_function_sum"
    })
)

# --- 2) Ambil file-level yang sukses ---
df_file_success = df_cprofile[
    df_cprofile["status"] == "SUCCESS"
].copy()

# --- 3) Gabungkan kedua hasil ---
df_compare = df_file_success.merge(
    df_func_sum,
    on=["nim", "module", "file_name"],
    how="left"
)

# isi NaN jika file tidak punya runtime function sukses
df_compare["runtime_function_sum"] = (
    df_compare["runtime_function_sum"]
    .fillna(0)
    .round(7)
)

# rename runtime file-level
df_compare = df_compare.rename(columns={
    "execution_time_seconds": "runtime_file_level"
})

# --- 4) Hitung gap ---
df_compare["gap"] = (
    df_compare["runtime_file_level"]
    - df_compare["runtime_function_sum"]
).round(7)

# --- 5) Hitung gap percent ---
df_compare["gap_percent"] = (
    (
        df_compare["gap"]
        / df_compare["runtime_file_level"]
    )
    .replace([float("inf"), -float("inf")], 0)
    .fillna(0)
    * 100
).round(2)

# --- 6) Pilih kolom final ---
df_compare = df_compare[
    [
        "nim",
        "module",
        "file_name",
        "function_count",
        "runtime_file_level",
        "runtime_function_sum",
        "gap",
        "gap_percent"
    ]
].copy()

# tambahkan nomor urut
df_compare.insert(0, "no", range(1, len(df_compare) + 1))

# --- 7) Simpan report ---
df_compare.to_excel(COMPARE_REPORT, index=False)

print("=" * 90)
print(f"{'PERBANDINGAN FILE LEVEL vs FUNCTION LEVEL':^90}")
print("=" * 90)
print("-" * 90)
print(f"Rata-rata gap         : {df_compare['gap'].mean():.7f}")
print(f"Rata-rata gap percent : {df_compare['gap_percent'].mean():.2f}%")
print(f"Gap terbesar          : {df_compare['gap'].max():.7f}")
print(f"Gap percent terbesar  : {df_compare['gap_percent'].max():.2f}%")
print(f"Hasil disimpan di     : {COMPARE_REPORT}")
print("-" * 90)

display(df_compare.head(20))

In [ ]:
# ============================================================
# 1) DATASET SUMMARY
# ============================================================
total_repo = len([
    d for d in os.listdir(DATASET_INPUT)
    if os.path.isdir(os.path.join(DATASET_INPUT, d))
])

total_file = len(df_cprofile)

total_function = (
    df_runtimeFunct["function_name"] != "NO_FUNCTION"
).sum()

total_file_no_function = (
    df_runtimeFunct["status"] == "NO FUNCTION"
).sum()

print("=" * 90)
print(f"{'RINGKASAN DATASET PERBANDINGAN RUNTIME':^90}")
print("=" * 90)
print(f"{'Total Repository':<35}: {total_repo}")
print(f"{'Total File':<35}: {total_file}")
print(f"{'Total Function':<35}: {total_function}")
print(f"{'Total File tanpa Function':<35}: {total_file_no_function}")
print("-" * 90)


# ============================================================
# 2) FUNCTION LEVEL SUM PER FILE
# ============================================================
df_func_success = df_runtimeFunct[
    df_runtimeFunct["status"] == "SUCCESS"
].copy()

df_func_sum = (
    df_func_success
    .groupby(["nim", "module", "file_name"], as_index=False)
    ["execution_time_seconds"]
    .sum()
    .rename(columns={
        "execution_time_seconds": "runtime_function_sum"
    })
)


# ============================================================
# 3) FILE LEVEL SUCCESS
# ============================================================
df_file_success = df_cprofile[
    df_cprofile["status"] == "SUCCESS"
].copy()


# ============================================================
# 4) MERGE FILE vs FUNCTION
# ============================================================
df_compare = df_file_success.merge(
    df_func_sum,
    on=["nim", "module", "file_name"],
    how="left"
)

df_compare["runtime_function_sum"] = (
    df_compare["runtime_function_sum"]
    .fillna(0)
    .round(7)
)

df_compare = df_compare.rename(columns={
    "execution_time_seconds": "runtime_file_level"
})


# ============================================================
# 5) GAP & GAP PERCENT
# ============================================================
df_compare["gap"] = (
    df_compare["runtime_file_level"]
    - df_compare["runtime_function_sum"]
).round(7)

df_compare["gap_percent"] = (
    (
        df_compare["gap"]
        / df_compare["runtime_file_level"]
    )
    .replace([float("inf"), -float("inf")], 0)
    .fillna(0)
    * 100
).round(2)


# ============================================================
# 6) FINAL TABLE
# ============================================================
df_compare = df_compare[
    [
        "nim",
        "module",
        "file_name",
        "function_count",
        "runtime_file_level",
        "runtime_function_sum",
        "gap",
        "gap_percent"
    ]
].copy()

df_compare.insert(0, "no", range(1, len(df_compare) + 1))


# ============================================================
# 7) SAVE REPORT
# ============================================================
df_compare.to_excel(COMPARE_REPORT, index=False)

print(f"{'PERBANDINGAN FILE LEVEL vs FUNCTION LEVEL':^90}")
print("=" * 90)
print(f"Total file dibandingkan : {len(df_compare)}")
print(f"Hasil disimpan di       : {COMPARE_REPORT}")
print("-" * 90)

display(df_compare.head(20))


# ============================================================
# 8) GAP SUMMARY
# ============================================================
print("-" * 90)
print(f"{'Rata-rata Gap':<35}: {df_compare['gap'].mean():.7f}")
print(f"{'Rata-rata Gap Percent':<35}: {df_compare['gap_percent'].mean():.2f}%")
print(f"{'Gap Maksimum':<35}: {df_compare['gap'].max():.7f}")
print(f"{'Gap Percent Maksimum':<35}: {df_compare['gap_percent'].max():.2f}%")